### ISSUE TITLE
Support for google API client (via httplib2)

### ISSUE THREAD

**Issue by HonzaKral** [elastic/apm-agent-python#1022]
**Describe the solution you'd like**: I would like http requests done by `httplib2` captured the same as from the other http libraries.

**Additional context**: `httplib2` library is used in the [google API client](https://github.com/googleapis/google-api-python-client) which would be extremely useful to see as spans.

I would be happy to work on a PR if it would be accepted.

Thank you!

**Comment by beniwohli** [comment]
Hey @HonzaKral! Yes, that seems like a sizeable gap in our instrumentation story! A PR would be great! The [`urllib3`](https://github.com/elastic/apm-agent-python/blob/15278433c97d9c81c5ad1dcdf57d27da847be912/elasticapm/instrumentation/packages/urllib3.py) instrumentation and [tests](https://github.com/elastic/apm-agent-python/blob/15278433c97d9c81c5ad1dcdf57d27da847be912/tests/instrumentation/urllib3_tests.py) could serve as a starting point. There's also quite a bit of [boilerplate](https://github.com/elastic/apm-agent-python/blob/master/CONTRIBUTING.md#adding-new-instrumentations-to-the-matrix-build)  required to add a new instrumentation to the test matrix :see_no_evil: (feel free to leave that part to us :D ).
