### ISSUE TITLE
capture_body makes requests hangs / validation error

### ISSUE THREAD

**Issue by Syniex** [elastic/apm-agent-python#1032]
**Describe the bug**: 
When using CAPTURE_BODY:
1) "all" - you get "validation error: error: context: request: 'body': validation rule 'types(string;map[string]interface)' violated "
2) "errors" - sending httpx request to unreachable address, the client gets stuck and no repsonse is returned to the client

**To Reproduce**

1. Create FastAPI.
2. do any request using  httpx.AsyncClient to unknown request (ex: localhost: 5050)
3. if your CAPTURE_BODY is set to all, you will get validation error
4. if your CAPTURE_BODY is set to errors, the requests will hang forever

**Environment (please complete the following information)**
- OS: [e.g. Linux]: Docker python:3.8.2-slim-buster
- Python version: 3.8.2
- Framework and version [e.g. Django 2.1]: FastAPI 63.0
- APM Server version: 7.10.2
- Agent version: 5.10.1

**Additional context**

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    apm_config = {
        "SERVICE_NAME": "map",
        "ENABLED": True,
        "SERVER_URL": "http://**********:8200",
        "CAPTURE_HEADERS": True,
        "CAPTURE_BODY": "all",
    }
    ```
  </details>
- `requirements.txt`:
  <details>
    <summary>Click to expand</summary>

    ```
    aiofiles
    aredis
    async-timeout
    asyncpg
    authlib
    certifi
    cffi
    chardet
    click
    cryptography
    debugpy
    python-dateutil
    ecdsa<0.15
    elastic-apm
    fastapi
    gunicorn
    h11
    h2
    hiredis
    hpack
    hstspreload
    httpcore
    httptools
    httpx
    hyperframe
    idna
    loguru
    orjson
    pyasn1
    pycparser
    pydantic
    python-jose
    python-multipart
    rfc3986
    rsa
    six
    sniffio
    starlette==0.13.6
    ujson
    uvicorn
    uvloop
    websockets
    # yappi
    ```
  </details>

**Comment by Syniex** [comment]
After debugging a little, it's related to the body payload, it seems flat body like: [10,20] will make it not work

**Comment by basepi** [comment]
@Syniex To clarify, using a flat body like that will make the request hang? Does it hang even without the agent present? If the agent makes the application hang for any reason, we consider that a bug.

**Comment by Syniex** [comment]
without the agent the application doesn't hangs.

**Comment by Syniex** [comment]
I will provide code tomorrow, and dig deeper to it.

**Comment by basepi** [comment]
Thank you. This sounds like something we would like to fix.

**Comment by Syniex** [comment]
`python
from typing import List

import httpx
import uvicorn
from elasticapm.contrib.starlette import ElasticAPM, make_apm_client
from fastapi import FastAPI
from pydantic import BaseModel


class Point(BaseModel):
    coordinates: List[float]


app = FastAPI()
apm_config = {
    "SERVICE_NAME": "testing",
    "ENABLED": True,
    "SERVER_URL": "http://localhost:8200",
    "CAPTURE_HEADERS": True,
    "CAPTURE_BODY": "error",
    # "CAPTURE_BODY": "all",
}
apm = make_apm_client(apm_config)
app.add_middleware(ElasticAPM, client=apm)


class RandomError(BaseException):
    pass


@app.post("/working")
async def working_fine():
    #Example of working endpoint when no body is provided
    async with httpx.AsyncClient() as client:
        response = await client.get("http://notexisthost/")
        return response.json()


@app.post("/not/working/1")
async def not_working(point: Point):
    # This won't work when using "CAPTURE_BODY": "errors" and will hang the request forever
    async with httpx.AsyncClient() as client:
        response = await client.get("http://notexisthost/")
        return response.json()


@app.post("/not/working/2")
async def not_working_2(coordinates: List[float]):
    # "CAPTURE_BODY": "all" will make elasticsearch says "body": validation error
    async with httpx.AsyncClient() as client:
        response = await client.get("http://notexisthost/")
        return response.json()


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0")
`

**Comment by Syniex** [comment]
@basepi I checked the commit and the application doesn't hangs anymore.

but the Validation error is still there.

```python
from typing import List

import uvicorn
from elasticapm.contrib.starlette import ElasticAPM, make_apm_client
from fastapi import FastAPI

app = FastAPI()
apm_config = {
    "SERVICE_NAME": "testing",
    "ENABLED": True,
    "SERVER_URL": "http://localhost:8200",
    "CAPTURE_HEADERS": True,
    "CAPTURE_BODY": "all",
}
apm = make_apm_client(apm_config)
app.add_middleware(ElasticAPM, client=apm)


@app.post("/validation/error")
async def working_fine(coordinates: List[float]):
    # Example of working endpoint when no body is provided
    return "Done"


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", debug=False)

```

**Comment by basepi** [comment]
Oh, right, sorry, I got so hung up on the hang (which was definitely the biggest problem) that I forgot to look at the validation issues. Thanks for attaching an example error, that will be helpful.
