### ISSUE TITLE
Django Middleware and ASGI 

### ISSUE THREAD

**Issue by thenewguy** [elastic/apm-agent-python#1047]
I read that middleware was working last March per https://github.com/elastic/apm-agent-python/issues/737#issuecomment-597288157 so I have been investigating a transition from WSGI to ASGI.

I am hitting this problem:

```
 Traceback (most recent call last):
   File "/django/core/handlers/exception.py", line 47, in inner
     response = get_response(request)
   File "/django/utils/deprecation.py", line 116, in __call__
     response = self.process_response(request, response)
   File "/elasticapm/contrib/django/middleware/__init__.py", line 114, in process_response_wrapper
     response = wrapped(*args, **kwargs)
   File "/wagtail/contrib/redirects/middleware.py", line 37, in process_response
     if response.status_code != 404:
 AttributeError: 'coroutine' object has no attribute 'status_code'
```

Relevant packages per the linked issue comment
```
Python 3.7.10
elastic-apm==6.0.0
asgiref==3.3.1
Django==3.1.6
```

Any tips?

**Comment by beniwohli** [comment]
@thenewguy looking at the traceback, it's not immediately clear to me that this is caused by the agent. Does the error disappear if you remove `elasticapm` from `INSTALLED_APPS`?

**Comment by thenewguy** [comment]
`ELASTIC_APM_DJANGO_AUTOINSERT_MIDDLEWARE = False` would be the same thing right?

**Comment by beniwohli** [comment]
@thenewguy actually, can you first try with `export ELASTIC_APM_INSTRUMENT_DJANGO_MIDDLEWARE=False`? By default, we instrument all class based middleware so we can detect redirects that are caused by a middleware and not a view. But reading through Django's docs, we might not handle that correctly. Changing this setting to `False` only deactivates that redirect-detection, everything else should work normally.

**Comment by thenewguy** [comment]
No change with the env var

**Comment by thenewguy** [comment]
After removing elasticapm from installed apps it seems like this isn't an elasticapm problem and it was just in the traceback.

Should there be an issue for `export ELASTIC_APM_INSTRUMENT_DJANGO_MIDDLEWARE=False` not preventing the middleware from being installed?

**Comment by beniwohli** [comment]
@thenewguy `ELASTIC_APM_INSTRUMENT_DJANGO_MIDDLEWARE` doesn't prevent installation of our middleware, but instrumentation of all other middleware. I suspected that there could be an issue with our middleware instrumentation, but that turned out to be not the case.
