### ISSUE TITLE
Using use_elastic_excepthook throws TypeError

### ISSUE THREAD

**Issue by philipp-sontag-by** [elastic/apm-agent-python#1049]
**Describe the bug**:
When using the option [use_elastic_excepthook](https://www.elastic.co/guide/en/apm/agent/python/master/configuration.html#config-use-elastic-excepthook) every uncaught exception also produces the following `TypeError`:

```bash
Error in sys.excepthook:
TypeError: _excepthook() takes 1 positional argument but 4 were given
```

**To Reproduce**

Run the following Python snippet
```python
import elasticapm


def run():
    raise Exception("hello")

client = elasticapm.Client(
    {"SERVICE_NAME": "test"},
    use_elastic_excepthook=True,
)
run()
```
It will produce this output:

```bash
Error in sys.excepthook:
TypeError: _excepthook() takes 1 positional argument but 4 were given

Original exception was:
Traceback (most recent call last):
  File "t.py", line 13, in <module>
    run()
  File "t.py", line 5, in run
    raise Exception("hello")
Exception: hello
```

**Environment (please complete the following information)**
- OS: MacOS 10.15.3
- Python version: 3.8.5
- Agent version: 6.0.0

**Additional context**

The problem seems to be with the function signature of the [Client._excepthook](https://github.com/elastic/apm-agent-python/blob/b7e408a7b8c9554c0ee74a5b7e7c6347b4b814f2/elasticapm/base.py#L567) function that is used to override the `sys.excepthook`.

The [sys.excepthook](https://docs.python.org/3/library/sys.html#sys.excepthook) expects three arguments (type, value, traceback), while the `Client._excepthook` only expects the `self` argument.

**Comment by basepi** [comment]
Thanks for reporting this! We'll get it fixed.
