### ISSUE TITLE
Accessing APM client in Django Integration

### ISSUE THREAD

**Issue by josefkorbel** [elastic/apm-agent-python#1059]
Hello!

I am using APM integration for Django, everything works fine, however I am doing some tasks on background in uWSGI spooler and want to connect the trace for the HTTP request (invocation).

However I cannot find a way to access the APM client object in django (as django is initializing this automatically and the docs says I should treat it as singletone - I dont want to create new instance of apm agent in different uwsgi spooler thread because I am worried about race conditions.
I've tried the `elasticapm.contrib.django.client.ProxyClient`, which states:
```python
class ProxyClient(object):
    """
    A proxy which represents the current client at all times.
    """
```

But when trying to `begin_transaction` with this ProxyClient instance from `elasticapm.contrib.django.client`, it throws an exception:

```
'elasticapm.contrib.django.client' has no attribute 'begin_transaction'
```

How to access the apm client object when using Django integration?

EDIT:
Also found `get_client` function in `elasticapm.base` which is supposed to work as a singleton getter, but I am not able to import this function anyhow.

**Comment by basepi** [comment]
@josefkorbel The `elasticapm.get_client()` function is new, and has not been released yet. But that will be the easiest way for you to get the client once we release a new version of the agent. You could try installing from `master` to test, in the meantime.

**Comment by josefkorbel** [comment]
Thank you very much for such a fast reply, I'll test with master.
