### ISSUE TITLE
How to iterate through children spans from current transaction ?

### ISSUE THREAD

**Issue by NielkS** [elastic/apm-agent-python#1085]
**Is your feature request related to a problem? Please describe.**
A common problem of relying on an ORMs is the "N+1 queries" pattern.
To make sure that application performances are fine, I want to add transaction labels with number of spans per type / subtype.

**Describe the solution you'd like**
I think the best way to do that would be in a middleware, at the very end of the transaction execution.
I would like to be able to write this:
```
import collections
import elasticapm

class AddCountPerSpanTypeMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        res = self.get_response(request)

        apm_transaction = elasticapm.traces.execution_context.get_transaction()        ​
       ​if not apm_transaction.spans:
           ​return res

       ​breakdown_per_type = collections.defaultdict(int)
       ​for a_span in (apm_transaction.spans or tuple()):
           ​breakdown_per_type[a_span.type]  += 1
           ​if a_span.subtype:
               ​breakdown_per_type[a_span.type + '/' + a_span.subtype] += 1

       ​elasticapm.tag(span_count_by_time=dict(breakdown_per_type.items())
       return res

```

But as I understand it, the current data model links a span to a transaction, but not the other way around: the `Transaction` class does not have a `spans` property

**Describe alternatives you've considered**
I managed to work around this by patching `Transaction.track_span_duration`, but this is just a hack at the moment

```
import elasticapm.traces

original_track_span_duration = elasticapm.traces.Transaction.track_span_duration

def patched_track_span_duration(transaction, span_type, span_subtype, self_duration):
    original_track_span_duration(span, span_type, span_subtype, self_duration)
    if not hasattr(transaction, 'breakdown_per_type'):
        transaction.breakdown_per_type = collections.defaultdict(int)
    transaction.breakdown_per_type[span_type] += 1
    if span_subtype:
        transaction.breakdown_per_type[span_type + '/' + span_subtype] += 1


elasticapm.traces.Transaction.track_span_duration = patched_track_span_duration

```

**Additional context**
Linking transaction and spans objects in both directions may create ref-cycles, maybe that's why it has not been implemented so far ?
For the particular usecase I describe, I don't need the full Span objects, just their type & subtypes.

**Comment by basepi** [comment]
I don't think this is a data model change that we're going to make. A transaction can have unlimited spans attached to it, and tracking them in the transaction object could be costly, when on the Elasticsearch end it's trivial to query out all spans that are tied to a given transaction. 

It's possible that this could be a useful feature in Kibana. You might consider opening an issue over in https://github.com/elastic/apm with more information on how you use this information.
