### ISSUE TITLE
Botomongo - S3 spans throwing an "validation error: span: context: destination: service: 'name' required"

### ISSUE THREAD

**Issue by tonyman19** [elastic/apm-agent-python#1089]
**Flask Python application doesn't record the SPAN with S3 call**:

**To Reproduce**

1. Flask Application doing S3 call
2. In console you will see the exception `Failed to submit message: 'HTTP 400: {"accepted":3,"errors":[{"message":"validation error: span: context: destination: service: \'name\' required",...`

**Environment (please complete the following information)**
- OS: Linux
- Python version: 3.6
- Framework and version: Flask 1.1.2
- APM Server version: v7.12.0
- Agent version: 6.1.0

**From the APM version 7.12 name field is required**

Problem is located here:
elasticapm/instrumentation/packages/botocore.py
`context["destination"]["service"] = {"type": span_type}`
for destination.service there is no destination.service.name element

IMHO: destination.service.name should be set as in the elasticapm/instrumentation/packages/elasticsearch.py

**Comment by beniwohli** [comment]
@tonyman19 thanks for the heads up! I opened a PR with a fix in #1090. Will do a release ASAP!

**Comment by tonyman19** [comment]
Reviewed the PR - looks good!

**Comment by beniwohli** [comment]
@tonyman19 thanks for the review! The fix is released in version 6.1.1 of the agent. Thanks again for the report!
