### ISSUE TITLE
Root Django URL doesn't appear in the UI when using routes

### ISSUE THREAD

**Issue by HonzaKral** [elastic/apm-agent-python#1092]
**Describe the bug**: `transaction.name` field is missing from the `transcction` document

**To Reproduce**

1. set `DJANGO_TRANSACTION_NAME_FROM_ROUTE` to `True`
2. have url of `path("", TemplateView.as_view(template_name="pages/home.html"), name="home")`
3. ...
4. not profit

**Environment (please complete the following information)**
- OS: Linux
- Python version: 3.8
- Framework and version [e.g. Django 2.1]: Django 3.1.6
- APM Server version: 7.12
- Agent version:6.1.1

**Comment by beniwohli** [comment]
@HonzaKral thanks for the report! I opened a PR that uses the URL name or the function name as fallbacks: https://github.com/elastic/apm-agent-python/pull/1095
