### ISSUE TITLE
Make elastic-apm available via conda-forge.

### ISSUE THREAD

**Issue by tobiasraabe** [elastic/apm-agent-python#1103]
Hi everybody,

thanks for providing this package. I would like to install elastic-apm via conda, but the package is currently not available. Thus, I started a PR for the conda-forge channel. Would you like to be listed as maintainers?

Maintainer status would allow you to publish new versions. For example, you upgrade the release on PyPI which automatically creates a PR in the conda-forge feedstock to bump and build the new version. You only have to merge the PR and maybe add a dependency to the recipe if you make such changes.

https://github.com/conda-forge/staged-recipes/pull/14608

**Comment by beniwohli** [comment]
Hey @tobiasraabe! I haven't used Conda myself yet, but I think it would be great if the agent was installable that way. Thanks for creating the recipe! I'd be happy to be added as a maintainer. @basepi should also be added, but he is currently on PTO, so he'd  not be able to write a confirmatory comment on the github issue for some time. Can we add him on a later date?

**Comment by tobiasraabe** [comment]
Sure, we can do that later. I added you as a maintainer. If you could state your consent, I will ask the conda-forge team for a review.

**Comment by beniwohli** [comment]
Closing this as elastic-apm is now available on Conda
