### ISSUE TITLE
No module named 'elasticapm'

### ISSUE THREAD

**Issue by abiral-sijaria** [elastic/apm-agent-python#1105]
**Describe the bug**: ...
When I install the package using `pip install elastic-apm`, the elasticapm module is not found in the library. My pip is pointing to `/usr/local/lib/python3.8/site-packages/pip`. When I change this to point at Macpython `/Library/Frameworks/Python.framework`, it works fine. I need to why It is failing since the same is happening inside my Kubernetes pod as well.

**To Reproduce**

1. ...install the package using `pip install elastic-apm`
2. ...try importing like this `from elasticapm.contrib.django import *`
3. ...you would encounter something like this: `No module named 'elasticapm'`

**Environment (please complete the following information)**
- OS: Mac OS
- Python version: 3.8.6
- Pip version: 20.2.1
- Framework and version [e.g. Django 2.1]:2.2.6

**Comment by Sparkycz** [comment]
If you want to use Elastic APM agent under the framework Django, follow these instructions https://www.elastic.co/guide/en/apm/agent/python/current/django-support.html

If you want to use the agent out of a framework, follow these instructions https://www.elastic.co/guide/en/apm/agent/python/current/instrumenting-custom-code.html#instrumenting-custom-code-transactions

**Comment by basepi** [comment]
Hey @abiral-sijaria, I'm going to close this since we never heard back from you. Please comment if you still need help!
