### ISSUE TITLE
Reduce default stack_trace_limit from 500 to 50

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-python#1128]
Looking through the [config docs](https://docs.google.com/spreadsheets/d/1JJjZotapacA3FkHc2sv_0wiChILi3uKnkwLTjtBmxwU/edit#gid=0&range=A63), all other agents set the default limit to 50.

Setting a modest limit for the stack traces is important for APM Server to avoid out of memory issues when the in-memory queue fills up. The APM Server's queue size is measured in the number of events, not bytes. Therefore, it's important to be able to estimate the maximum event size in bytes so that we can provision an appropriate amount of memory for the default queue size.

cc @simitt

**Comment by Sparkycz** [comment]
[good first issue](https://github.com/elastic/apm-agent-python/issues?q=is%3Aissue+is%3Aclosed+label%3A%22good+first+issue%22 ) label? :-)
