### ISSUE TITLE
I[#/name] S[#/allOf/1/properties/name/type] expected string or null, but got array

### ISSUE THREAD

**Issue by cuber3x3** [elastic/apm-agent-python#1146]
Hi,

I'm randomly getting this error in my logs : 

Failed to submit message: 'HTTP 400: {"accepted":7,"errors":[{"message":"failed to validate transaction: error validating JSON: I[#] S[#] doesn\'t validate with \\"transaction#\\"\\n  I[#] S[#/allOf/1] allOf failed\\n    I[#/name] S[#/allOf/1/properties/name/type] expected string or null, but got array"

I'm not sure what allOf/1/properties/name/type is and how I can change it's value ?
Is there a document referencing these ?

**Comment by beniwohli** [comment]
Hi @cuber3x3. The message indicates that the name of a transaction was set to be an array instead of a string somewhere. Do you use [`elasticapm.set_transaction_name()`](https://www.elastic.co/guide/en/apm/agent/python/current/api.html#api-set-transaction-name) somewhere in your code? If not, what framework do you use the agent with? E.g. Django, Flask, ...

**Comment by cuber3x3** [comment]
Hello @beniwohli thank you so much, indeed I forced the transaction name to string and didn't have the error anymore.
However I can't see any funky transaction names in Kibana's APM, so not sure what was causing this and why it's not appearing in the transactions name list..
Anyway, that's great not to have the logs clogged by these messages anymore, thanks !

**Comment by beniwohli** [comment]
@cuber3x3 great to hear that you managed to solve it! The reason why you don't see any weird names in the transaction list is that the APM Server discarded those transactions as they wouldn't fit into the given schema.

We could however try and force the name to string in `set_transaction_name()` to avoid this from happening to other users going forward. I'll open an issue for that.
