### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [elastic/apm-agent-python#1151]
Problem
---------
On aarch64, ‘pip install elastic-apm’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes more time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, ‘pip install elastic-apm’ should download the wheels from pypi
 @beniwohli, Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by beniwohli** [comment]
Hi @odidev! Yes, that would be great! We use cibuildwheel to build binary wheels. cibuildwheel [does support](https://cibuildwheel.readthedocs.io/en/stable/faq/#emulation) building for aarch64 using qemu.

We run cibuildwheel on our own Jenkins installation, not on e.g. Github Actions (like the cibuildwheel examples). We'd need to ensure that qemu is available on the machine. I'll check with our Jenkins team if that would be possible.

**Comment by odidev** [comment]
@beniwohli, Could you please let me know if you got any chance to look into this.

**Comment by beniwohli** [comment]
@odidev our CI/Jenkins team had a lot of work on their plate, but they prioritized this issue now.

**Comment by odidev** [comment]
Hi @beniwohli, do you have any updates on this issue? Thanks

**Comment by basepi** [comment]
Unfortunately no updates yet. The CI team hasn't had a chance to get to this.
