### ISSUE TITLE
Starlette/FastAPI python agent setup examples result in TypeError

### ISSUE THREAD

**Issue by jwhite3** [elastic/apm-agent-python#1160]
When following the [example](https://www.elastic.co/guide/en/apm/agent/python/current/starlette-support.html#starlette-fastapi) of setting up the Elastic APM agent with python + FastAPI, we find that we can't use `make_apm_client` as described as it has a required positional argument, `config`. The documentation however says that we should be able to call `make_apm_client` with no arguments and in that case it should look for environment variables and/or use defaults. 

**To Reproduce**
Follow the example exactly: 
```python
from fastapi import FastAPI
from elasticapm.contrib.starlette import make_apm_client, ElasticAPM

apm = make_apm_client()
# Client fails to start due to TypeError: TypeError: make_apm_client() missing 1 required positional argument: 'config'

app = FastAPI()
app.add_middleware(ElasticAPM, client=apm)
```

**Environment (please complete the following information)**
- OS: Mac, Linux, Ubuntu
- Python version: 3.8.8
- Framework and version [e.g. Django 2.1]: fastapi==0.65.1
- APM Server version: latest
- Agent version: 6.2.2

**Comment by beniwohli** [comment]
Hi @jwhite3! Thanks for opening the issue, this is indeed a bug. I opened #1161 to address it.

**Comment by jwhite3** [comment]
Awesome, thanks @beniwohli
