### ISSUE TITLE
Update supported Redis

### ISSUE THREAD

**Issue by thenewguy** [elastic/apm-agent-python#1179]
Per [supported technology docs](https://github.com/elastic/apm-agent-python/blob/master/docs/supported-technologies.asciidoc#redis), redis client support is `>=2.8,<3.2.0`.  Please revisit this as `<3.2.0` means not updated since Janurary 2019 per https://pypi.org/project/redis/#history

**Comment by basepi** [comment]
Thanks for this. Looks like our CI is testing against [lastest redis](https://github.com/elastic/apm-agent-python/blob/master/tests/requirements/reqs-redis-newest.txt) so I think we can just remove the upper limit on that doc. I'll submit a PR shortly.
