### ISSUE TITLE
IT is open APM Elastic 

### ISSUE THREAD

**Issue by prashantnitt07** [elastic/apm-agent-python#129]
hi ,
i want install ELastic APM on python application . it is open source ?

**Comment by beniwohli** [comment]
Hi

Yes, the Python Elastic APM agent is open source under the [BSD-3-Clause license](https://github.com/elastic/apm-agent-python/blob/master/LICENSE).

If you have any further questions, can I ask you to use our forum at [discuss.elastic.co](https://discuss.elastic.co/c/apm)? 

Cheers
