### ISSUE TITLE
Cookie value from request header is not getting sanitized

### ISSUE THREAD

**Issue by phkavitha** [elastic/apm-agent-python#1297]
Hi, 

The APM python agent is silently throwing error when trying to sanitize the cookie value from request header. On debugging, I found that we are reading the cookie value incorrectly from context. 
 
Instead of  reading the cookie value using `event["context"]["request"]["headers"]["Cookie"]`, we read it as `event["context"]["request"]["headers"]["cookie"]`. 

https://github.com/elastic/apm-agent-python/blob/31c858595db709c766226e5cddb826d27e377d9d/elasticapm/processors.py#L116

**Comment by basepi** [comment]
Thanks for the report! Should be an easy fix.
