### ISSUE TITLE
Flask error handling removes error transactions from APM 

### ISSUE THREAD

**Issue by davidshaw2018** [elastic/apm-agent-python#1298]
**Describe the bug**: 

I'm running a Python Flask application and connected it to APM. However, I've noticed that when I add an error handler to my application as below, APM will see the error without providing a stack trace. 

```@app.errorhandler(Exception)
    def handle_anything(error):
        try:
            status_code = error.status_code
        except AttributeError:
            status_code = 500
        response_dict = {"type": str(type(error)), "exception_message": str(error)}
        app.logger.exception(response_dict, status_code=status_code)
        response = jsonify(error=response_dict)
        response.content_type = "application/json"
        response.status_code = status_code
        return response
```

Without this error handling, the trace appears as expected. Screenshots and further description are provided in https://discuss.elastic.co/t/flask-error-handling-removes-error-transactions-from-apm/281725/3. In that thread Colton suggested it might be a bug, and to report it here. 

**Environment (please complete the following information)**
- OS: Linux
- Python version: 3.7.7
- Framework and version [e.g. Django 2.1]: Flask 1.1.2
- APM Server version: 7.11.0
- Agent version: 6.3.3

**Additional context**

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
        from elasticapm.contrib.flask import ElasticAPM
        from flask_sqlalchemy import SQLAlchemy
        app = Flask(__name__)

        app.config['ELASTIC_APM'] = {
            'SERVICE_NAME': web_config.apm_server_name,
            'SERVER_URL': f"http://{web_config.apm_server_url}:{web_config.apm_port}",
            'ENVIRONMENT': 'development'
        }
        ElasticAPM(app)
        DB = SQLAlchemy()
        DB.init_app(app)
    ```
  </details>
- `requirements.txt`:
  <details>
    <summary>Click to expand</summary>

    ```
    'flask',
    'flask_cors',
    'Flask-SQLAlchemy',
    'elastic-apm[flask]',
    'pymysql',  # install MySQLdb/mysqlclient for more performance
    'python-logstash-async',
    'sqlalchemy==1.3',
    ```
  </details>

**Comment by basepi** [comment]
Ah, ok, I think I've figured this out. Our flask integration only captures unhandled exceptions. By installing an error handler which handles `Exception`, you've ensured that there will be no unhandled exceptions.

The reason it still shows in the error graph is because we're setting the transaction outcome to a failure (due to the 500 status code).

If you also want the stacktrace in these cases, you need to call `elasticapm.capture_exception` (assuming you named your `ElasticAPM` object `elasticapm`):

```python
@app.errorhandler(Exception)
    def handle_anything(error):
        elasticapm.capture_exception(exc_info=(type(error), error, error.__traceback__))
        try:
            status_code = error.status_code
        except AttributeError:
            status_code = 500
        response_dict = {"type": str(type(error)), "exception_message": str(error)}
        app.logger.exception(response_dict, status_code=status_code)
        response = jsonify(error=response_dict)
        response.content_type = "application/json"
        response.status_code = status_code
        return response
```

Keep me posted if you have any issues with that!

**Comment by davidshaw2018** [comment]
Interesting, I assumed the status code was the source of truth for errors. I'll see if I can manually capture exceptions, thanks!

**Comment by basepi** [comment]
It is, but you can have a 500 status code without actually throwing an exception (and thus stack trace). Once you've handled the exception you need to manually collect it if you want to treat it as an error -- many handled exceptions don't result in errors, after all!

**Comment by davidshaw2018** [comment]
Gotcha, that was what I was wondering - if I could manually ship the trace to APM. Looks like your suggestion worked! Thanks for the help
