### ISSUE TITLE
APM Python/Starlette agent not working with a GraphQL application

### ISSUE THREAD

**Issue by kleysonr** [elastic/apm-agent-python#1302]
I'm trying to use the apm agent in a python Starlette application (https://www.elastic.co/guide/en/apm/agent/python/master/starlette-support.html)

My starlette app is based on GraphQL app (https://www.starlette.io/graphql/)

After configure the apm agent to monitor my application, I'm getting all the transactions, regardless the endpoint called, aggregated as a `POST /` transaction in the Kibana.

Is APM python agent prepared to work with GraphQL ? How to get the correct graphql transactions ?

Best Regards.

**Comment by kleysonr** [comment]
@basepi Yes. Starlette graphql support is deprecated, but still supporting mounting third-party library that provide GraphQL support.

In my case I'm using Starlette to mount an Ariadne GraphQL application.

```python
from ariadne import make_executable_schema

schema = make_executable_schema(type_defs, resolvers, directives=directives)

def create_app():

    app = Starlette(debug=True)
    app.mount(
        '/graphql',
        GraphQL(
            schema,
            debug=True
        )
    )

    return app
```

**Comment by kleysonr** [comment]
@basepi Use de code below to run a Starlette app mounting a GraphQL Ariadne application.

```txt
ariadne==0.13.0
starlette==0.14.2
uvicorn==0.15.0
elastic-apm==6.3.3
```
```python
import random
import time
from starlette.middleware.cors import CORSMiddleware
from starlette.middleware import Middleware
from starlette.applications import Starlette
from ariadne.asgi import GraphQL
from ariadne import QueryType, gql, make_executable_schema
from elasticapm.contrib.starlette import make_apm_client, ElasticAPM

apm = make_apm_client({
    'SERVICE_NAME': 'pythonapp',
    'SECRET_TOKEN': '12345678',
    'DEBUG': True,
    'SERVER_URL': 'http://localhost:8200',
})    

type_defs = gql("""
    type Query {
        ping1: String!
        randWait1: String!
    }
""")

query = QueryType()

@query.field('ping1')
def resolve_ping(obj, info):

    # try:
    #     1 / 0
    # except ZeroDivisionError:
    #     apm.capture_exception()

    return str(time.time())

@query.field('randWait1')
def resolve_randWait(obj, info):

    w = random.randrange(1,5)
    time.sleep(w)
    return str(w)

schema = make_executable_schema(type_defs, query)

def create_app():

    middleware = [
        Middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"]),
        Middleware(ElasticAPM, client=apm),
    ]

    app = Starlette(debug=True, middleware=middleware)
    app.mount(
        '/graphql',
        GraphQL(
            schema,
            debug=True,
        )
    )

    return app

app = create_app()
```
```
$ uvicorn asgi:app --port 7070 --host 0.0.0.0
```
Then open http://localhost:7070/graphql/

**Comment by basepi** [comment]
Thanks for the sample code! We'll find some time to look into this.

**Comment by kleysonr** [comment]
@basepi Hi.

Did you have a chance to take a look on this ?

I need to bring observability into my application.

Best Regards.

**Comment by basepi** [comment]
I haven't, unfortunately. We're currently reworking how we prioritize these bugs and other community interactions -- it's so easy to fill a release with feature work and then bugs can languish. But we hope to bring more focused attention here soon!

**Comment by process0** [comment]
Can confirm the APM is not working with Ariadne + Starlette

**Comment by beniwohli** [comment]
Hey all

the issue here is that the APM agent can't determine an appropriate transaction name. For e.g. REST APIs or other hierarchical URL systems, we can use the (parametrized) URL as the transaction name. GraphQL uses the same URL endpoint for all calls, so we end up grouping all GraphQL queries together.

A while ago, we merged a PR (https://github.com/elastic/apm-agent-python/pull/850) that derives an appropriate transaction name from a GraphQL query for Graphene 2. Something similar would have to be done for Ariadne and all other GraphQL implementations mentioned here. Unfortunately, we currently don't have the resources to implement this in a timely manner, but if anybody is interested in contributing a PR, I'd be happy to review and merge it.
