### ISSUE TITLE
elasticapm.label() "No transaction currently active." in celery integration. elasticapm.set_custom_context works.

### ISSUE THREAD

**Issue by riccardomassullo** [elastic/apm-agent-python#1330]
**Describe the bug**:
Using Python Celery contrib implementation, i'm trying to use `elasticapm.label()` API instead of `elasticapm.set_custom_context()` in the same point in the code (in a transaction specifically) doesn't seem to work and return an error.

This works as intended:
``` python
import elasticapm
from elasticapm.contrib.celery import register_exception_tracking, register_instrumentation

from .celery_app import app

elasticapm.instrument()
apm_client = elasticapm.Client()
register_instrumentation(apm_client)
register_exception_tracking(apm_client)

@app.task(bind=True, base=CustomBaseTaskClass)
def MyCoolFunction(self, instance_id, payload: str) -> int:
    elasticapm.set_custom_context({
        'instance_id': instance_id,
        'queue_name': self.request.delivery_info['routing_key'],
        'job_id': self.request.id
    })

    ...
```
This, isn't working:
```python
import elasticapm
from elasticapm.contrib.celery import register_exception_tracking, register_instrumentation

from .celery_app import app

elasticapm.instrument()
apm_client = elasticapm.Client()
register_instrumentation(apm_client)
register_exception_tracking(apm_client)

@app.task(bind=True, base=CustomBaseTaskClass)
def MyCoolFunction(self, instance_id, payload: str) -> int:
    elasticapm.label(
        instance_id = instance_id,
        queue_name = self.request.delivery_info['routing_key'],
        job_id = self.request.id
    )

    ...
```
returning the following error:
```bash
[2021-09-16 09:40:07,162: WARNING/ForkPoolWorker-1] Ignored labels instance_id, queue_name, job_id. No transaction currently active.
```

As reported in the documentation [APM Overview [7.14] » Data Model » Metadata](https://www.elastic.co/guide/en/apm/get-started/current/metadata.html) it should apply at the same entities as `set_custom_context` API,  plus on Spans.

**Environment**
- OS: Ubuntu 20.10
- Python version: 3.8.10
- Framework and version: Celery 5.1.2
- APM Server version: 7.12.0
- Agent version: 6.4.0

**Comment by basepi** [comment]
I am extremely confused by this behavior. If you look at the two calls:

`elasticapm.label()`:

https://github.com/elastic/apm-agent-python/blob/8880393cb0105f8ab5519fd5e99d2c380c38e6d6/elasticapm/traces.py#L727-L728

`elasticapm.set_context()` (which is what `set_custom_context()` uses):

https://github.com/elastic/apm-agent-python/blob/8880393cb0105f8ab5519fd5e99d2c380c38e6d6/elasticapm/traces.py#L848-L849

you can see that they both get the `transaction` object in identical ways, and that the check for `label()` is actually *more* permissive because it doesn't care about sampling decisions. It feels like we're missing something from your examples. Maybe I'll have to try to find some time to reproduce this myself.

**Comment by zikphil** [comment]
If it can be a path for resolution, I haven't been able to use the official celery instrumentation for Standalone celery without django. The Client object is not thread-safe for SSL connections so I had to initiate the client in the task pre_run and set it in a context variable to be re-accessed in the other hooks.

Celery uses multi-threading, the jobs are never launched in the main thread where the Elastic APM Client is initiated.

**Comment by riccardomassullo** [comment]
@zikphil thanks for the info, however this doesn't explain the difference in behavior between `set_custom_context` and `label` API.
However, the auto instrumentation for celery seems to work good, until i found this `label` API problem with Celery 5.1.0.

**Comment by zikphil** [comment]
> @zikphil thanks for the info, however this doesn't explain the difference in behavior between `set_custom_context` and `label` API.
> However, the auto instrumentation for celery seems to work good, until i found this `label` API problem with Celery 5.1.0.
> Look at the following open issue, i commented how i achieved auto instrumentation for Celery [Issue 685](https://github.com/elastic/apm-agent-python/issues/685), official documentation about standalone celery auto instrumentation wasn't really clear.

Wow can't believe I missed ur Issue when I was researching this. Thank you so much :)

**Comment by beniwohli** [comment]
@riccardomassullo I've tried to reproduce this issue, but in my tests, both `label()` and `set_custom_context()` work within a celery task.

Is there something out of the ordinary with how you deploy celery? (different worker model than prefork, anything special you would do in `CustomBaseTaskClass` etc.)

**Comment by riccardomassullo** [comment]
@beniwohli I'm tried using a base Task class with the following results:

**Comment by riccardomassullo** [comment]
@beniwohli I tried using a base Task class with the following task definition:
```python
@app.task(bind=True)
def test(self, instance_id, payload: str) -> int:
    elasticapm.label(
      instance_id=instance_id
    )
    return 0
```

that's called via a fastapi restapi like the following one:
```python
@router.post('/queue-message', status_code=202)
async def queue_message(m: Message):
    task_name = 'sherpa.celery_worker.test'
    task = celery_app.send_task(task_name, args=[m.instance_id, m.payload], task_id=m.id, queue=m.queue_name)
    return {'task_id': task.id}
```
But i always obtain the usual error:
```
[2021-09-23 13:36:24,435: INFO/MainProcess] celery@5e6cab053fa1 ready.
[2021-09-23 13:36:33,059: INFO/MainProcess] Task sherpa.celery_worker.test[f3ec0997-9162-4782-b33a-1e5551f6bcbd] received
[2021-09-23 13:36:33,139: WARNING/ForkPoolWorker-1] Ignored labels instance_id. No transaction currently active.
```
Concurrency model is **Prefork**

**Comment by beniwohli** [comment]
@riccardomassullo so far, we've been unable to reproduce the issue. Would it be possible for you to create a minimal project that reproduces the issue?

**Comment by riccardomassullo** [comment]
> @riccardomassullo so far, we've been unable to reproduce the issue. Would it be possible for you to create a minimal project that reproduces the issue?

Hi, after various attempt, i rebuilt from scratch the base container where the Celery application was running and the problem disappeared and i wasn't able to reproduce that.
At this point is in production since about 3 weeks and no signs of the error so far.

Sorry for the late reply and thanks for the help. From my side you can close the issue.

**Comment by basepi** [comment]
Excellent! Thanks for the update.
