### ISSUE TITLE
gunicorn + flask,kibana  show no data

### ISSUE THREAD

**Issue by Crazycosin** [elastic/apm-agent-python#1331]
**Describe the bug**: ...

**To Reproduce**

1. ... gunicorn worker-class gevent
2. ...flask
3. ...elastic-apm 6.4.0
4. ...

**Environment (please complete the following information)**
- OS: [e.g. Linux]Linux
- Python version: 3.6.8
- Framework and version [e.g. Django 2.1]:
- APM Server version:7.3.1
- Agent version:

**Additional context**
my flask flask_extensions.py code:

```
from flask import Flask
from elasticapm.contrib.flask import ElasticAPM

from config import config


flask_app = Flask(__name__)
flask_app.config.from_object(config)
flask_app.config['ELASTIC_APM'] = {
        'SERVICE_NAME': 'flask',
        'SECRET_TOKEN': 'xxx',
        'SERVER_URL': 'http://localhost:8200',
    }

apm = ElasticAPM()
apm.init_app(flask_app)
```

app.py content.

```
from flask_extensions import flask_app


if __name__ == '__main__':
    flask_app.run(host='0.0.0.0', port=8000, debug=False)

```
example a:
     run shell `python app.py`, after that, kibana can show some data.

example b:
     run shell
 ```
gunicorn --access-logfile - --error-logfile - \
    --workers 32 \
    --timeout 300 \
    --threads 2  \
    --bind 0.0.0.0:8000 \
    --worker-class gevent \
    --worker-connections 2000 \
    app:flask_app \
    2>&1 | tee ./backend_log.log
```
 after that ,request the same url ,but can see nothing on kibana.
 i have tried change to pre_load = False or preload_app = False, but no effect.

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your agent config options
    remember to mask any sensitive fields like tokens
    ```
  </details>
- `requirements.txt`:
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your `requirements.txt`
    ```
  </details>

**Comment by Alsheh** [comment]
I'm hitting the same issue with `elastic-apm[flask]==6.4.0`  using docker base image `python:3.9-alpine`. Essentially, all I'm getting is `processor.event: metric` and any transaction I manually start and end. Flask transactions and spans are not showing in Kibana.

**Comment by basepi** [comment]
To clarify, does this issue go away if you use `elastic-apm[flask]<6.4.0` ?

**Comment by Crazycosin** [comment]
> To clarify, does this issue go away if you use `elastic-apm[flask]<6.4.0` ?

with elastic-apm[flask]==6.3.3 and elastic-apm[flask]==6.2.0, there still has been nothing on kibana.

**Comment by Alsheh** [comment]
None of the `6.*` versions seem to be working for me. I try to spin up an apm server locally and use the `console` output to diagnose the server output but I can only see the `processor.name: onboarding` log emitted by the apm server in my terminal.

As @Crazycosin mentioned, running the flask app directly in the shell sends the traces to the apm server but in my case nothing gets sent when running the app in a docker container with supervisor + nginx + uwsgi. My setup including `requirements.txt`, `apm-server.yml`, `docker-compose.yml`, etc are all available in [this repo](https://github.com/Alsheh/app).

**Comment by basepi** [comment]
OK, so this is not a regression, that's good to know. We'll take a look.

**Comment by beniwohli** [comment]
Hey all. I tried to figure out what's going on here over the last few days, but no matter what configuration I try, transactions are correctly recorded with Flask. I tried it both with gunicorn and uwsgi, as well as with gevent workers. I also tried with and without `--preload`.

The test application I used can be found at https://github.com/elastic/opbeans-flask. @Crazycosin @Alsheh do you see any glaring differences between your flask apps and this app?

**Comment by Alsheh** [comment]
@beniwohli for me, the uWsgi setting `enable-threads` was the culprit since, by default, uWSGI does not enable threading support which means the APM agent cannot create background threads. Enabling threading seems to fix the issue.

**Comment by beniwohli** [comment]
@Alsheh ah, good to know. We document this requirement (e.g. https://www.elastic.co/guide/en/apm/agent/python/current/flask-support.html#flask-installation), so I don't think there's much more we can do here.

**Comment by sundarv85** [comment]
@beniwohli I face a similar issue and I have created a new issue #2153
