### ISSUE TITLE
Django ASGI support

### ISSUE THREAD

**Issue by metalshanked** [elastic/apm-agent-python#1341]
Is Django Asgi supported unofficially or via any workarounds? 

I am running Elastic 7.13.4 , APM Server 7.13.4 , Django 3.2.7 on Uvicorn+Gunicorn with elastic-apm 6.4.0 and do not see any errors.
However, the apm-indices which are created by the APM server are not getting populated.

Any advise to make it work with Django Asgi?

**Comment by basepi** [comment]
I don't think we've done any testing with Django ASGI yet. Thanks for the request, I think we'll be able to get this prioritized.
