### ISSUE TITLE
Stop using undocumented get_raw_uri in DjangoClient

### ISSUE THREAD

**Issue by jaap3** [elastic/apm-agent-python#1342]
Django 4.0 removes the `request.get_raw_uri` method (without a deprecation period) because it is undocumented/private and considered unsafe (https://code.djangoproject.com/ticket/32698#comment:11).

This method is used here (guarded by a `hasattr(request, "get_raw_uri")` check):

https://github.com/elastic/apm-agent-python/blob/484ba5a1ad07e59bd4adeaf0291cc3da23d76afa/elasticapm/contrib/django/client.py#L155-L167

According to the ticket description (https://code.djangoproject.com/ticket/32698) "Niche use cases, such as APM packages [...], can read the internal attributes of HttpRequest instead.". I assume this means that e.g. the elastic-apm client can recreate the same behaviour by replicating the now removed `get_raw_uri` method.

Looking at the commit that removes this method (https://github.com/django/django/commit/8bcb00858e0ddec79cc96669c238d29c30d7effb) this would work:

```
url = '{scheme}://{host}{path}'.format(
    scheme=request.scheme,
    host=request._get_raw_host(),
    path=request.get_full_path(),
)
```

This means using a private/undocumented method (`request._get_raw_host`) but I see no other alternative.

**Comment by beniwohli** [comment]
@jaap3 thanks for the heads up! I opened #1343 to add Django 4.0 to our test matrix, and a test related to this does indeed fail. I agree that copying the now-removed implementation of `get_raw_uri()` seems like the most sensible way forward.

BTW, contrary to what is said in that Django ticket, we didn't stumble over `get_raw_uri()`, we've been [pointed towards it](https://code.djangoproject.com/ticket/27506#comment:3) by a Django core dev :grinning:

**Comment by jaap3** [comment]
I might be worthwhile pointing this out to the Django devs. I tried but they weren't very receptive. It's odd that the only way forward is again relying on a private API (at least this time it's clear that the API is private :)).
