### ISSUE TITLE
Problem validating JSON document against schema

### ISSUE THREAD

**Issue by gabriel-tincu** [elastic/apm-agent-python#135]
The apm server keeps dropping certain python agent requests with the following error:
```
2018-01-17T13:41:51.252+0100	ERROR	[request]	beater/handlers.go:384	error handling request	
{"request_id": "104c6f2b-8e7a-4480-aca7-cc292b890b4e", "error": "Problem validating JSON document against schema: I[#] S[#] doesn't validate with \"transaction#\"\n  I[#] S[#/required] missing properties: \"service\""}
```
Since it's a schema requirement error, and the schema definition [here](https://www.elastic.co/guide/en/apm/server/master/transaction-api.html#payload-with-transactions) specifies that the service field should be present , i thought this was the best place to post the issue

**Comment by beniwohli** [comment]
Hi Gabriel
Thanks for trying out Elastic APM!

Which version of the apm-server do you use? In the upcoming 6.2 release of the Elastic Stack, we changed the API quite significantly, so the elastic-apm agent from PyPI is not compatible with the apm-server 6.2

If you want to test our Python agent against the upcoming 6.2, you can use the `2.x` branch: https://github.com/elastic/apm-agent-python/tree/2.x. Note however that there might still be some changes between now and the official release of 6.2.

After the release of 6.2, we won't have any breaking changes for a while :)

**Comment by gabriel-tincu** [comment]
Hey, thanks for the reply. The agent was installed using pip and python3.6. The server was first downloaded from the main ES page [here](https://www.elastic.co/downloads/apm/apm-server), then build from source on the master branch, with the same results. The server download link specifies the version to be 6.1.X, so maybe the agent is a bit behind then....
I'll try to build that from source, thanks.

**Comment by beniwohli** [comment]
The version installable with `pip` should work with version 6.1 of the apm-server. Did you have issues with that combination?

Using apm-server from master is probably not going to be a great experience at the moment, as it isn't compatible with the dashboards and the X-Pack APM UI from Kibana 6.1.

**Comment by liza-mae** [comment]
Seeing same issue in 6.2 and 2.x branch.

**Comment by beniwohli** [comment]
I wasn't able to replicate this with the 2.x branch against apm-server 6.2 (pre-release). Closing. Feel free to re-open if you still encounter the problem.

@liza-mae if I remember correctly, your case turned out to be due to a setting rename?
