### ISSUE TITLE
install with --no-index does not work

### ISSUE THREAD

**Issue by mcosta74** [elastic/apm-agent-python#1375]
I need to install the package with --no-index after I downloaded all the packages

**To Reproduce**

1. setup a virtual environment
2. download wheel packages for setuptools, urllib3, certifi and elastic_apm
3. install them with
```
pip install --no-index setuptools-50.3.2-py3-none-any.whl certifi-2020.11.8-py2.py3-none-any.whl urllib3-1.26.2-py2.py3-none-any.whl
```
4. try to install elastic_apm with
```
pip install --no-index elastic-apm-6.6.0.tar.gz
```
I'm getting error 
```
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/massimoc/Projects/python/foo/.venv/bin/python3.9 /private/var/folders/2h/hz8sm1hn36lcmcmnpcpz98v80000gn/T/pip-standalone-pip-yb62v9ey/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/2h/hz8sm1hn36lcmcmnpcpz98v80000gn/T/pip-build-env-chofgdlh/overlay --no-warn-script-location --no-binary :none: --only-binary :none: --no-index -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (2 lines):
  ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
  ERROR: No matching distribution found for setuptools>=40.8.0
  ----------------------------------------
```

**Environment (please complete the following information)**
- OS: macOS
- Python version: 3.9
- Framework and version [e.g. Django 2.1]:
- APM Server version:
- Agent version:

**Additional context**

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your agent config options
    remember to mask any sensitive fields like tokens
    ```
  </details>
- `requirements.txt`:
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your `requirements.txt`
    ```
  </details>

**Comment by basepi** [comment]
This seems like a `pip` bug. You obviously installed `setuptools>=40.8.0` since you installed `setuptools-50.3.2-py3-none-any.whl` -- maybe you need to install them all in one command? I've never used `--no-index`.

**Comment by mcosta74** [comment]
hello, looks like I fixed installing `wheel` as well

**Comment by basepi** [comment]
Excellent. Thanks for the update!
