### ISSUE TITLE
aiohttp test failures

### ISSUE THREAD

**Issue by cachedout** [elastic/apm-agent-python#1391]
We have [started to see the following failures](https://apm-ci.elastic.co/job/apm-agent-python/job/apm-agent-python-nightly-mbp/job/master/775/) in the nightly tests:

    Test / Python-python-3.9-0 / tests.contrib.asyncio.aiohttp_web_tests.test_http_exception_below_500[pyloop]
    Test / Python-python-3.8-3 / tests.contrib.asyncio.aiohttp_web_tests.test_http_exception_below_500[pyloop]
    Test / Python-python-3.7-3 / tests.contrib.asyncio.aiohttp_web_tests.test_http_exception_below_500[pyloop]

An example stacktrace from a failed test looks like this:

```
aiohttp_client = <function aiohttp_client.<locals>.go at 0x7f7b81ad5280>
aioeapm = <elasticapm.contrib.aiohttp.ElasticAPM object at 0x7f7b81d79760>

    async def test_http_exception_below_500(aiohttp_client, aioeapm):
        app = aioeapm.app
        client = await aiohttp_client(app)
        elasticapm_client = aioeapm.client
        resp = await client.get("/raise/ok")
>       assert resp.status == 200
E       assert 500 == 200
E         +500
E         -200

tests/contrib/asyncio/aiohttp_web_tests.py:156: AssertionError
```

Possible culprit? https://github.com/elastic/apm-agent-python/pull/1384

**Comment by beniwohli** [comment]
It looks like these failures happen when testing against the unreleased [aiohttp 4.0](https://github.com/aio-libs/aiohttp/releases/tag/v4.0.0a1). The last alpha of 4.0 has been released over two years ago, while the latest 3.x release (3.8) happened just a few weeks ago. Without digging too much further, it looks like the 4.0 release train has been abandoned. I suggest we remove it from CI.

@basepi what do you think?

**Comment by basepi** [comment]
@beniwohli Seems reasonable to me.

**Comment by basepi** [comment]
I guess I'm mostly surprised that the tests passed on #1384. Was `aiohttp 4.0` pegged to only build on nightlies or something?

**Comment by beniwohli** [comment]
@basepi yes, the PRs only get a subset of all variants, as the full set would be too resource intensive
