### ISSUE TITLE
Include option of turning off compressed spans for python agent

### ISSUE THREAD

**Issue by m-standfuss** [elastic/apm-agent-python#1428]
**Is your feature request related to a problem? Please describe.**
We have endpoints that hit the database a lot, but with different queries. Previously before compressed spans went in we could see each of these queries in our trace breakdown. Now they are rolled up into a single "X Calls to postgres" which I can see being useful to some to avoid bloat in their span index but for us is near useless if we cant get the underlying queries being ran. Conversely if we had the option to add another layer to this logic 

```
Two spans are considered exact matches if the following attributes are identical:
 * span name
 * span type
 * span subtype
 * destination resource (e.g. the Database name)
```

for inclusion of the query being ran (ideally before parameters are applied to the query ie `SELECT name FROM person WHERE age > 18` and `SELECT name FROM person WHERE age > 21` could be considered the same would be awesome).  

**Describe the solution you'd like**
Either a flag to not compress spans (if it already exists I couldn't find it in documentation), or additional logic to include thequery as part of the attribute consideration. 

**Describe alternatives you've considered**
None I suppose, tried to figure out what was happening and had to dig through release notes to find the addition to the python agent. 

**Additional context**
It would be nice if new features like this came out with a feature flag that defaulted to current behavior rather then having to dig around for why our spans now look differently.

**Comment by m-standfuss** [comment]
It looks like in our case these queries are different meaning their `name` doesnt match but its still grouped together due to this [1] configuration. Would setting this to 0 make it to where spans that are same-kind are never grouped together? Shouldnt this be the default and this functionality be opt-in instead for consumers? 

[1] https://www.elastic.co/guide/en/apm/agent/python/master/configuration.html#config-span-compression-same-kind-max-duration

**Comment by m-standfuss** [comment]
Also it looks like this configuration is in the overall agent spec but not implemented for python. Was this feature not fully fleshed out before going out or whats going on? 

https://github.com/elastic/apm/blob/master/specs/agents/handling-huge-traces/tracing-spans-compress.md#configuration-option-span_compression_enabled

**Comment by basepi** [comment]
Good catch, it looks like we forgot to implement that `span_compression_enabled` setting.

In the meantime, if you set both `span_compression_exact_match_duration` and `span_compression_same_kind_max_duration` to `0ms` I think it will effectively disable span compression.

**Comment by m-standfuss** [comment]
Thanks for the confirmation! good to close this ticket, will this be added into a future release?

**Comment by beniwohli** [comment]
@m-standfuss I'll probably create a hotfix release some time this week. Sorry about the troubles!

**Comment by m-standfuss** [comment]
Thanks @beniwohli!!

**Comment by m-standfuss** [comment]
@beniwohli still planning on hotfixing this into a release?

**Comment by beniwohli** [comment]
@m-standfuss this was part of the 6.7.2 release about a month ago
