### ISSUE TITLE
[ci] tests.config.tests.test_config_all_upper_case failing

### ISSUE THREAD

**Issue by cachedout** [elastic/apm-agent-python#1435]
It appears that the `tests.config.tests.test_config_all_upper_case` test is failing [across a number of different platforms on the master branch](https://apm-ci.elastic.co/job/apm-agent-python/job/apm-agent-python-mbp/job/master/593/testReport/):
<img width="684" alt="Screen Shot 2021-12-16 at 9 04 34 AM" src="https://user-images.githubusercontent.com/111616/146331918-5ee9fa87-156b-42b1-8dc5-53ceea0d6df1.png">

**Comment by beniwohli** [comment]
@cachedout I'm aware, I just didn't get around to fix it yet. It's an easy fix, I'll open a PR
