### ISSUE TITLE
Dropped spans that match configuration

### ISSUE THREAD

**Issue by ToGoBananas** [elastic/apm-agent-python#1476]
**Describe the bug**: ...

**To Reproduce**

1. Switch from 6.7.2 to 6.8.0
2. Try to capture some async span with discardable property and EXIT_SPAN_MIN_DURATION != -1
3. any span goes to discarded

**Environment (please complete the following information)**
- APM Server version: 8.0.1
- Agent version: 6.8.0

The root of issue in 
```
    def report(self) -> None:
        if self.discardable and self.duration < self.transaction.config_exit_span_min_duration:
            self.transaction.track_dropped_span(self)
            self.transaction.dropped_spans += 1
        else:
            self.tracer.queue_func(SPAN, self.to_dict())
```

For span with duration 1ms
self.duration would be 0.01
self.transaction.config_exit_span_min_duration (default value 1ms) equals 1
So...

**Comment by basepi** [comment]
I'm fixing this in #1483. Apologies for the regression.
