### ISSUE TITLE
APM agent crashes if the request body is too large

### ISSUE THREAD

**Issue by Ofekroz10** [elastic/apm-agent-python#1478]
**Describe the bug**: ...
When the request body is too large, reporting to the apm server fails. 
The error message is: 
```
eapm event processor thread elasticapm.transport:286 - Failed to submit message: 'HTTP 400: {"accepted":4,"errors":[{"message":"event exceeded the permitted size." ...
```

**To Reproduce**

1. Check the body's size before reporting. If it's too large, report the body as `[Too large]` or something like that.

**Environment (please complete the following information)**
- OS: mac
- Python version: 3.7
- Framework and version [e.g. Django 2.1]: django==2.2.26
- APM Server version: ?
- Agent version: 5.10.1

Elastic apm configuration (in `settings.py`): 
```
ELASTIC_APM = {
	...
    "CAPTURE_BODY": "all",
}
```

**Additional context**

The issue is that Django client extracts the request body [without checking the size of the body](https://github.com/elastic/apm-agent-python/blob/main/elasticapm/contrib/django/client.py#L151-L152). I believe that adding a size check in [this](https://github.com/elastic/apm-agent-python/blob/97188c362497910762e5b1ef8fc53e4011ec75b8/elasticapm/contrib/django/client.py#L117) function should solve the issue.

**Comment by basepi** [comment]
Fix open in #1610
