### ISSUE TITLE
Span not being dropped (Python + Sanic)

### ISSUE THREAD

**Issue by julianogv** [elastic/apm-agent-python#1481]
**Describe the bug**
I'm trying to optimize my ElasticAPM to reduce the amount of storage it's currently using on my ES Cluster and after some research I figured out that APM is not dropping spans with a duration lower than the defined ELASTIC_APM_EXIT_SPAN_MIN_DURATION (20ms).
After running the query below I can see some indexed items with a span info with the duration of 105us (which is lower than 20ms and should be dropped).
Is that a bug or am I missing some config to prevent these spans to not being logged?

<details>
<summary>ES search</summary>

```
GET .ds-traces-apm-default-2022.*/_search
{
  "size": 10,
  "query": {
    "match_all": {}
  },
  "sort": [
    {
      "@timestamp": {
        "order": "desc"
      }
    }
  ]
}

```
</details>

<details>
<summary>Indexed span information</summary>

```
"span" : {
    "duration" : {
      "us" : 105
    },
    "subtype" : "redis",
    "destination" : {
      "service" : {
        "resource" : "redis"
      }
    },
    "name" : "MGET",
    "action" : "query",
    "id" : "xyz",
    "type" : "db"
  }
```

</details>

**To Reproduce**
1. Using a python 3.7 / sanic 19.3.1 / elastic-apm 6.7.2
2. Configuring the ELASTIC_APM_EXIT_SPAN_MIN_DURATION to "20ms"
3. Span are being sent to the elasticsearch index instead of being dropped

**Expected behavior**
APM should drop span info with a duration lower than ELASTIC_APM_EXIT_SPAN_MIN_DURATION

**All my APM environment variables**
ELASTIC_APM_METRICS_INTERVAL = "0s"
ELASTIC_APM_TRANSACTION_SAMPLE_RATE = "0.1"
ELASTIC_APM_EXIT_SPAN_MIN_DURATION = "20ms"
ELASTIC_APM_SPAN_FRAMES_MIN_DURATION = "100ms"
ELASTIC_APM_CAPTURE_BODY = "off"
ELASTIC_APM_CAPTURE_HEADERS = "false"

**Comment by basepi** [comment]
ELASTIC_APM_EXIT_SPAN_MIN_DURATION is new in 6.8.0. However, there's a bug (fixed in #1483) so you should wait for 6.8.1.
