### ISSUE TITLE
HTTP 400: Problem validating JSON document against schema: unexpected EOF

### ISSUE THREAD

**Issue by lechup** [elastic/apm-agent-python#150]
I'm having troubles with submitting transactions that have more than 900KB:

```
INFO 2018-02-05 10:45:01,326 /var/virtualenv/lib/python3.5/site-packages/elasticapm/transport/http.py 54 12002 140542526174976 Sent request, url=XXX/v1/transactions size=957.61kb status=400
ERROR 2018-02-05 10:45:04,590 /var/virtualenv/lib/python3.5/site-packages/elasticapm/base.py 256 11718 140542526174976 HTTP 400: Problem validating JSON document against schema$
ERROR 2018-02-05 10:45:05,075 /var/virtualenv/lib/python3.5/site-packages/elasticapm/base.py 263 11718 140542526174976 Failed to submit message: '<no message value>'
Traceback (most recent call last):
  File "/var/virtualenv/lib/python3.5/site-packages/elasticapm/transport/http_base.py", line 45, in send_sync
    url = self.sync_transport.send(self, data, headers)
  File "/var/virtualenv/lib/python3.5/site-packages/elasticapm/transport/http.py", line 77, in send
    raise TransportException(message, data, print_trace=print_trace)
elasticapm.transport.base.TransportException: HTTP 400: Problem validating JSON document against schema: unexpected EOF
```

Agent config:

```
{'APP_NAME': 'XXX',
 'MAX_EVENT_QUEUE_LENGTH': 150,
 'SERVER_URL': 'XXX',
 'TIMEOUT': 10,
 'TRACES_SEND_FREQ': 15}
```

apm-server config:

```
apm-server:
  host: '0.0.0.0:8200'
  max_unzipped_size: 52428800
  read_timeout: '15s'
  write_timeout: '15s'
  shutdown_timeout: '10s'
  concurrent_requests: 20
queue:
  mem:
    events: 16384
    flush.min_events: 512
```

I've found similar problem here:
https://github.com/elastic/apm-agent-nodejs/issues/141

AFAIK my settings are ok, but issue is still showing up...

PS: Thanks for sharing great piece of software!

**Comment by beniwohli** [comment]
Hi @lechup, thanks for trying out Elastic APM!

I think you are correct in assuming this is similar to elastic/apm-agent-nodejs#141. In the upcoming version 6.2 of apm-server, there will be a nicer error message for this case. We also tried to reduce the amount of data we send up with each transaction.

In the mean time, I suggest to either increase the `max_unzipped_size` further, or reducing `MAX_EVENT_QUEUE_LENGTH`.

**Comment by lechup** [comment]
Hm... I've changed in apm-server.yml:

```
max_unzipped_size: 104857600
```

That is 100mb (was 50mb).

and in agent config:

```
MAX_EVENT_QUEUE_LENGTH: 100
```

And for now problem is gone - all transactions sent are below 200kb now.

I don't know internals but still I don't know why exactly this one helped to reduce transaction size more than 4 times, and still 1mb even after unzipping should never exceed previous limit of 50mb...

For now I'm closing this issue @beniwohli thanks for help!
