### ISSUE TITLE
Bug: [Django] TypeError: get_username() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by imshashank** [elastic/apm-agent-python#1514]
**Describe the bug**: ...

I am seeing the below error on almost every Django call when there is some other exception:

```
Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/elasticapm/contrib/django/middleware/__init__.py", line 182, in process_response
    elasticapm.set_context(lambda: self.client.get_user_info(request), "user")
  File "/venv/lib/python3.8/site-packages/elasticapm/traces.py", line 1090, in set_context
    data = data()
  File "/venv/lib/python3.8/site-packages/elasticapm/contrib/django/middleware/__init__.py", line 182, in <lambda>
    elasticapm.set_context(lambda: self.client.get_user_info(request), "user")
  File "/venv/lib/python3.8/site-packages/elasticapm/contrib/django/client.py", line 105, in get_user_info
    user_info["username"] = encoding.keyword_field(encoding.force_text(user.get_username()))
TypeError: get_username() missing 1 required positional argument: 'self'
```

**To Reproduce**

1. Add elasticapm to Django as INSTALLED_APPS
2. Get an exception and this error will be creates

This is quite a strange error and we are not able to debug this ourselves. 

**Environment (please complete the following information)**
- OS: [e.g. Linux] Linux
- Python version:  CPython Version 3.8.13
- Framework and version [e.g. Django 2.1]: Django 3.0.7
- APM Server version: 6.8.1
- Agent version:

Elasticapm Trace ID | 3c9c89bfa0891b94433e78f54114215d
elasticapm_transaction_id | 0d649f9faa87735e

```
{
service.name: api-django, 
span.id: None, 
trace.id: 3c9c89bfa0891b94433e78f54114215d, 
transaction.id: 0d649f9faa87735e
}
```

**Comment by basepi** [comment]
After talking this over with @beniwohli, I don't think we're going to "fix" this after all. We think this is a bug in the `frontegg` user authentication. According to both Django's docs and its source code, `request.user` is supposed to be an instance of a `User` object. Obviously their `User` object is not quite complying with the norms and so is causing this issue. Working around what seems to us to be a bug seems like a bad idea, as we could hide legitimate bugs in the future (and it junks up the code).

Can you please open a support ticket with `frontegg` and see if they can track down this issue or have any insight?
