### ISSUE TITLE
Data doesn't arrive in the elastic cloud panel

### ISSUE THREAD

**Issue by mjr** [elastic/apm-agent-python#1547]
I'm getting these errors:

```
No version key found in server response: b'{"ok":false,"message":"Unknown resource."}\n'
```

```
dropping flushed data due to transport failure back-off
```

```
TransportException
HTTP 404: {"ok":false,"message":"Unknown resource."}
```

**Environment**
- OS: Linux
- Python version: 3.10.4
- Framework and version: Django 4.0.4 
- APM Server version: 7+
- Agent version: elastic-apm 6.9.1

**My config**

```python
INSTALLED_APPS = [
    # ...
    'elasticapm.contrib.django',
]

ELASTIC_APM = {
    'SERVICE_NAME': 'testelasticapm',
    'SECRET_TOKEN': 'DYVuJGfJTX8brbTKaY',
    'SERVER_URL': 'https://28b44e7b03744591a63f086fe3058600.apm.us-east-1.aws.cloud.es.io:443',
    'ENVIRONMENT': 'production',
}

MIDDLEWARE = [
    'elasticapm.contrib.django.middleware.TracingMiddleware',
    # ...
]
```

**Comment by basepi** [comment]
Is there anything interesting in your network setup? Sending through a proxy or anything? It's very odd that the APM Server would be returning a 404. Even if it were an authentication issue it should be a 5xx response I'm pretty sure....

**Comment by mjr** [comment]
@basepi I understand the problem, but it's something strange, the problem was because I had an old configuration in the environment variables and that was overwriting the hard code configuration in settings.py.
Thank's for your time.
