### ISSUE TITLE
Problem validating JSON document against schema - length must be <= 1024, but got 1523

### ISSUE THREAD

**Issue by SuryaSankar** [elastic/apm-agent-python#156]
Continuously seeing these errors in the log -

2018-02-13T05:06:49.104Z	ERROR	[request]	beater/handlers.go:384	error handling request	{"request_id": "79f54c15-f99e-4d1d-ab14-07bf622983c8", "error": "Problem validating JSON document against schema: I[#] S[#] doesn't validate with \"transaction#\"\n  I[#/transactions/29/context/request/url/full] S[#/properties/transactions/items/properties/context/properties/request/properties/url/properties/full/maxLength] length must be <= 1024, but got 1523"}

apm-server version is 6.2.1
elastic-apm agent version 2.0.0 with Flask.

Is there any config property that I need to change to let the apm server accept urls of a longer length?

**Comment by beniwohli** [comment]
Thanks for trying out Elastic APM @SuryaSankar. The 1024 limit is currently hard-coded in the APM Server and can't be changed. The bug here is that the Python agent doesn't truncate it before sending it up. I will open a PR that does this ASAP.

Just out of interest, can you tell us a bit about your URLs? We assumed that 1024 characters should be enough for most use cases 😊

**Comment by SuryaSankar** [comment]
Thanks for the quick reply @beniwohli and thanks for open sourcing such an useful tool. 

The logs are not showing which particular url is throwing the error. But I can guess what might be the issue.
Our API query language is designed to accept a desired output data structure as a part of the query argument. So the client can request something like

`GET /api/resources/(resource_id)?_ds={"attrs":["foo","bar"],"rels":{"rel1":{"attrs":["foo1", "bar1"]}}}`

This data structure can be nested to any level to let the client query any number of related resources to any depth. So in some cases it might be possible that the url is exceeding 1024 chars if the client is asking for a particularly detailed data structure. 

Until this fix is done, is there any way I can turn off the errors? These errors are flooding my main web server logs and making it exceed the associated Sentry account's quota.  

I've tried setting logging=False when initializing APM. But that is not having any effect

`elastic_apm.init_app(app, logging=False)`

**Comment by beniwohli** [comment]
We use the logger name `elasticapm.errors` for these messages, so you could set up your logging config to not forward messages from this logger to Sentry for now. We have some information on this in our [Django docs](https://www.elastic.co/guide/en/apm/agent/python/2.x/django-support.html#django-logging) (last item in the `loggers` dict), it should be more or less the same with [Flask and `dictConfig`](http://flask.pocoo.org/docs/dev/logging/#basic-configuration).

**Comment by beniwohli** [comment]
@SuryaSankar I've just uploaded v2.0.1 of the agent to pypi, which includes truncating for the request.url and a bunch of other fields. Can you check if this solves your problem?
