### ISSUE TITLE
AWS lambda: capture_serverless does not provide information when lambda is connected to ELB (not to API GW)

### ISSUE THREAD

**Issue by tonyman19** [elastic/apm-agent-python#1587]
Event that lambda handler receiving in case of attachment through the ELB you can find in attachment: [elb-lambda-event.txt](https://github.com/elastic/apm-agent-python/files/9103558/elb-lambda-event.txt)

Please note that queryStringParameters are quoted (in the event which is coming from API gateway they are not).
Note that in this case requestContext contains only elb element and nothing else.

**Is your feature request related to a problem? Please describe.**
Recently AWS has introduced that lambda could be joined directly to ELB (without API gateway) and when transaction is getting recorded by capture_serverless then it has much less information comparing to the API gateway connected one.

This function should be rewritten to react accordingly. For the lambdas which are ELB api invocations - the " elasticapm.set_context(lambda: get_data_from_request( is not getting invoked.

    def __enter__(self):

..... 

 self.httpmethod = nested_key(self.event, "requestContext", "httpMethod") or nested_key(
            self.event, "requestContext", "http", "method"
        )
....

if self.httpmethod:  # API Gateway
    self.source = "api"

.....

.....
       if self.source == "api":
            elasticapm.set_context(
                lambda: get_data_from_request(

**Comment by tonyman19** [comment]
@basepi Could you take a look please :)

**Comment by basepi** [comment]
Thanks for providing a sample event! We can definitely get it updated to deal with these differences from API Gateway.

**Comment by tonyman19** [comment]
@basepi Dear Colton, I've provided the PR for this issue along with other fix. Could you, please, take a look?
https://github.com/elastic/apm-agent-python/pull/1605

I signed the INDIVIDUAL CONTRIBUTOR LICENSE Agreement again.
How to re-trigger the build? Where to upload the signed license?

Thank you for your support!

**Comment by basepi** [comment]
Theoretically the CLA checker will update now that I triggered the tests. It can be a bit finnicky. You shouldn't have to upload your signed document anywhere as long as you signed it through [here](https://www.elastic.co/contributor-agreement).

**Comment by tonyman19** [comment]
Hi Colton,

Thank you for review and quick reply. Finalized signing for anton.matviyenko@gmail.com
What about recorded commits - is it possible to change from anton@mycarly.com to the abovementioned email?
Or is it ok the way they are ATM?

**Comment by tonyman19** [comment]
@basepi Short question about following inconsistency that I have found. Is it by purpose or just a mistake?

if self.source == "api":
....
     cloud_context["origin"]["account"] = {"id": self.event["requestContext"]["accountId"]}
elif self.source == "sns":
.....
     cloud_context["origin"]["account_id"] = record["Sns"]["TopicArn"].split(":")[4]

So first time (and everywhere else) we are creating subobject with id field ["origin"]["account"]["id"]  - next time we create subelement account_id which is located under ["origin"]["account_id"].

Should we also fix that here?
