### ISSUE TITLE
Python Agent cannot establish distributed tracing with web applications using JS Agent (RUM)?

### ISSUE THREAD

**Issue by LHB6540** [elastic/apm-agent-python#1588]
**Describe the bug**: ...
Ideally, a JS Agent is added to A-front, a web front-end application, and a Python Agent is added to A-Flask, a web back-end application requested by A-front. In the transactions view of the A-front of Kibana's APM, the timeline should show the two traces together. But in fact, the timeline only shows the span of an http request, not the trace of A-Flask.
![image](https://user-images.githubusercontent.com/41095303/178965723-a2bc9f5d-3766-4f70-a590-e81d45977d5d.png)
![20220714185003](https://user-images.githubusercontent.com/41095303/178966132-e68bd9a5-73ba-4c1f-bf19-b4c5109e5c86.jpg)

For testing, I replaced A-Flask with a program written in Golang and introduced Golang Agent. At this time, in the transactions view of A-front of Kibana's APM, you can see that the transactions of the two services are displayed together
![image](https://user-images.githubusercontent.com/41095303/178965437-8da05d17-32c1-47c1-b69b-1c36612c7e82.png)
Does the Python Agent not capture the transaction.id of the Context in the Http Request and use it as the parent id of the span? Or in other words, does the Python Agent support distributed tracing?

**To Reproduce**
as above

**Environment (please complete the following information)**
- OS: Centos 7
- Python version: 3.6.8
- Framework and version [e.g. Django 2.1]: Flask 2.0.1
- APM Server version: ES cloud 8.2.3
- Agent version: 6.10.1

**Comment by basepi** [comment]
The Python agent definitely supports distributed tracing.

We fetch the parent ID from the incoming headers [here](https://github.com/elastic/apm-agent-python/blob/be6f4edd2c0ff11f565de759fa80e5b320039683/elasticapm/contrib/flask/__init__.py#L178)

Can you check that either the `traceparent` or `elastic-apm-traceparent` header are present in the request to Flask?

**Comment by LHB6540** [comment]
> The Python agent definitely supports distributed tracing.
> 
> We fetch the parent ID from the incoming headers [here](https://github.com/elastic/apm-agent-python/blob/be6f4edd2c0ff11f565de759fa80e5b320039683/elasticapm/contrib/flask/__init__.py#L178)
> 
> Can you check that either the `traceparent` or `elastic-apm-traceparent` header are present in the request to Flask?

Thanks for your answer. I tried to print the header of the first request, but I didn't find transcation.id. I realized that the problem is with the use of JS Agent, I will check the JS Agent further. Thanks again
