### ISSUE TITLE
Performance Bug in the varmap function

### ISSUE THREAD

**Issue by kohlmanj-hs** [elastic/apm-agent-python#1592]
**Describe the bug**: ...
When python code throws an error, and one of the local variables contains a very large list of lists of lists, it takes the elastic python apm client a very long time to process through the list. In our case it was taking over 60 seconds for the code to complete.

**To Reproduce**
To simply replicate the issue, I: (see code snipit  in the elastic forum, link below)

- created a simple script to create a list of list of lists of integers.
- in one method I had my "with elasticAPMTransaction:" statement.
- under this I created the list (200 integers) of list (300 integers) of list (40 integers) aka 24M items total.
- started to iterate through the outer list and picked an arbitrary spot to through an exception. This essentially mimicked the method where the real code threw an exception.
- wrapped this whole thing in a profiler and evaluated the output.
This would take 60 seconds +/- to complete.

Seems like the issue is in the varmap function in elasticapm\utils_init_.py but there maybe lots of ways to solve this issue.

**Environment (please complete the following information)**
- OS: [e.g. Linux]
- Python version: 3.x
- Framework and version [e.g. Django 2.1]:
- APM Server version: N/A
- Agent version: 6.7.2

**Additional context**
Created a case here https://discuss.elastic.co/t/python-client-apm-very-slow-when-local-list-variable-is-very-large/309935. See this for additional details.

**Comment by basepi** [comment]
This is fixed in #1593 -- can you test for me?

**Comment by kohlmanj-hs** [comment]
Colton,

First off thanks for taking care of this so quickly!!!

The fix looks good. Time went from +/- 60 seconds to +/- 15 seconds for a list of list of lists with a total of 24M items. 

For completeness, I modified my script to use dicts with more or less the same shape instead of lists.  A dict of dict of dict, where the key was an int and the values were "some text {}".format(key). The results after your fix took +/- 22 seconds. 

I also tried with making the keys "some key {}".format(key) and with your fix this took 20 seconds. 

I suspect the extra 2 seconds when the key is an int is due to the fact it has to convert the key to a string? I didn't actually look through the code, it is just a guess.

May I suggest a slight refactoring. You always call "ret = func(name, var, **kwargs)" first. So we can pull it out before the "if" statement, remove it from "if" and "elif" and remove the else statement entirely. See below.

`def varmap(func, var, context=None, name=None, **kwargs):
    """
    Executes ``func(key_name, value)`` on all values,
    recursively discovering dict and list scoped
    values.
    """
    if context is None:
        context = set()
    objid = id(var)
    if objid in context:
        return func(name, "<...>", **kwargs)
    context.add(objid)

    # Apply func() before recursion, so that `shorten()` doesn't have to iterate over all the trimmed values
    ret = func(name, var, **kwargs)
    
    if isinstance(var, dict):
        # iterate over a copy of the dictionary to avoid "dictionary changed size during iteration" issues
        ret = dict((k, varmap(func, v, context, k, **kwargs)) for k, v in ret.copy().items())
    elif isinstance(var, (list, tuple)):
        ret = [varmap(func, f, context, name, **kwargs) for f in ret]

    context.remove(objid)
    return ret`

For further completeness I retested both dicts and lists. Not surprisingly, the timings were exactly the same as with your original fix.

Thanks again for this!!

Best,
Kohlman

**Comment by basepi** [comment]
I forgot to check back in on this issue before I merged the PR! Your refactor is excellent, I'll submit another PR with that shortly.

**Comment by kohlmanj-hs** [comment]
What can I say, you helped us out . . . so I wanted to return the favor!!

:-)
