### ISSUE TITLE
Investigate options to support async (Twisted)

### ISSUE THREAD

**Issue by beniwohli** [elastic/apm-agent-python#16]
We currently don't support any asynchronous Python frameworks like Twisted, Tornado & Co. Supporting these frameworks is inherently difficult due to the fact that we made a lot of design decisions on the assumption that a thread only handles a single request at a time. This is not true for async frameworks.

There are some ways we could achieve at least some support for Twisted by storing data of the current transaction on the request handler instead of a thread local. Similar workarounds may or may not exist for other async frameworks.

In the future, we may be able to use execution contexts as proposed by [PEP 550](https://www.python.org/dev/peps/pep-0550/), but this will take some time until it is available.

**Comment by beniwohli** [comment]
For Tornado, we could potentially piggyback on `StackContext` using something like https://gist.github.com/virtuald/50bf7cacdc8cfb05e323f350539f0efa

I haven't found something similar for Twisted. There is some discussion around context tracking [here](http://twistedmatrix.com/pipermail/twisted-python/2011-March/023679.html), but the general advice there seems to be against trying to use [`twisted.python.context.ContextTracker`](https://twistedmatrix.com/documents/16.2.0/api/twisted.python.context.ContextTracker.html) to track asynchronous context.

**Comment by beniwohli** [comment]
There's some more development in this space:

 * [PEP 567 - Context Variables](https://www.python.org/dev/peps/pep-0567/) has been accepted/merged and will be available in Python 3.7
 * There is a [backport](https://github.com/MagicStack/pep567) of PEP 567 to Python 3.6 (albeit without an asyncio event loop)
 * As pointed out by @watson, there is a 3rd party library called [AioContext](https://github.com/sqreen/AioContext) that might be helpful.

All of these are built around asyncio though, so I'm not sure of how much benefit either one would be in conjunction with Twisted and Tornado (both of which use their own event loop implementation)

**Comment by beniwohli** [comment]
See #252 for a very WIPy implementation of asyncio support

**Comment by chris-erickson** [comment]
The asgi apps are starting to gain traction, and are a compelling alternative to Go, Node, etc for better concurrency in heavy IO blocking apps.  APM support is a sticking point for me in building apps this way (Starlette in particular) and I’d love to see support in this area, or even recommendations on how to get partial support of some kind (ie. request timing) working.  Thanks!

**Comment by bhodorog** [comment]
Another asynchronous framework quite used by python projects is [gevent](http://www.gevent.org/). Needless to say currently that's not supported and the first significant effect is that transactions are not being supported. 

While I appreciate the initial design decision which were mentioned by the OP in the first post would you guys consider supporting something like gevent ? I'm thinking you might be able to use [`werkzeug.local`](http://werkzeug.pocoo.org/docs/0.14/local/) to achieve the same effect as `contextvar` does for native threads and asyncio.

**Comment by basepi** [comment]
We have support for tornado, starlette/fastapi and various async libraries as well. If there's continued interest in gevent, twisted, or others, we request that separate issues be made.
