### ISSUE TITLE
Problem validating JSON - I[#/service/name] S[#/properties/service/properties/name/type] expected string, but got null

### ISSUE THREAD

**Issue by nemd** [elastic/apm-agent-python#161]
Hi there,

  Right after update apm-server from 6.1.2 to 6.2.0 I've started to get these:

HTTP 400: Problem validating JSON document against schema: I[#] S[#] doesn't validate with "transaction#"
   I[#/service/name] S[#/properties/service/properties/name/type] expected string, but got null
 Failed to submit message: '<no message value>'
 Traceback (most recent call last):
   File "/usr/lib/python2.7/site-packages/elasticapm/transport/http_base.py", line 45, in send_sync
     url = self.sync_transport.send(self, data, headers)
   File "/usr/lib/python2.7/site-packages/elasticapm/transport/http.py", line 77, in send
     raise TransportException(message, data, print_trace=print_trace)
 TransportException: HTTP 400: Problem validating JSON document against schema: I[#] S[#] doesn't validate with "transaction#"
   I[#/service/name] S[#/properties/service/properties/name/type] expected string, but got null

apm-server: 6.2.0 (docker)
apm-agent: 2.0.0 (django with uwsgi)
elasticsearch: 6.2.1 (elastic cloud)

**Comment by beniwohli** [comment]
Hi @nemd, thanks for trying out Elastic APM! Unfortunately, we had to introduce a few breaking changes between 6.1 Beta and 6.2, which also affect the agents. If you haven't yet, can you

 * update your agent to 2.0
 * rename the `APP_NAME` setting to `SERVICE_NAME`

A full list of breaking changes is in the [changelog](https://github.com/elastic/apm-agent-python/blob/master/CHANGELOG.asciidoc#v200).

**Comment by nemd** [comment]
thanks @beniwohli what helped was changing APP_NAME to SERVICE_NAME.

**Comment by lechup** [comment]
@beniwohli maybe You can somewhere link those changes in docs? It took me some time to actually find it out myself (from other older issue found by Google)...

Google haven't indexed this topic yet and by default Github hide closed issues so maybe even opening the issue would be the best option + changing the name by prepending [update to 6.1 -> 6.2] or something similar?

Anyway errors are gone. Thanks! :+1:
