### ISSUE TITLE
APM Transactions not sampled when sample rate is 1

### ISSUE THREAD

**Issue by Alsheh** [elastic/apm-agent-python#1624]
**Describe the bug**:
We have micro services using Flask as framework and ElasticAPM for tracing requests. We noticed ~10% of transactions are not sampled despite not changing the default sample rate (1) for any of the services. Services send traces to APM servers running two different versions (`7.14.1` and `7.16.1`). With APM server `7.14.1`, upsampled transactions have `transaction.sampled` set to `false`.

**Environment**
- Python version: `3.6`, `3.7`
- Framework and version: `Flask 1.0.2, 1.1.2,  2.0.2, 2.1.1`
- APM Server version: `7.14.1`, `7.16.1`
- Agent version: `5.10.1`, `6.7.2`

**Additional context**
The screenshot below shows upsampled transactions associated with one HTTP request:
* `transaction.sampled=false`
* `transaction.span_count.started=0`
![Screen Shot 2022-08-31 at 7 59 17 PM](https://user-images.githubusercontent.com/16920445/187738226-2df19df8-2137-4e2a-a59b-e100e8489621.png)

**Comment by basepi** [comment]
Do you have any upstream services calling your python service? If the incoming headers have our `traceparent`, it includes the sampling decision made in the upstream service. We do not make our own sampling decision in this case.

You can check the `http.request.headers` on those unsampled transactions to see if they had an incoming `traceparent` header.

**Comment by Alsheh** [comment]
@basepi  Indeed, one of our clients is passing the `traceparent` header which is messing with our APM sampling. How can we ensure our sampling decision does not get impacted by external clients?

**Comment by basepi** [comment]
You'll want [`trace_continuation_strategy=restart` or `trace_continuation_strategy=restart_external`](https://www.elastic.co/guide/en/apm/agent/python/current/configuration.html#config-trace-continuation-strategy), depending on whether the upstream service is Elastic-monitored. (You can tell if it's an Elastic traceparent by checking the `tracestate` header for an `es=` entry.)

Note, however, that this setting was only introduced in version [6.10.0](https://github.com/elastic/apm-agent-python/releases/tag/v6.10.0) of the agent, and the versions you listed above are older than that.

**Comment by Alsheh** [comment]
Thanks for the quick response, @basepi ! Will test setting `ELASTIC_APM_TRACE_CONTINUATION_STRATEGY=restart` and get back to you.

**Comment by Alsheh** [comment]
@basepi  using [trace_continuation_strategy=restart](https://www.elastic.co/guide/en/apm/agent/python/current/configuration.html#config-trace-continuation-strategy) eliminated the majority of upsampled transactions but we're still seeing few upsampled transactions when clients send a `traceparent` header but the `tracestate` header is empty:

```
  "headers": {
     ...
    "traceparent": "00-ac76a4e4e9af04b7ed1507b4fb417683-65e34fff5ebb080e-00",
    "tracestate": ""
   }
```

**Comment by basepi** [comment]
@Alsheh You're certain that those traces are on a service with `transaction_sample_rate=1.0`, and `elasticapm>=6.10.0` ?

I thought maybe we had a bug here, but we don't even look at the tracestate if `trace_continuation_strategy=restart`:

https://github.com/elastic/apm-agent-python/blob/45abe9734dd25acdc21633cdc58ab80304506d8a/elasticapm/traces.py#L943-L949

I can't see any problem in the code...

**Comment by Alsheh** [comment]
@basepi yes the service is using `elastic-apm==6.10.0`, `transaction_sample_rate=1.0`, and `trace_continuation_strategy=restart` but few transactions are still not sampled. However, I found other upsampled transactions where `tracestate` is set:

```
        "headers": {
          "tracestate": "1482302@nr=0-0-1482302-27961896-fdaad9b2cf8c0e4e-9585f7e4ff9c959f-0-0.159652-1662495712768",
          "traceparent": "00-0079207792d62ec2345d651e22fa53ae-fdaad9b2cf8c0e4e-00"
          ...
        }
```

**Comment by Alsheh** [comment]
actually, I just noticed one stale container didn't pick up the new update (`trace_continuation_strategy=restart`). I removed the stale container and will monitor.

**Comment by Alsheh** [comment]
Updating the service with `trace_continuation_strategy=restart` and ensuring the deployment is up to date fixes the issue. Thank you @basepi for your help in resolving this issue.
