### ISSUE TITLE
python3.11 support

### ISSUE THREAD

**Issue by tanagumo** [elastic/apm-agent-python#1676]
`elasticapm.utils.wrapt.decorators` module imports `formatargspec` from `inspect` package, which is removed at python3.11.

**Comment by beniwohli** [comment]
@tanagumo thanks for raising this issue! We've decided to completely remove `elasticapm.utils.wrapt` and instead rely on the official `wrapt` package going forward. We'll release a new version of the agent ASAP!

**Comment by tanagumo** [comment]
@beniwohli thanks for your quick response!
