### ISSUE TITLE
Not compressing spans ?

### ISSUE THREAD

**Issue by precbioinf** [elastic/apm-agent-python#1685]
**Describe the bug**: 

Profiling a custom application (radicale.org) and noticed that spans are not compressed:
![image](https://user-images.githubusercontent.com/10626186/199561676-cd02bf15-2f5b-4475-b87f-f85548883dbb.png)

These are successive calls to the same class method annotated using "@elasticapm.capture_span()"

Could this because the method is invoked by different instances of the class ? Or based on the parameters of the method call ?
The documentation only specify span name, type, subtype, and destination as the basis for compression.
How does class instances and calling parameters set different values for these ? 

**Environment (please complete the following information)**
- OS: Windows 10
- Python version: 3.9.13
- Framework and version [e.g. Django 2.1]: custom code
- APM Server version: 8.4.2
- Agent version: 6.12.0

**Additional context**

apm = elasticapm.Client (
        service_name = "radicale",
        server_url = "https://xxxxx",
        service_version = "0.1.0",
        verify_server_cert = False,
        span_compression_enabled = True,
        span_compression_exact_match_max_duration = "50ms",
        span_compression_same_kind_max_duration = "50ms",
    )

**Comment by brett-fitz** [comment]
Python Code:

```
async with AsyncElasticsearch(**elastic_context) as client:
    async for doc in async_scan(
        client=client,
        index='XXX',
        query=query,
        _source={
            "includes": ["XXX"],
            "excludes": ["XXX"]
        }
    ):
```

**Comment by beniwohli** [comment]
Closing this now. @precbioinf if you still encounter this issue, feel free to reopen.
