### ISSUE TITLE
Elastic APM crashes when trying to inspect hits from queries while track_total_hits is False

### ISSUE THREAD

**Issue by cccs-sgaron** [elastic/apm-agent-python#1686]
**Describe the bug**: 

The Elastic APM instrumentation for _Elasticsearch_ tries to get total number of hits in the results of a query but if the **track_total_hits** is set to **False** the `result.body['hits']` does not have a **total** key.

Fails at this line exactly with a KeyError('total'): https://github.com/elastic/apm-agent-python/blob/8b22d6a910ceda6587b99e47d8b3c9fa95c8d490/elasticapm/instrumentation/packages/elasticsearch.py#L180

**To Reproduce**

1. Instrument your python code with ElasticAPM, you don't even need to have the APM server up it crashes while collecting the data
2. Run any search query with **track_total_hits** set to **False**
`client.search(params={'track_total_hits': False}, **query_body)`

**Environment (please complete the following information)**
- OS: Linux
- Python version: 3.9
- Framework and version [e.g. Django 2.1]: Flask
- APM Server version: Irrelevent
- Agent version: 6.13.0

**Additional context**

This will crash no matter the config. We've reverted our code to use ElasticAPM 6.12 to make it work again.

**Comment by basepi** [comment]
Thanks for the report! This is fixed in #1687 and we should have a 6.13.1 release out soon.
