### ISSUE TITLE
KeyError: 'db' for DroppedSpan when running scan query on Elasticsearch

### ISSUE THREAD

**Issue by flaper87** [elastic/apm-agent-python#1689]
**Describe the bug**: ...

Elastic APM fails with a `KeyError: db key not found`.

The application where this happens is a Django project that stores/reads data from Elasticsearch. I have APM enable (APM server and Elasticsearch cluster are both running on Elastic Cloud). The library fails with the aforementioned error (shown in the snippet and screenshots below) while running a scan query on Elasticsearch. It looks like it's dropping some spans, which ends up in this case:

```
            hits = self._get_hits(result_data)
            if hits:
                span.context["db"]["rows_affected"] = hits
 
            return result_data
```

here's a screenshot of what I see on the APM Error page:

![image](https://user-images.githubusercontent.com/13816/200343191-fcff09cb-17f0-4f95-90db-f49fd1ab632d.png)

Few variables from the context:

![image](https://user-images.githubusercontent.com/13816/200343396-b95e0f90-a62e-4a4d-ad5d-87554b2a1d53.png)

**To Reproduce**

Unfortunately, I don't have a reproducible snippet. 

**Environment (please complete the following information)**
- OS: Linux (containerized)
- Python version: 3.9.15
- Framework and version [e.g. Django 2.1]:
- APM Server version: 7.17.4
- Agent version: 

```
$ pip freeze | grep elastic
django-elasticsearch-dsl==7.2.2
elastic-apm==6.13.1
elasticsearch==7.17.4
elasticsearch-dsl==7.4.0
```

**Additional context**

**Comment by basepi** [comment]
Thanks for the thorough report! Fixed in https://github.com/elastic/apm-agent-python/pull/1690

**Comment by flaper87** [comment]
Thanks for the quick fix! Should I expect this to be released as a patch release?

**Comment by basepi** [comment]
> Should I expect this to be released as a patch release?

Yes, though it may not be until next week.

**Comment by flaper87** [comment]
> > Should I expect this to be released as a patch release?
> 
> Yes, though it may not be until next week.

I see, thanks. I guess I will have to install from the commit for a week since this is breaking our environment.
