### ISSUE TITLE
flask_openapi3 support

### ISSUE THREAD

**Issue by dikshith** [elastic/apm-agent-python#1697]
Hi Team,

**Need help/fix for flask_openapi3 support?** in Elastic APM.

We are using FLASK_OPENAPI3 version of Flask implementation in which APM UI(Kibana) is unable to display the TRANSACTIONS.
We are using ELASTIC APM to instrument FLASK APP with Wsgi, Gunicorn.

The events are generated and submitted to APM Server with status code as "202". The APM - Kibana UI is unable to display the requests.
**_Sent request, url=http://x.x.x.7.149:8200/intake/v2/events size=5.11kb status=202
Exception message : N/A
Culprit - threading._bootstrap_**
Flask app with Gunicorn + wsgi uses gevent - **gunicorn --worker-class=gevent --timeout=0 --worker-connections=100 --workers=9 wsgi:app**
![image](https://user-images.githubusercontent.com/2103133/202592462-22759983-55ca-4f08-ae28-2be63a0bc2ee.png)
![image](https://user-images.githubusercontent.com/2103133/202592501-e65a4f1b-701e-4fb3-9dc3-8641762f490e.png)

**My question is :** **The APM UI shows empty with no transactions being recorded, that's the issue am facing even though APM logs** show - {"log.level":"info","@timestamp":"2022-11-15T04:47:07.194-0600","log.logger":"request","log.origin":{"file.name":"middleware/log_middleware.go","file.line":63},"message":"request accepted","url.original":"/intake/v2/events","http.request.method":"POST","user_agent.original":"apm-agent-python/6.11.0 (RHEL_53_WorklistServices)","source.address":"172.27.7.53","http.request.body.bytes":526,"http.request.id":"10f63edd-8dbe-400b-af74-b46c86f62c5a","event.duration":10410600,"http.response.status_code":202,"ecs.version":"1.6.0"}
![image](https://user-images.githubusercontent.com/2103133/202592650-5b45e088-1f0b-497b-b2fd-67b7593ef00a.png)

**We are initializing the app like here -**

```python
from flask import Flask
from elasticapm.contrib.flask import ElasticAPM
import elasticapm
from elasticapm.handlers.logging import LoggingHandler
from elasticapm.contrib.flask import ElasticAPM
from elasticapm.handlers.logging import LoggingHandler
"""
# WSGI - stands for web server gateway interface.
# used to forword requests from web server to a backend python web
  application or framework.
# WSGI server simply invokes a callable object on the WSGI application
"""
server_url = 'http://x.x.x.x:8200'
service_name = 'RHEL_WorklistSVC'
environment = 'RHEL_DEV'
app = create_app()
apm = ElasticAPM(app, server_url=server_url, service_name=service_name, environment=environment, logging=True)
elasticapm.instrument()
```

Here is the code for "CREATE_APP" , please help me why we are not getting transactions in the UI.

```python
import os
from datetime import timedelta
from flask import request
from werkzeug.exceptions import HTTPException
from flask_jwt_extended import JWTManager
from flask_openapi3 import Info, HTTPBearer, OpenAPI
from jivacore.logger.log import Logger
from worklist.resources.worklist import worklist_routes
from worklist.resources.other_routes import health_routes
from worklist.common import constants
from worklist.security import permissions
from jivacore.db.db import get_scoped_session
from worklist import config, error_handlers


def create_app(flask_config=None, **kwargs):
    """
    Instantiation and configure of flask application
    Args:
        flask_config (str): Flask configuration value
    Returns:
        OpenAPI: Flask OpenAPI instance
    """
    info = Info(title=os.getenv("PROJECT_NAME"), version="1.0.0", description=constants.WORKLIST_DESCRIPTION)
    app = OpenAPI(__name__, info=info, security_schemes={"jwt": HTTPBearer()})

    # Configuring logger for Worklist Service
    logger = Logger(request)
    logger.info('*******************Starting worklist Service********************')

    # Load application configuration from the object
    config.LoadApplicationConfig(app, flask_config)

    # Adding permissions to the application
    app.permissions = permissions

    # Adding scoped_session to the application
    app.scoped_session = get_scoped_session()

    # JSON Web Token configuration
    jwt = JWTManager(app)
    app.config["JWT_IDENTITY_CLAIM"] = "jti"
    app.config["JWT_TOKEN_LOCATION"] = ["headers", "cookies"]
    app.config["JWT_ACCESS_COOKIE_NAME"] = "aptn"
    app.config["JWT_ACCESS_CSRF_HEADER_NAME"] = "X-CSRFT"
    app.config["JWT_ACCESS_TOKEN_EXPIRES"] = timedelta(minutes=30)

    # Register Error Handlers
    jwt.unauthorized_loader(error_handlers.missing_token_callback)
    app.register_error_handler(HTTPException, error_handlers.http_errors)
    app.register_error_handler(Exception, error_handlers.global_errors)

    # Register blueprints
    app.register_api(worklist_routes)
    app.register_api(health_routes)

    # Before and after request handlers
    app.before_request(config.before_request_func)
    app.after_request(config.after_request_func)
    app.teardown_request(config.teardown_request_func)

    return app
```

**Comment by dikshith** [comment]
hi @basepi ,

Just to have the info, when is the next version release planned which I hope would support open API3

**Comment by basepi** [comment]
@dikshith Unfortunately we're not sure. I'm hoping to get it on our next version planning but even then we don't commit to dates or versions. Sorry for the inconvenience!

**Comment by dikshith** [comment]
Hopefully the next version planned soon !! Any workaround would help ....

**Comment by basepi** [comment]
Hmmm, I set up the [test app ](https://github.com/luolingchun/flask-openapi3#a-simple-example)from the project's README and it seems to be working for me. Perhaps try setting `debug=True` in case flask_openapi3 sets the debug flag by default?

```python
apm = ElasticAPM(app, server_url=server_url, service_name=service_name, environment=environment, logging=True, debug=True)
```

Here is my working example app:

```python
from pydantic import BaseModel

from flask_openapi3 import Info, Tag
from flask_openapi3 import OpenAPI
from elasticapm.contrib.flask import ElasticAPM


info = Info(title="book API", version="1.0.0")
app = OpenAPI(__name__, info=info)
apm = ElasticAPM(app, service_name="openapi3_is_great", debug=True)

book_tag = Tag(name="book", description="Some Book")


class BookQuery(BaseModel):
    age: int
    author: str


@app.get("/book", tags=[book_tag])
def get_book(query: BookQuery):
    """get books
    get all books
    """
    return {
        "code": 0,
        "message": "ok",
        "data": [
            {"bid": 1, "age": query.age, "author": query.author},
            {"bid": 2, "age": query.age, "author": query.author}
        ]
    }


if __name__ == "__main__":
    app.run(debug=True)
```
