### ISSUE TITLE
No message sending to APM server

### ISSUE THREAD

**Issue by fallingleaf** [elastic/apm-agent-python#170]
- I'm trying simple Elastic APM example with python flask agent on local. I noticed that there're several logs saying that APM threads are sending messages to server after I hit `Ctrl + C`. However, I checked kibana and elastic cluster, there're no documents.

`PID 8745: ElasticAPM is attempting to send 1 pending messages
Waiting up to 10 seconds, press Ctrl-C to quit.
PID 8745: done, took 9.90 seconds to complete.`

My settings:
`{'MAX_EVENT_QUEUE_LENGTH': 500, 'TIMEOUT': 5, 'DISABLE_SEND': False, 'SECRET_TOKEN': '0123456789abcdefghijklmnopqrstxyz', 'DEBUG': False, 'SERVER_URL': 'http://localhost:8200/', 'APP_NAME': ''}
`
Flask debug set to False.

Code to send message:

`apm.capture_message('hello elastic apm')`

**Comment by beniwohli** [comment]
Hi @fallingleaf! Can you try it with `SERVICE_NAME` instead of `APP_NAME`? There's been some backwards incompatible changes between 6.1 Beta and 6.2 of the apm-server, and version 2.0 and up of the Python agent implements those changes. The [changelog](https://github.com/elastic/apm-agent-python/blob/master/CHANGELOG.asciidoc#v200) has a full list of backwards incompatible changes.

**Comment by fallingleaf** [comment]
Thanks @beniwohli, I tried with `SERVICE_NAME`, but still it's not sending any messages. These are my softwares: elasticsearch-6.1.3, kibana-6.1.3, apm-6.2.2 and python agent elastic-apm-2.0.1

**Comment by beniwohli** [comment]
Do you see any error messages printed by flask related to APM? Or any error messages printed by the apm-server (you might have to start it with the `-e` flag to print errors to the console, `apm-server -e`.

Another thing, if you intend to use the APM UI in Kibana X-Pack basic, you'll need to upgrade elasticsearch and kibana to 6.2.

**Comment by fallingleaf** [comment]
yeah I'm running apm server with `-e` flag, no error messages from both sides, I also check apm server `logs` file, but no error. I cannot debug with no error message. Only log I can see in apm-server: 
`2018-02-26T11:46:51.346-0800	INFO	[monitoring]	log/log.go:124	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":109,"time":109},"total":{"ticks":352,"time":354,"value":352},"user":{"ticks":243,"time":245}},"info":{"ephemeral_id":"10a11c9c-6d88-441e-99de-479c24c69d3b","uptime":{"ms":3720008}},"memstats":{"gc_next":4358928,"memory_alloc":3907944,"memory_total":74140160}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":0}}},"system":{"load":{"1":2.5977,"15":2.2222,"5":2.2319,"norm":{"1":0.3247,"15":0.2778,"5":0.279}}}}}}`

**Comment by fallingleaf** [comment]
Resolved: with my above setting `'SERVER_URL': 'http://localhost:8200/'`, transport url becomes invalid: `http://localhost:8200//v1/errors`. Thread worker stuck at opening POST request to server without any response: 

`response = self.http.urlopen('POST', url, body=data, headers=headers, timeout=timeout, preload_content=False)`

**Comment by beniwohli** [comment]
Great catch @fallingleaf! I'll make sure to make it work with both a trailing slash and no trailing slash in the next release!
