### ISSUE TITLE
Bug when sending message contains formatter

### ISSUE THREAD

**Issue by fallingleaf** [elastic/apm-agent-python#171]
This code on `events.py` (line 144) will introduce error `not enough arguments for format string` if I send normal messages that contain string formatter:

`@staticmethod
    def capture(client, param_message=None, message=None, level=None, logger_name=None, **kwargs):
        if message:
            param_message = {'message': message}
        params = param_message.get('params', ())
        message = param_message['message'] % params
        data = kwargs.get('data', {}) `

for example: `apm.capture_message('abc%def') ` which usually happens when I capture the http request. My suggestion is not to force normal message to become param message when param message is None.

**Comment by beniwohli** [comment]
Thanks for the report @fallingleaf, you're absolutely right, this is a bug. I'm currently traveling, so it's probably going to be a few days until I can get around to fix this
