### ISSUE TITLE
OPTIONS Request in Flask uses content-type of None

### ISSUE THREAD

**Issue by JelleM-Congressus** [elastic/apm-agent-python#172]
OPTIONS requests (CORS Preflight) are checked for content-type on the request object in the flask contrib module (`elasticapm/contrib/flask/utils.py`):

```
    if request.method not in ('GET', 'HEAD'):
        body = None
        if request.content_type == 'application/x-www-form-urlencoded':
            body = compat.multidict_to_dict(request.form)
        elif request.content_type.startswith('multipart/form-data'):
            body = compat.multidict_to_dict(request.form)
```

However an OPTIONS requests does not have a content_type by default which causes the `startswith()` method to be called on a NoneType resulting in a crash as this exception is unhandled.

**Comment by beniwohli** [comment]
Thanks for the report @JelleM-Congressus, this looks like a bug indeed! I'm currently traveling, so it's probably going to be a few days until I can get around to fix this.
