### ISSUE TITLE
ServiceMap UI does not show links between lambda calls with API gateway

### ISSUE THREAD

**Issue by g3kr** [elastic/apm-agent-python#1757]
**Describe the bug**
All I am trying is to pass a custom traceparent with the event JSON in a lambda function, that get passed to the child lambda function so that these services show up under one trace parent in elastic and the APM UI shows the serviceMap link between the services.

**To Reproduce**
1. Two Python Lambda functions (parent, child) that uses the Elastic APM python agent (elastic-apm-extension-ver-1-2-0-x86_64) to capture and monitor data on the function's performance. Specifically, the Parent lambda invokes the child Lambda function, and I'm capturing this request as a span in the APM agent and propagating the same traceparent to child lambda. Attached the code for both lambdas
[ChildLambda.txt](https://github.com/elastic/apm/files/10746479/ChildLambda.txt)
[ParentLambda.txt](https://github.com/elastic/apm/files/10746481/ParentLambda.txt)

The lambdas run fine. However the elastic APM UI does not show the expected links. Attached screenshots from Elastic APM. What am I missing?
<img width="1522" alt="ServiceMap" src="https://user-images.githubusercontent.com/6721657/219128329-d30323bb-2569-46e4-a08e-9756adf7ba2a.png">
<img width="1539" alt="services" src="https://user-images.githubusercontent.com/6721657/219128338-592a18cd-42d7-4dbb-bbc4-88e6da5644bd.png">

**Expected behavior**
The traceparent gets passed to the child lambda and shows up in the UI in the serviceMap link.

The link should flow from parentlambda to childlambda. The childlambda is orphaned now.

**Comment by g3kr** [comment]
The `trace.id` is different between the Childlambda and ParentLambda which is why the link seems to be broken. Since propagation did not work I am not sure how else to make it work. I re-enabled adding the traceparent to the custo context, but no difference. 

Is there an API to get the `traceparent` from ChildLambda, that way I can ensure the `set_custom_context` is really working.

If i may ask, can you share an example of how trace propagation works with python-apm agent and AWS lambda? It appears to be a simple thing to do, somewhere things are breaking.

**Comment by g3kr** [comment]
@basepi Changed the HTTP request endpoint to lambda function URL instead of API gateway endpoint and trace propagation automagically worked :)
Thanks for leading me in the right direction.
<img width="977" alt="Screenshot 2023-02-17 at 11 47 27 AM" src="https://user-images.githubusercontent.com/6721657/219720537-510ed587-2577-40f9-8158-0c73e743e61d.png">

**Comment by basepi** [comment]
Glad you have it working!

That said, the trace propagation *should* work through an API Gateway endpoint as well. I wonder if the API Gateway was overwriting our `traceparent` header for some reason? Do you want to help me explore that issue or call it "solved" with function URLs for now?

**Comment by basepi** [comment]
I have been unable to reproduce this. I have two lambda functions, one that I'm triggering with a lambda URL, which does a `requests.get` against the API gateway that fronts the second. The headers are present, and the service map correctly shows the two services connected:

![image](https://user-images.githubusercontent.com/702318/223858075-7fe22b27-b279-473f-afb8-8c7fe2d0a5fd.png)

I will note I did *briefly* see an "uninstrumented node" for the API gateway like you were seeing above, but it appears to be a transient issue because I haven't been able to get it back. The service map uses live queries so perhaps 

Please keep me posted if you find any other issues with the lambda integration, and I'll happily look again.
