### ISSUE TITLE
apm-agent attempts to unpack localhost URLs with service/region via botocore

### ISSUE THREAD

**Issue by lewisren** [elastic/apm-agent-python#176]
When running locally (localhost:13579), it for some reason attempts to utilize botocore and try to unpack the URL into 
``` service, region, _ = parsed_url.hostname.split('.', 2) ```

Naturally this fails since the hostname is localhost. I'm not sure why it's using botocore here, or if it should just be defensive against accepting localhost as a valid param

**Comment by beniwohli** [comment]
@lewisren sorry for the slowness on this, it fell between the cracks with traveling and vacation. I just merged a fix and will push a new release to PyPI in the next few hours

**Comment by lewisren** [comment]
Thanks!
