### ISSUE TITLE
urllib3 v2.0 compatibility

### ISSUE THREAD

**Issue by basepi** [elastic/apm-agent-python#1816]
urllib3 v2.0 came out during PyConUS 2023 and is resulting in hanging tests on windows, and test failures on Linux. We need to update our code/tests to ensure compatibility for this new version.

**Comment by pquentin** [comment]
Hello fellow Elasticians :wave: 

We just released [urllib3 2.0.1](https://github.com/urllib3/urllib3/releases/tag/2.0.1) that includes https://github.com/urllib3/urllib3/pull/2992. We have extensive tests for cert pinning, but Tornado (our test server) can accept multiple connections at a time unlike pytest-localserver. So we did not see the resource leak that caused the deadlock in your case, sorry about that.

Would you mind giving 2.0.1 a try?

**Comment by basepi** [comment]
@pquentin worked wonderfully. Thanks!
