### ISSUE TITLE
Enhancement Request: Add elasticapm.set_custom_span_context()

### ISSUE THREAD

**Issue by LucaWintergerst** [elastic/apm-agent-python#1856]
**Description**
Currently, the Elastic APM Python library restricts custom context to the transaction and error level. However, there is a use case where the user would like to enrich their spans with metadata, and storing it on the transaction level is not suitable. It would be beneficial to have a method like elasticapm.set_custom_span_context() that applies to the currently active span only.

**Context**
In an internal Slack conversation, it was discussed that custom context can be set for spans using an undocumented argument extra on capture_span(). However, this argument is not namespaced, which means users could accidentally overwrite the internal context.

**Proposed Solution**
To address the limitations and provide a more intuitive way of setting custom context for spans, it is suggested to add the elasticapm.set_custom_span_context() method to the Elastic APM Python library. This method should allow users to specify custom metadata for the currently active span without the risk of overwriting internal context.

**Expected Behavior**
The elasticapm.set_custom_span_context() method should enable users to set custom metadata for the currently active span only. The custom context should be namespaced to avoid conflicts with internal context. This enhancement would provide more flexibility in enriching spans with metadata and better serve the use case mentioned in the Slack conversation.

**Comment by basepi** [comment]
I had completely implemented this in #1893, when my reviewer pointed out that we don't have custom span context in the [spec](https://github.com/elastic/apm-agent-python/blob/70f6475ee1c15070a664c15a51d1d3ca082ed35b/tests/upstream/json-specs/span.json#L53-L607), and thus the data will probably be dropped. I did some testing, and sure enough, any data outside of the spec'd context fields will be dropped. 😓 

I think the answer for now is to use labels (which will be sent via the `tags` context) for any user-data that's span-specific.
