### ISSUE TITLE
TypeError: write() argument must be str, not bytes

### ISSUE THREAD

**Issue by mastak** [elastic/apm-agent-python#186]
Here message pass to `to_string` and then to `sys.stderr.write()`
`to_string` – returns bytes
`sys.stderr.write` receives str

`TypeError: write() argument must be str, not bytes`:

**Comment by beniwohli** [comment]
Hi @mastak! Thanks for the report! I assume you are getting this in connection with our logging handlers? There is indeed a bug there, and I opened a PR to fix it (#187). Sorry about that!

**Comment by mastak** [comment]
Hi @beniwohli!

Yes, I faced with it in logging handler. 
By the way,  I thought I pasted the path to file `elasticapm/handlers/logging.py` in the issue, but not, sorry.

PS thanks for quick response!

**Comment by beniwohli** [comment]
The PR is merged now. We'll make a release with this in the next few days!
