### ISSUE TITLE
[META 808] Make `include_process_args` an opt-in option

### ISSUE THREAD

**Issue by elastic-apm-tech** [elastic/apm-agent-python#1860]
See meta issue and spec for the description and details:
- Meta issue: https://github.com/elastic/apm/issues/808
- Spec issue: https://github.com/elastic/apm/issues/809

**Comment by basepi** [comment]
We don't currently have `include_process_args`. Checking on the [meta issue](https://github.com/elastic/apm/issues/808#issuecomment-1607984126) if this is relevant to us.
