### ISSUE TITLE
support for asynchronous psycopg3

### ISSUE THREAD

**Issue by Antonkoch999** [elastic/apm-agent-python#1872]
psycopg3 was released some time ago

You started supporting psycopg in version 6.16, but only synchronous operations.
Tell me, please, is it possible to implement support for asynchronous operations too?

https://www.psycopg.org/psycopg3/docs/advanced/async.html#async

**Comment by basepi** [comment]
We should definitely add support for async psycopg3 as well. Thanks for the request!

**Comment by zikphil** [comment]
@basepi Good morning. Do we know if/when we should expect monitoring options for AsyncIO versions of DBAPIv2 compliant objects?
