### ISSUE TITLE
Can't disable elastic traceparent headers

### ISSUE THREAD

**Issue by brett-fitz** [elastic/apm-agent-python#1877]
(Possible misconfiguration) I can't seem to disable Elastic APM traceparent headers for requests made using the aiohttp library. I am using environment variables to disable.

**To Reproduce**

1. Set environment variable
2. Instrument python AWS lambda function - capture_serverless()
3. Make http request using aiohttp
4. Capture request readers and inspect for traceparent headers 

aiohttp session creation / request

```python
# Create Session
async with aiohttp.ClientSession(response_class=WrappedResponseClass) as session:
    resp = await session.request(
                url=f'{protocol}://{address}:{port}{path}',
                method='GET',
                headers=headers,
                timeout=aiohttp.ClientTimeout(sock_connect=5, total=20),
                ssl=ssl_context
            )
```

Instrumentation via `capture_serverless()`:

*Note: Handler function executes an async coroutine: asnyc_handler to start async event loop*

```python
async def async_handler(event):
    # call some code that makes an aiohttp request

    return {
            'statusCode': 200,
            'body': 'success'
        }
```

```python
@capture_serverless()
def handler(event, _context) -> Dict:
    return asyncio.run(async_handler(event))
```

**Environment (please complete the following information)**
- OS: [e.g. Linux] debian:bullseye-slim (python:3.9-slim container image) x86
- Python version: 3.9
- Framework and version [e.g. Django 2.1]: N/A AWS Lambda Function
- APM Server version: 8.8.2
- Agent version: 6.15.0

**Additional context**

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    AWS_LAMBDA_EXEC_WRAPPER: /opt/python/bin/elasticapm-lambda
    ELASTIC_APM_LOG_LEVEL: error
    ELASTIC_APM_LAMBDA_APM_SERVER: https://<Elastic Cloud Hostname>:443
    ELASTIC_APM_SECRET_TOKEN: ${env:ELASTIC_APM_SECRET_TOKEN}
    ELASTIC_APM_ENVIRONMENT: ${self:provider.stage}
    ELASTIC_APM_USE_ELASTIC_TRACEPARENT_HEADER: False
    ELASTIC_APM_CAPTURE_HEADERS: False
    ELASTIC_APM_SPAN_COMPRESSION_SAME_KIND_MAX_DURATION: 1000ms
    ELASTIC_APM_SPAN_STACK_TRACE_MIN_DURATION: 50ms
    ```
  </details>
- `pyproject.toml deps`:
  <details>
    <summary>Click to expand</summary>

    ```
    [tool.poetry.dependencies]
    python = "^3.9"
    requests = "^2.28.2"
    scapy = "^2.5.0"
    urllib3 = "^1.26.15"
    pefile = "^2023.2.7"
    python-dateutil = "^2.8.2"
    elasticsearch = "^8"
    pyjarm = "^0.0.5"
    shodan = "^1.28.0"
    netstruct = "^1.1.2"
    PyYAML = "^6.0"
    elastic-apm = "^6.15"
    aiohttp = "^3.8.4"
    tomlkit = "^0.11.6"
    uvloop = "^0.17.0"
    multidict = "^6.0.4"
    aiobotocore = "^2.5"
    boto3 = "^1.26"
    types-aiobotocore = {extras = ["essential"], version = "^2.5.0"}
    python-tlsh = "^4.5.0"
    domaintools-api = "^1.0.1"
    ipykernel = "^6.21.3"
    httpx = "^0.23.3"
    cryptography = "^38.0.4"
    yamale = "^4.0.4"
    aiofiles = "^22.1.0"
    validators = "^0.20.0"
    censys = "^2.1.9"
    pyopenssl = "^23.1.1"
    pyasn1 = "^0.5.0"
    pandas = "^2.0.2"
    tldextract = "^3.4.4"
    paramiko = "^3.2.0"
    pyelftools = "^0.29"
    ```
  </details>

**Comment by basepi** [comment]
I think this is a misunderstanding. All that `ELASTIC_APM_USE_ELASTIC_TRACEPARENT_HEADER: False` does is disable the fallback/legacy header `elasticapm-traceparent`. It does not disable distributed tracing. Can you clarify your use case here?

**Comment by brett-fitz** [comment]
I'm not sure if there is a way to disable tracing for a specific span? e.g.

```python

@elastic_apm.disable_capture()
async def my_func():
    return

```

**Comment by basepi** [comment]
Currently, we don't have a way to disable distributed tracing for our automatic instrumentations. One way you could do it is to disable the aiohttp automatic instrumentation, and then use `elasticapm.capture_span()` to capture the call manually. Unfortunately, you'll miss out on some of the extra context that we collect with the `aiohttp` [automatic instrumentation](https://github.com/elastic/apm-agent-python/blob/main/elasticapm/instrumentation/packages/asyncio/aiohttp_client.py), like url, header collection, and automatic handling of HTTP status codes for "span outcome" (success/failure). You could set that context manually if you'll miss it.

Instrumentations can be disabled with the environment variable `SKIP_INSTRUMENT_<name>`, where `<name>` is the name defined in the instrumentation for aiohttp_client, [the name is `aiohttp_client`](https://github.com/elastic/apm-agent-python/blob/bf7534f45ac8c22512dfa54b68ca831b4ab71e7a/elasticapm/instrumentation/packages/asyncio/aiohttp_client.py#L40), so you would set `SKIP_INSTRUMENT_AIOHTTP_CLIENT: True`. Then, you could surround your call with `elasticapm.capture_span()` to capture the span manually without adding distributed tracing headers.

**Comment by brett-fitz** [comment]
No worries there, this is a great solution and thank you for the helpful tips!
