### ISSUE TITLE
IndexError when "url" not found in args or kwargs.

### ISSUE THREAD

**Issue by pd-pg** [elastic/apm-agent-python#1884]
### Overview

I've found an issue in line 46 of `call()` method in `AioHttpClientInstrumentation(...)` class.

https://github.com/elastic/apm-agent-python/blob/da93e7af448abcac367d216e2d20a584051f6e50/elasticapm/instrumentation/packages/asyncio/aiohttp_client.py#L44-L47

I'm getting an `IndexError` exception due to lack or "url" in both kwargs and in args[1]. The the reason is that the argument containing urls is called "str_or_url".

https://github.com/aio-libs/aiohttp/blob/4b59d55e9e79f5a0b1932d6dc9f6b12a33d19266/aiohttp/client.py#L325-L328

By default the code is running fine, but this issue will appear in cases where someone will try to use `ClientSession._request()` method directly AND use keyword-arguments.

### How to recreate the bug?

This is a general example on how to recreate the bug. Lets assume that somewhere in my code I want to connect to some external http rest-api service using aiohttp library. I'll be using custom made session object based on ClientSession object from aiohttp library.

```python
from aiohttp import ClientSession, ClientResponse

class CustomSession(ClientSession):

    async def _request(self, method: str, str_or_url: StrOrURL, **kwargs: Any) -> ClientResponse:
        # put some extra code here, like add retry functionality
        client_response = await super()._request(method=method, str_or_url=url, **kwargs) # << ISSUE IS HERE
        return client_response
```
the above code is valid and it works as long as there is no apm agent running as middleware. With apm agent added, the code has to be written as below:
```python
        client_response = await super()._request(method, url, **kwargs)
```

### How to fix it?

Do search for both `url` and `str_or_url` in kwargs. It's simple fix that can fit in same line, I bet.

**Comment by basepi** [comment]
Thanks for the find! Would you be willing to submit a PR for this fix?

**Comment by pd-pg** [comment]
I can't promise it will be soon, but I'll try to put something together and submit it as PR. After all it should be a really simple fix.

**Comment by basepi** [comment]
Excellent! Looking forward to your PR. No hurry. :)

**Comment by basepi** [comment]
Excellent, thanks @nbarbey!
