### ISSUE TITLE
`py.typed` is not in the published library 

### ISSUE THREAD

**Issue by fritzdj** [elastic/apm-agent-python#1924]
Hi @basepi, after https://github.com/elastic/apm-agent-python/pull/1897 was merged I was expecting to see typing support enabled when running mypy within consumer apps. However, I am still not seeing this get picked up currently. it looks like the https://github.com/elastic/apm-agent-python/blob/main/elasticapm/py.typed file that was added is not in the published version of this package (in v6.19). Is this file getting excluded and can this be modified so it is included?

Thank you!

**Comment by basepi** [comment]
Fixed in #1925
