### ISSUE TITLE
AttributeError: 'Retry' object has no attribute 'copy'

### ISSUE THREAD

**Issue by StephanErb** [elastic/apm-agent-python#1928]
The `elasticapm` Python client fails with `AttributeError: 'Retry' object has no attribute 'copy'` during HTTP retries.

The Elastic APM UI points towards the following lines being responsible for the crash https://github.com/elastic/apm-agent-python/blob/c9a1f7a74b4b8e39af06f9b383037a3ae49ca42b/elasticapm/instrumentation/packages/urllib3.py#L66-L68 

**To Reproduce**

Configure a `requests` session with [urllib3 retries](https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html) as described below. Then point it at a flaky endpoint.

``` python
class TimeoutHTTPAdapter(HTTPAdapter):
    def __init__(self, retries: int, *args: Any, **kwargs: Any) -> None:
        self.timeout = kwargs.pop("timeout", 30)
        self._retries = retries
        super().__init__(*args, **kwargs)

    def send( 
        self, request: requests.PreparedRequest, **kwargs: Any
    ) -> requests.Response:
        kwargs.setdefault("timeout", self.timeout)
        return super().send(request, **kwargs)

def session_with_retries(
    retries: int = 3,
    backoff_factor: float = 1,
    timeout: int = 30,
    status_forcelist: Collection[int] = (408, 429, 500, 502, 503, 504),
) -> requests.Session:

    retry_strategy = Retry(
        total=retries,
        backoff_factor=backoff_factor,
        status_forcelist=status_forcelist,
        allowed_methods=Retry.DEFAULT_ALLOWED_METHODS.union(["POST", "PATCH"]),
    )
    adapter = TimeoutHTTPAdapter(
        retries=retries, max_retries=retry_strategy, timeout=timeout
    )

    s = requests.Session()
    s.mount("http://", adapter)
    s.mount("https://", adapter)
    return s
```

**Environment**
- OS: Linux
- Python version: Python 3.11
- Framework and version: `urllib3==2.0.6` and `requests==2.31.0`
- APM Server version: 8.10.4
- Agent version: `elastic-apm==6.19.0`

**Background**
* This appears to be related to the recent urllib3 fixes https://github.com/elastic/apm-agent-python/pull/1822 and https://github.com/elastic/apm-agent-python/issues/1816

**Comment by cluster-master** [comment]
hello all, can you please suggest older previous version of elastic apm agent which is stable and has not that type of issues?

**Comment by basepi** [comment]
@cluster-master  You need to use an older version of `urllib3`; no version of the agent has a fix for this yet.

**Comment by xrmx** [comment]
@StephanErb could you please provide an example requests session method call please? Just need the method and what parameters you are passing, no need for actual values. Thanks.

**Comment by StephanErb** [comment]
You can find a public example here which triggers the issue: https://github.com/kubernetes-client/python/blob/master/kubernetes/client/rest.py#L217-L221 

I don't seem to be able to reproduce it with anything else any longer besides the Kubernetes client.

**Comment by xrmx** [comment]
@StephanErb thanks!

**Comment by xrmx** [comment]
@StephanErb the kubernetes code pass args as kwargs though so it'll not pass thru the same code path. Do you have another stack trace?

**Comment by StephanErb** [comment]
@xrmx does that help? 
```
kubernetes==27.2.0
urllib3==2.2.1
elastic-apm==6.20.0
```
![Elastic-APM-Error](https://github.com/elastic/apm-agent-python/assets/483730/8e7e4fd2-98b2-4f4b-8fcd-7a1286da9d7a)
