### ISSUE TITLE
dbapi2 fails to extract table name when using square brackets 

### ISSUE THREAD

**Issue by anderssonjohan** [elastic/apm-agent-python#1929]
**Describe the bug**: ...

Queries made to tables which requires escaping end up with the wrong span name.

The following spans are SELECTs from four different tables, but only two unique span names appear.
![Screenshot 2023-10-31 at 19 13 46](https://github.com/elastic/apm-agent-python/assets/435885/5384fd4d-df13-4828-a9f2-b7e1c309f07f)

**To Reproduce**

Import package and call [extract_signature](https://github.com/elastic/apm-agent-python/blob/05332cd007560615b4421b1567659ff9f9634088/elasticapm/instrumentation/packages/dbapi2.py#L153):

```python
>>> from elasticapm.instrumentation.packages import dbapi2
>>> dbapi2.extract_signature("SELECT username FROM user")
'SELECT FROM user'
>>> dbapi2.extract_signature("SELECT username FROM [user]")
'SELECT FROM ['
```

**Environment (please complete the following information)**
- OS: [e.g. Linux]
- Python version:
- Framework and version [e.g. Django 2.1]:
- APM Server version:
- Agent version:

**Additional context**

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your agent config options
    remember to mask any sensitive fields like tokens
    ```
  </details>
- `requirements.txt`:
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your `requirements.txt`
    ```
  </details>

**Comment by aless10** [comment]
Hi, I would like to contribute and give it a try to fix this

**Comment by anderssonjohan** [comment]
@aless10 I'm touching the same thing in this PR. Perhaps you will find my parameterized test useful as boiler-plate code here: https://github.com/elastic/apm-agent-python/pull/1938/files
