### ISSUE TITLE
Make it possible to build test artifacts

### ISSUE THREAD

**Issue by xrmx** [elastic/apm-agent-python#1994]
**Is your feature request related to a problem? Please describe.**

We are not able to catch problems in the build workflows until it's too late. Since our release process requires to cut a new release and the fact that we are distributed that'll adds tons of latency for getting a package out of the building.

Recent incidents:

https://github.com/elastic/apm-agent-python/pull/1990
https://github.com/elastic/apm-agent-python/pull/1993 and https://github.com/elastic/apm-agent-python/pull/1996

**Describe the solution you'd like**

I'd like to being able to run the release workflows pushing test packages / lambdas / you name it to test instances so we can check that the workflows are working.

Ideally this would be run every time we touch .github/workflows to catch dependabot regressions :)

The emphasis here is running the very same github workflows and not on publishing test artifacts.

**Describe alternatives you've considered**

None I can think of.

**Additional context**

In python we have a test package index (https://test.pypi.org/) where we can push things without bothering anyone.

**Comment by v1v** [comment]
I enabled the test.pypi as explained in https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-pypi

<img width="867" alt="image" src="https://github.com/elastic/apm-agent-python/assets/2871786/4d8b4dca-7704-4b0d-94ea-ab01df47e6ad">
