### ISSUE TITLE
Investigate local version in production packages

### ISSUE THREAD

**Issue by xrmx** [elastic/apm-agent-python#2015]
**Describe the bug**: 

6.21.4 got published to the production pypi (https://pypi.org/project/elastic-apm/#history) with a local release. That was not supposed to happen and local version should only have been added to the test packages.
Packages has been built from this actions run https://github.com/elastic/apm-agent-python/actions/runs/8347027212

**To Reproduce**

1. push a tag

**Environment (please complete the following information)**
- OS: [e.g. Linux]
- Python version:
- Framework and version [e.g. Django 2.1]:
- APM Server version:
- Agent version:

**Additional context**

**Comment by xrmx** [comment]
@elastic/observablt-ci can you help with this please?

**Comment by amannocci** [comment]
Hi @xrmx, it seems like it's the expected behavior.
The release is triggered on [tag creation](https://github.com/elastic/apm-agent-python/blob/main/.github/workflows/release.yml).

**Comment by v1v** [comment]
The [evil elvis](https://github.com/elastic/apm-agent-python/blob/main/.github/workflows/packages.yml#L21) didn't work correctly, since it was triggered with the `workflow_call`:

- https://github.com/elastic/apm-agent-python/actions/runs/8347027212/job/22845710899#step:3:9

**Comment by amannocci** [comment]
The '' is coerced to false, and as a result, the other value is always returned.
I will create PR to fix the issue.
