### ISSUE TITLE
New release for apm-agent-python with python 3.12

### ISSUE THREAD

**Issue by timostrunk** [elastic/apm-agent-python#2043]
**Is your feature request related to a problem? Please describe.**
After the wrapt-dependency was relaxed a new release is required to allow downstream to solve for environments with the new wrapt.
Currently this blocks our python 3.12 rollout, because the conda-forge package pins < 1.15.0 and there is no 1.14.1 release for python 3.12. 
The official support for python 3.12 in wrapt started with 1.16: https://github.com/GrahamDumpleton/wrapt/commit/bc3529c95ba9ade3876a25ca2c3280b799531eb2

**Describe the solution you'd like**
Could a new point release be made soon? 

**Describe alternatives you've considered**
I though of simply trying to ask in the conda-forge feedstock, whether we could relax the wrapt dependency as-is, but a new point release would be the much cleaner solution.

**Comment by xrmx** [comment]
I would like to try to sort out #2041 before cutting a new release. I'll try to cut a new release next week.

**Comment by timostrunk** [comment]
Awesome thank you!

**Comment by xrmx** [comment]
Released 6.22.2
