### ISSUE TITLE
Support for Azure OpenAI

### ISSUE THREAD

**Issue by sorenlouv** [elastic/apm-agent-python#2064]
The APM agent should have support for auto-instrumentation of [OpenAI library](https://github.com/openai/openai-python?tab=readme-ov-file#microsoft-azure-openai) in order to better support applications that interacts with this LLM. 

What we need to collect that we don’t collect OOTB today :
 - User prompt (string)
 - LLM response (string)
 - Token count (number)

**Related**

- https://github.com/elastic/observability-docs/issues/3961
- https://github.com/elastic/apm-agent-nodejs/issues/4074

**Comment by xrmx** [comment]
Given that the docs using OTel did get in I think we can close this.
