### ISSUE TITLE
Error while capturing exception that contains a extension module stack frame

### ISSUE THREAD

**Issue by martenbr** [elastic/apm-agent-python#217]
The following line 

https://github.com/elastic/apm-agent-python/blob/6328e3ddf789fe897257edf8f1197215f078df6b/elasticapm/utils/stacks.py#L80

raises 

    TypeError: 'NoneType' object is not subscriptable

When `loader.get_source(...)` returns None, which in my case it does because the loader is a [ExtensionFileLoader](https://docs.python.org/3/library/importlib.html#importlib.machinery.ExtensionFileLoader) that always returns None.

I am running elastic-apm 2.1.1 under Python 3.6

**Comment by beniwohli** [comment]
Thanks for the report @martenbr! Is the extension module you use publicly available so we can reproduce this?

**Comment by beniwohli** [comment]
@martenbr awesome, thanks, I'll get this fixed ASAP, but it'll probably be a couple of days until I can get around to it

**Comment by beniwohli** [comment]
@martenbr I just committed a fix. Thanks again for raising the issue! We'll cut a new release in the coming days.

BTW, we're working on instrumenting Cassandra, but don't really have that much code to test it with. If you have the time, it would be _super_ helpful if you could try out #205 in your dev environment and let us know how it goes. I rebased it on top of master just now, so it should contain the fix from #219.
