### ISSUE TITLE
Add Framework name and version in Sanic instrumentation

### ISSUE THREAD

**Issue by goodki-d** [elastic/apm-agent-python#2175]
Django and Flask integrations have **_framework name and version_** extracted from the packages automatically.
This is missing in Sanic integration, it will be very useful as I have a lot of applications running different frameworks and versions. 

(I currently use manual config which is not scalable and hard to maintain on upgrade)

**Comment by xrmx** [comment]
@goodki-d Are you passing a client explicitly when instantiating `ElasticAPM`? If so you need to use `elasticapm.contrib.sanic.utils.make_client` that will set framework name and version. The one created by default should contain the framework data already.

**Comment by goodki-d** [comment]
Yes I've been creating client object and passing it manually to `sanic.ElasticAPM`.
Thanks! I couldn't find anything related in docs so I thought the feature was absent
