### ISSUE TITLE
apm client is unable to connect to the apm server when the user attempts to use basic authentication in the server_url

### ISSUE THREAD

**Issue by bastbnl** [elastic/apm-agent-python#225]
I tried to connect to the apm-server using `server_url` with basic authentication, but that fails. I read that's because I'm using a secret token, which is passed along via the HTTP `Authorization` header. It would be nice if that case would be caught by the `elasticapm check` management command.

I'm using elastic apm on Django 2.0.6 and it appears to work properly.

PR coming up

**Comment by beniwohli** [comment]
closed by #226
