### ISSUE TITLE
Disable automatic Celery instrumentation

### ISSUE THREAD

**Issue by chripede** [elastic/apm-agent-python#236]
Is there any way to not instrument Celery in a Django project?

I run thousands of celery tasks every minute using gevent. Elastic APM will make the tasks halt and lock up the database.

**Comment by beniwohli** [comment]
Thanks for the report @chripede! There is a [setting](https://www.elastic.co/guide/en/apm/agent/python/current/configuration.html#config-instrument) you can use to disable instrumentation. To only make this setting visible for celery, you could set it as an environment variable for your Celery processes (`ELASTIC_APM_INSTRUMENT=false`).

Of course, the fact that Elastic APM causes these problems in the first place is concerning. I have to admit that our experience with gevent celery workers is relatively limited. It would be interesting to see if this issue also occurs with prefork workers if you have a way to test it without much work.

Also, with such a large amount of tasks per minute, we suggest to [sample](https://www.elastic.co/guide/en/apm/agent/python/current/configuration.html#config-transaction-sample-rate) aggressively.

**Comment by chripede** [comment]
I actually tried that, but somehow APM will still cause database connections to lock up. It seems that just loading it in INSTALLED_APPS causes gevented Celery tasks to lock

**Comment by beniwohli** [comment]
That's weird :( If you have logging set up, could you try to set the debug level for `elasticapm.instrument` to `DEBUG` and see if you get any log messages like 

    Instrumented some.module, SomeClass.some_function

(ensure that you run version 2.2.1 of the Elastic APM agent, we added fine grained logger names in 2.2)

**Comment by leobuskin** [comment]
Can fully confirm. I'm using APM 2.2.1, it doesn't work with Celery 4.1-4.2 (gevent) at all, Celery gets frozen immediately when a task is finished. That's very bad :( ready to assist in any ways to make this happen correctly

**Comment by beniwohli** [comment]
@leobuskin oh, that's interesting to know. By default, we create a background thread to send the data to the APM server. It's possible that this interacts badly with gevent. Can you try to use the non-threaded transport to see if that resolves the lockup? This is configurable via the [`transport_class`](https://www.elastic.co/guide/en/apm/agent/python/current/configuration.html#config-transport-class) setting, and you'd need to set it to `elasticapm.transport.http.Transport`.

**Comment by leobuskin** [comment]
@beniwohli that was the first thing I thought. Nope, it doesn’t help, already tried this transport, no effect

**Comment by solartune** [comment]
Hi @beniwohli, same thing in my project. When I use gevent after approx a minute (I suppose when the client sends data to a server) it just gets frozen. Without gevent everything works fine. Can confirm that changing the `transport_class` doesn't help

**Comment by beniwohli** [comment]
Thanks for the update @solartune! Looks pretty bad :( unfortunately, I wasn't able to reproduce this myself yet. If it isn't a lot of work, it would be fantastic if you or @leobuskin / @chripede could put together a minimal example app that reproduces the issue and put it into a gist.

I'll try to find some time to investigate the issue, but it's probably going to be a while. Sorry about that :(

**Comment by solartune** [comment]
Hey guys, I've solved the problem in my project. I've updated `gevent` to the latest version (1.3.5 at the moment) and now it works pretty fine! Before I had installed 1.2.2 version

**Comment by ciarancourtney** [comment]
@solartune relevant https://github.com/benoitc/gunicorn/issues/1194#issuecomment-416171718

**Comment by lemig** [comment]
Setting ELASTIC_APM_DISABLE_SEND=True worked for me.

**Comment by basepi** [comment]
Sounds like this is solved with newer versions of `gevent`. I'm going to close this, but if it's still an issue for anyone please comment and we'll re-open!
