### ISSUE TITLE
Instrumentation for PyMSSQL

### ISSUE THREAD

**Issue by eliasbrange** [elastic/apm-agent-python#239]
We use SQLAlchemy heavily and would like to instrument it. Might be able to find time to make an implementation myself if no one beats me to it.

https://pypi.org/project/SQLAlchemy/
http://www.sqlalchemy.org/

**Comment by beniwohli** [comment]
Hi @eliasbrange 

We already instrument SQL database calls on the DB-API2 level (basically, `cursor.execute` and friends), so DB calls from SQLAlchemy should be captured. Currently, this is implemented for PostgreSQL, MySQL, SQLite and soon PyODBC.

Do you think there would be a benefit in instrumenting SQLAlchemy directly over the current DB-API2-level instrumentation?

**Comment by eliasbrange** [comment]
Hmm. We are using http://pymssql.org/en/stable/ which might explain why I don't receive any captured spans then.

I honestly can't answer that. Just started playing around with APM a couple of days ago.

**Comment by beniwohli** [comment]
Yes, that would explain it :)

Adding support for additional database drivers is (usually) quite simple, see e.g. #238 for the PyODBC instrumentation that we are currently working on. The most difficult part is getting tests to work, as we like to spin up a database to test that we don't break the actual connection between the driver and the database.

I'll have a look how difficult it would be to get pymssql instrumented and tested :)

**Comment by eliasbrange** [comment]
Great! I'll try aswell. Got some of my DB calls in by instrumenting `("sqlalchemy.pool", "Pool.connect")`, but somehow misses some of my calls. Will have to check and see if there's another method inside there anywhere that gets called instead.

**Comment by eliasbrange** [comment]
```

**Comment by beniwohli** [comment]
@eliasbrange nice! However I'd prefer going forward with the current strategy of directly instrumenting the driver, instead of SQLAlchemy. That ensures that the instrumentation even works when using the driver directly, or a different ORM (e.g. Django's ORM).

e.g. something like this (watch out, completely untested as of now :D)

    from elasticapm.instrumentation.packages.dbapi2 import (ConnectionProxy,
                                                            CursorProxy,
                                                            DbApi2Instrumentation,
                                                            extract_signature)
    
    
    class PyMSSQLCursorProxy(CursorProxy):
        provider_name = 'pymssql'
    
        def extract_signature(self, sql):
            return extract_signature(sql)
    
    
    class PyMSSQLConnectionProxy(ConnectionProxy):
        cursor_proxy = PyMSSQLCursorProxy
    
    
    class PyMSSQLInstrumentation(DbApi2Instrumentation):
        name = 'pymssql'
    
        instrument_list = [
            ("pymssql", "connect"),
        ]
    
        def call(self, module, method, wrapped, instance, args, kwargs):
            return PyMSSQLConnectionProxy(wrapped(*args, **kwargs))

**Comment by eliasbrange** [comment]
That sure seems a lot more clever @beniwohli ...

**Comment by eliasbrange** [comment]
@beniwohli. How do I instrument the above instrumentation without adding it `elasticapm/instrumentation/register.py` after I have initialized APM with `apm = ElasticAPM(app, ...)`?

**Comment by soumithx** [comment]
is SQLAlchemy  DB Calls logging  available for apm?
