### ISSUE TITLE
Add support for distributed tracing

### ISSUE THREAD

**Issue by alvarolobato** [elastic/apm-agent-python#244]
Work is underway to add support for distributed tracing to the API/server: https://github.com/elastic/apm-server/issues/913 / https://github.com/elastic/apm-server/issues/968.
Support needs to be added to this agent too.

- [x] intake protocol v2 (#281)
- [x] `traceparent` header extract/inject functionality
- [x] update opbeans-python to include a distributed tracing call 
- [x] `transaction.span_count.total` (https://github.com/elastic/apm-server/issues/1241)
- [x] auto-instrument http module(s) to use extact/inject functionality

**Comment by Talador12** [comment]
What is the status on this item?

**Comment by alvarolobato** [comment]
We are actively working on it, it will come together with the implementation of the intake V2 protocol which needs to be in place for Distributed Tracing - #269
