### ISSUE TITLE
APM server not getting events from Django

### ISSUE THREAD

**Issue by kmcdeogracias** [elastic/apm-agent-python#256]
I setup the apm agent in my django app, verified that the configs are correct but I'm not getting any transactions saved in elastic.

I only get transactions if there's an error (404, 500). The python manage.py elasticapm test sends the event to apm server too.

My Django version is 1.9.7

Thanks!

**Comment by beniwohli** [comment]
@kmcdeogracias sorry for the long delay, didn't realize you opened this as well as the [topic](https://discuss.elastic.co/t/apm-server-not-getting-events-from-django/139709/2) in the dicuss forum :) as suggested there, you can enable logging of the apm-server to find out if there is a issue with parsing.

I'll close this in the mean time, feel free to re-open if necessary.
