### ISSUE TITLE
Is there a functionality for data recovery when client crashed before sending a log to server?

### ISSUE THREAD

**Issue by caerang** [elastic/apm-agent-python#273]
Hello friends,

I need a functionality of data recovery when failed to send a log to a server due to client crash or something.
In this case, I expect that the APM client send a log to server automatically when it restarts

I searched documentation and googled about this functionality, but I can't find anything useful information.

So, I wonder APM python agent has this functionality. Do you have plan for adding this feature?

If you already have this feature, where can I find information about that?

**Comment by beniwohli** [comment]
Hi @caerang. Currently, the agent drops data if it can't reach the APM Server. Implementing a disk-buffer or other similar methods to achieve high availability are currently not planned.

If this is a huge concern for you, you might want to run an instance of the APM Server on the same machine as the agent. The APM Server does have optional spooling to disk while it can't reach Elasticsearch.
