### ISSUE TITLE
How to get version matching information？

### ISSUE THREAD

**Issue by zhongzi** [elastic/apm-agent-python#287]
![image](https://user-images.githubusercontent.com/10124154/45479719-d5299c80-b779-11e8-818e-6e3288eb781c.png)
Thanks.

**Comment by beniwohli** [comment]
Hi @zhongzi. We recommend using the newest version of both the agent (3.0.1 at this point in time) and the APM server. 

If you still see HTTP 400 response codes, I recommend to have a look at the logs from apm-server. It will print an error message with the exact validation error.

For usage questions, we recommend to use our forum at https://discuss.elastic.co/c/apm
