### ISSUE TITLE
Instrumentation for MySQLConnector

### ISSUE THREAD

**Issue by trancee** [elastic/apm-agent-python#288]
I am using Elastic APM for the first time and I was surprised that it did not instrument the MySQL Connector database calls. After some investigation I figured out that there is no actual instrumentation for MySQL Connector. By studying the existing implementations of other drivers I quickly figured out how to implement one for MySQL Connector and it works.

But you put the bar quite high for some simple code contributions and I am not sure if it is worth the effort.

This is my `mysqlconnector.py` version:

```
from elasticapm.instrumentation.packages.dbapi2 import (
    ConnectionProxy,
    CursorProxy,
    DbApi2Instrumentation,
    extract_signature,
)


class MySQLConnectorCursorProxy(CursorProxy):
    provider_name = "mysql.connector"

    def extract_signature(self, sql):
        return extract_signature(sql)


class MySQLConnectorConnectionProxy(ConnectionProxy):
    cursor_proxy = MySQLConnectorCursorProxy


class MySQLConnectorInstrumentation(DbApi2Instrumentation):
    name = "mysql.connector"

    instrument_list = [("mysql.connector", "connect")]

    def call(self, module, method, wrapped, instance, args, kwargs):
        return MySQLConnectorConnectionProxy(wrapped(*args, **kwargs))
```

This works as far as I could see. Maybe some of the existing authors/contributors can pick this up and implement it properly with all the necessary test cases.

**Comment by beniwohli** [comment]
Hi @trancee! This looks great, thank you! You're quite right that for instrumentations, writing and running tests could be easier and better documented. I hope to work on that a bit in the future.

As for now, it would be great if you could open a pull request with this code and sign our CLA (if this is your first contribution to an Elastic project). This would allow us to build a complete instrumentation including tests based on your code.

I can't promise when I'd get around to whip up the tests, but it'll probably be at least a few weeks.

**Comment by lreuven** [comment]
[fixed & supported](https://github.com/elastic/apm-agent-python/pull/289)
