### ISSUE TITLE
Creating instrumented module

### ISSUE THREAD

**Issue by tflorac** [elastic/apm-agent-python#290]
Hi,
I'm trying to create a new module to track my Chamelon templates, using Jinja2 module as template.
Everything seems OK, but I have two questions:
- how can I remove traceback from captured spans? Using "leaf=True" in capture_scan call doesn't seems to be efficient...
- I set "RENDER" as span's "name" and use my template filename as span's "context". How can I get this context in Kibana's APM UI?

Many thanks for any answer or advise...
Best regards,
Thierry

**Comment by beniwohli** [comment]
Hi @tflorac 

sorry for the long answer time, I was on vacation. Unfortunately, there isn't currently a way to indicate in `capture_span` to not collect a stack trace. However, this is an interesting idea, I'll look into implementing it!

The span context isn't currently exposed in the APM UI. We are currently working on making that a better experience and hope to have something in one of the coming releases. For now, I'd suggest to include the filename in the span name for better visibility.

**Comment by basepi** [comment]
Hello @tflorac! I'm going through and cleaning up older issues -- are you still interested in the ability to not capture the stack trace with `capture_span`? If so, would you mind opening a new issue with that feature request? I'm going to close this issue for now.
