### ISSUE TITLE
Disabling instrumentation of a specific type

### ISSUE THREAD

**Issue by chris-erickson** [elastic/apm-agent-python#296]
I have some instrumentation I'd rather not have automatically - is there any way to disable it for one type?

**Comment by beniwohli** [comment]
Hi @chris-erickson 

there is an undocumented way to disable instrumentation of certain modules, using environment variables. Here's the code that does that:

https://github.com/elastic/apm-agent-python/blob/27aa3284063eea671643768854e7fe662059739e/elasticapm/instrumentation/packages/base.py#L50-L53

You can find the `name` in the `Instrumentation` classes defined here: https://github.com/elastic/apm-agent-python/tree/master/elasticapm/instrumentation/packages

So to e.g. disable psycopg2 instrumentation, setting the environment variable `SKIP_INSTRUMENT_PSYCOPG2` to any value should work.

As mentioned, this is undocumented and hence subject to change. In fact, we are investigating a more robust way to register and de-register instrumentations, but there is no timeline for that at the moment.

**Comment by chris-erickson** [comment]
Thank you for the quick response, I'll give that a try.  FWIW, the Node version of providing the module names works acceptably, if a Python equivalent is possible.

**Comment by chris-erickson** [comment]
Let me elaborate a bit more, to see if perhaps I'm going about this wrong.  I have a particular bit of `requests` code that makes a `GET` to a URL but includes sensitive PII and authorization data in it.  Per the code, it looks like the URL is directly added as part of the span: https://github.com/elastic/apm-agent-python/blob/27aa3284063eea671643768854e7fe662059739e/elasticapm/instrumentation/packages/requests.py#L31

Can a processor post-process data that makes it's way into `context.url` in a span?  The docs state `A processor is a function that takes a client instance as well as an event (an error or a transaction)` so I initially disregarded this as I assumed a span is not an error or transaction.

**Comment by beniwohli** [comment]
the span can be found in `transaction["spans"]`, which you can modify with a processor.

This will change a bit in version 4 of the agent, which will be released together with Elastic Stack 6.5. Spans will be piped through processors the same as transactions and errors. That means that processors need to be adapted a bit for that release.

**Comment by basepi** [comment]
I'm going to close this issue as it's fairly stale. Please comment if you have any more questions about processors!
