### ISSUE TITLE
Allow configuration of SANITIZE_FIELD_NAMES and SANITIZE_VALUE_PATTERNS.

### ISSUE THREAD

**Issue by manterfield** [elastic/apm-agent-python#298]
Currently the only way I can see to extend the fields and values that are sanitized is to roll my own processor as described on the [santizing data](https://www.elastic.co/guide/en/apm/agent/python/current/sanitizing-data.html) page of the docs.

These two values are set to two hardcoded lists in [processors.py](https://github.com/elastic/apm-agent-python/blob/27aa3284063eea671643768854e7fe662059739e/elasticapm/processors.py#L20-L24)

The Java APM agent allows users to [set a value for field names](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-sanitize-field-names) via `sanitize_field_names`.

This also has a more comprehensive default list and allows patterns rather than straight string matches. 
**Java Agent default:**
```
(?i)password, (?i)passwd, (?i)pwd, (?i)secret, (?i)token, (?i)*key, (?i)*token, (?i)*session*, (?i)*credit*, (?i)*card*, (?i)authorization, (?i)set-cookie
```
**Python Agent default:**
```
"authorization", "password", "secret", "passwd", "token", "api_key", "access_token", "sessionid"
```

I'd be more than happy to make the contribution myself, though I'd like to establish a consensus first on what extended defaults should look like and if pattern support should be included.

**Comment by beniwohli** [comment]
Hi @manterfield. This suggestion makes a lot of sense! 

Note however that the Java agent doesn't use regular expressions, but its own matching rules that only support "`*`" and optional case insensitiveness. We used [`fnmatch`](https://docs.python.org/3.4/library/fnmatch.html) for some settings, but ideally we'd synchronize the exact matching format amongst all the agents.

In fact, that's something we just recently discussed at a meeting of all agent developers and came to the conclusion to follow Java's lead.

**Comment by beniwohli** [comment]
Nobody is actively working on it at the moment, so feel free to take a stab at it! 

We discussed some implementation strategies internally. While it seems to make sense for the Java agent to implement `WildcardMatcher`, my gut feeling is that in the case of Python, we'd have a hard time beating the performance of the highly optimized regex engine. So it would probably make a lot of sense to translate our matching format to a regex (basically replacing `*` with `.*`) and use that for matching :)

**Comment by basepi** [comment]
As of https://github.com/elastic/apm-agent-python/pull/860 we have support for `sanitize_field_names`. I don't think we currently have plans for pattern matching values, but if that's still something that interests you, can you please open a new issue just for that enhancement request?

Thanks!
