### ISSUE TITLE
No tracing happening from AWS Lambda

### ISSUE THREAD

**Issue by babyhuey** [elastic/apm-agent-python#320]
I am trying to run elasticapm python version 3.0.3, with apm-server version 6.4.2 and I am not getting any tracing information from Django on the APM server.

I have the correct settings in INSTALLED_APPS and also in MIDDLEWARE_CLASSES.

I have the same setup running on other service on Docker and they are working great.

I can get errors through the APM, just no Middleware Tracing is happening. 

elasticapm check: 

```
 Service name is set, good job!
  * optional SECRET_TOKEN not set

SERVER_URL http://xxxxxxxxxxxxxxxx:8200 looks fine

DEBUG mode is disabled! Looking good!

Tracing middleware is configured! Awesome!

Looks like everything should be ready!
```

elasticapm test:
```
Trying to send a test error to APM Server using these settings:
SERVICE_NAME:   xxxxxxxxx
SECRET_TOKEN:   None
SERVER:         http://xxxxxxxxxxxxxxx:8200
Success! We tracked the error successfully! You should be able to see it in a few seconds at the above URL
```
Python: 2.7
Deployment: Zappa

**Comment by beniwohli** [comment]
Hi @babyhuey 

Lambda is not an environment we support right now. The main issue is that the agent queues data up before sending it to the APM Server, to limit resource usage. We are looking into ways how to send data from lambda functions to the APM Server without compromising performance, but I can't give a time line for when we will have a solution for this.

Another Zappa-specific issue that we noticed is that Zappa does not call `response.close()`, which it should according to the WSGI standard. I will open an issue in the Zappa repo about this

**Comment by babyhuey** [comment]
Ah, well that would be my issue then :(

Is it documented anywhere that Lambda is not currently supported? 

I guess I have no choice but to wait until support is added.

Thanks!

**Comment by youcandanch** [comment]
@beniwohli Any update on this? Looks like there's been at least some discourse on Zappa w/r/t it:
https://github.com/Miserlou/Zappa/issues/1723
https://github.com/Miserlou/Zappa/pull/1724

I'm happy to push on the Zappa side if it looks like there's something coming down the pipe for APM. Thanks!
