### ISSUE TITLE
Are there any apm-agent-python that support Odoo?

### ISSUE THREAD

**Issue by guntursp** [elastic/apm-agent-python#327]
Hi,
We'd like to monitor our Odoo instance with Elastic APM. But still couldn't find the apm-agent for Odoo. Could you please let me know if any? or are there any possibilities to create the agent based on the "apm-agent-python"?

Appreciate the feedback.

Regards,
-gs

**Comment by beniwohli** [comment]
Hi @guntursp 

sorry for the long delay in answering this. We don't currently plan to add native support for Odoo. However, it is relatively straight forward to implement your own integration. I wrote a blog post a while ago that goes through the details, you can find it here: https://www.elastic.co/blog/creating-custom-framework-integrations-with-the-elastic-apm-python-agent

**Comment by sebastienbeau** [comment]
Hi @guntursp 

I am currently working on an implementation of elastic APM for odoo.
See the project here : https://github.com/akretion/odoo-elasticapm
It's in work in progress but we will go in production really soon.

When the project will be really mature we will propose it into the Odoo Community Association (OCA) https://github.com/OCA

Hope this can help
