### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'tell'

### ISSUE THREAD

**Issue by toughrogrammer** [elastic/apm-agent-python#348]
I'm using 4.0.1 version.
Exceptions are raised from `elasticapm.transport.base.queued_data_size`

Here is last trace.

```
        if f:
            # return size of the underlying BytesIO object if it is compressed
            return f.fileobj.tell() if hasattr(f, "fileobj") else f.tell()
        return 0
```

<img width="2298" alt="screen shot 2018-11-28 at 12 23 39 pm" src="https://user-images.githubusercontent.com/1473538/49126977-0a6d7180-f309-11e8-9c4b-85eeff62614e.png">
<img width="2252" alt="screen shot 2018-11-28 at 12 24 41 pm" src="https://user-images.githubusercontent.com/1473538/49126979-0ccfcb80-f309-11e8-8c30-90184abd76bf.png">

**Comment by toughrogrammer** [comment]
<img width="902" alt="screen shot 2018-11-28 at 3 03 47 pm" src="https://user-images.githubusercontent.com/1473538/49132259-dac96400-f31e-11e8-8006-c0688c41f29f.png">

It looks like f is gzip instance. And I test below code but there is no exception.

```python
import gzip

from elasticapm.utils.compat import BytesIO

a = BytesIO()
print(a.tell())

b = gzip.GzipFile(fileobj=BytesIO(), mode="w", compresslevel=1)
print(b.fileobj.tell())
print(b.tell())
```

**Comment by beniwohli** [comment]
Hi @toughrogrammer. Thanks for the bug report! How often does this happen? Very frequently or only seldom?

I have a suspicion that it could be a threading bug: `f` could be reset by another thread between the `if f` and the next line.

**Comment by toughrogrammer** [comment]
Only seldom. 50 occurance while processing more than 100k transactions

**Comment by ciarancourtney** [comment]
I've seen one example of this too, in a celery task that runs every 1 minute

**Comment by beniwohli** [comment]
@ciarancourtney how do you run celery? Just normal worker processes or something like Eventlet?

**Comment by ciarancourtney** [comment]
> @ciarancourtney how do you run celery? Just normal worker processes or something like Eventlet?

Just normal worker processes, celery 3.x

**Comment by axw** [comment]
GzipFile.fileobj will be set to None when the GzipFile is closed, which is done by Transport.flush. I suspect that the flush timer thread is kicking in between `self.queued_data.write` and `queue_size = self.queued_data_size` inside `Transport.queue`.

I think if you move `queue_size = self.queued_data_size` up inside the `with self._queue_lock` this can be avoided. The `Transport.queue_data_size` property method should probably also account for fileobj possibly being None.

**Comment by toughrogrammer** [comment]
@beniwohli Sorry... It's too busy now. I will try later.

**Comment by ciarancourtney** [comment]
@beniwohli I have it deployed to staging since yesterday, will keep you updated.

/remind me to check in 1 month

**Comment by rafaelsierra** [comment]
> @ciarancourtney how do you run celery? Just normal worker processes or something like Eventlet?

I was having issues using Python 2 and Gunicorn with eventlet worker class (specifically `AttributeError: 'ChilledQueue' object has no attribute 'not_full'`).

Is it the case that eventlet is not supported? (Changing to gevent fixes the problem)

**Comment by beniwohli** [comment]
@rafaelsierra can you open a new issue with this? As far as I can tell, this seems unrelated.
