### ISSUE TITLE
Connection hangs in CLOSE_WAIT state

### ISSUE THREAD

**Issue by tamoorqc** [elastic/apm-agent-python#349]
Socket is in CLOSE_WAIT state and will never be closed (until restart `app`). 

Following is output when I run apm server:
```
$ lsof -i -n -P | grep TCP | grep 8200
apm-serve 68586 QTS  7u  IPv4 0xcfb8bd22    0t0  TCP 127.0.0.1:8200 (LISTEN)
```

After I run the app and log an error. The same command gives following:
```
$ lsof -i -n -P | grep TCP | grep 8200
apm-serve 68586 QTS    7u  IPv4 0xcfb8bd22     0t0  TCP 127.0.0.1:8200 (LISTEN)
apm-serve 68586 QTS    8u  IPv4 0xcfb8bd22      0t0  TCP 127.0.0.1:8200->127.0.0.1:50305 (ESTABLISHED)
python    68860 QTS   19u  IPv4 0xcfb8bd22      0t0  TCP 127.0.0.1:50305->127.0.0.1:8200 (ESTABLISHED)
```

After a while the output is following:
```
$ lsof -i -n -P | grep TCP | grep 8200
apm-serve 68586 QTS    7u  IPv4 0xcfb8bd22     0t0  TCP 127.0.0.1:8200 (LISTEN)
python    68860 QTS   19u  IPv4 0xcfb8bd22      0t0  TCP 127.0.0.1:50305->127.0.0.1:8200 (CLOSE_WAIT)
```

For every error log there is process which hangs in CLOSE_WAIT state.

**Comment by beniwohli** [comment]
Hi @tamoorqc 

we use urllib3 for making HTTP requests to the APM Server. urllib3 uses a connection pool and keeps the sockets around for some time, so seeing a limited number of sockets in CLOSE_WAIT is expected. But if the number of connections in this state grows unbounded, then we have a problem. I can only see one socket in your example. Do you see many more after the app runs for some time?

**Comment by beniwohli** [comment]
I'll close this as I'm unable to replicate behaviour outside of the ordinary. Please re-open if you encounter it again.
