### ISSUE TITLE
GDPR: obfuscating user data

### ISSUE THREAD

**Issue by chubz** [elastic/apm-agent-python#358]
**Is your feature request related to a problem? Please describe.**
I've noticed that there is a User tab in the APM that is related to user information: id, username, email. How could this be avoided. Things like IP addresses of requests, user information etc. This is something that is evaluated against GDPR requirements.

**Describe the solution you'd like**
I'd like this to be something that can be added to the settings, like a pseudoanonymization settings that excludes fields/tabs or data from being gathered.

**Describe alternatives you've considered**
I'm not clear as to what would be an alternative to not collecting this data, maybe post processing in the elasticsearch? Is this a viable alternative?

**Comment by beniwohli** [comment]
Hi @chubz 

thanks for opening an issue, this is a very valid concern of course. The best way to achieve this at the moment is to write a processor that applies pseudonymization according to your needs or removes the data completely. See our documentation on [processors](https://www.elastic.co/guide/en/apm/agent/python/current/sanitizing-data.html). Your processor would need to operate on both `TRANSACTION` and `ERROR` types, and the user data is in `context.user`.

Does that cover your needs?

**Comment by chubz** [comment]
Hi @beniwohli thanks for a prompt answer.
It seems I lost sight of that part of docs when doing a basic integration.
I still hope this part will be as transparent as possible and I'll try to evaluate and test these processors and how they can affect the data gathered.

I hope this issue steers more people towards these docs.

**Comment by beniwohli** [comment]
@chubz let me know how it goes. I'll close this issue in the meantime.

If there's anything we can do to make the docs more obvious, feel free to open another issue!
