### ISSUE TITLE
Not stable for transporting data to APM server

### ISSUE THREAD

**Issue by toughrogrammer** [elastic/apm-agent-python#370]
I tried v4.0.3 and it looks like agent wasn't stable enough. Red rectangle area was time range of v4.0.3 and I downgraded to v3.0.4.

<img width="1086" alt="screen shot 2018-12-25 at 12 48 52 am" src="https://user-images.githubusercontent.com/1473538/50403135-975bfb80-07df-11e9-80a5-3e18771c4942.png">

I didn't change any configurations. So, almost configuration is defualt value.

**Comment by beniwohli** [comment]
Thanks for the report!

Do you see any indications of what could be wrong in the apm-server logs or the logs of your application?

**Comment by toughrogrammer** [comment]
I'm sorry but that's really difficult. I'm tracing many services with elastic apm which version is 3.0.4, and as I reported before, there are so huge amount of warning log. 

```
{"type":"mapper_parsing_exception","reason":"object mapping for [context.service] tried to parse field [service] as object, but found a concrete value"}
```

There are too many these warning log, I cannot retrieve any other logs. Almost 10MB of there warning logs are generated in less than 5 seconds.

**Comment by toughrogrammer** [comment]
As you know, it's hard to just upgrade all of agent's version to 4.0.3.

**Comment by beniwohli** [comment]
OK, thanks for the update! The `context.service` issue should be gone in 4.0.3, but I see how it could be difficult to upgrade a whole lot of installations at the same time.

Would it be helpful to you if I backported https://github.com/elastic/apm-agent-python/pull/367 to the 3.x branch? Then you should be able to upgrade to 3.0.5, wait a day or so for the dynamic mapping issue to take care of itself, and then try to upgrade to 4.0.3 again.

I can ship a 3.0.5 with the backport in about an hour or so

**Comment by toughrogrammer** [comment]
Good. I will try upgrade to v3.0.5 and report if there is something weird logs.

**Comment by beniwohli** [comment]
@toughrogrammer 3.0.5 with the boto3 fix is now on PyPI: https://pypi.org/project/elastic-apm/3.0.5/

**Comment by toughrogrammer** [comment]
Thank you. Merry Christmas!

**Comment by beniwohli** [comment]
@toughrogrammer were you able to solve your issue with these updates? I'm still a bit concerned with the graph you posted and want to make sure it is not a deeper problem with the new transport protocol we introduced with 4.0.

**Comment by beniwohli** [comment]
Closing this for now. Feel free to re-open if this problem reoccurs!
