### ISSUE TITLE
move context.url to context.http.url

### ISSUE THREAD

**Issue by graphaelli** [elastic/apm-agent-python#393]
While investigating the impact of https://github.com/elastic/apm-server/issues/411, I realized instrumentation of  [httplib3](https://github.com/elastic/apm-agent-python/blob/d215428603c0aaed3de9cc3fdb2fcb3f4583ad85/elasticapm/instrumentation/packages/urllib3.py#L46) and [requests](https://github.com/elastic/apm-agent-python/blob/d215428603c0aaed3de9cc3fdb2fcb3f4583ad85/elasticapm/instrumentation/packages/requests.py#L31) creates `context.url`.  By convention, that should have been going to `context.http.url`.  If the referenced issue is implemented, the convention will be codified and this information will start to be dropped, so let's move it either way.

**Comment by beniwohli** [comment]
Great catch! Implemented in #394
