### ISSUE TITLE
Showing logs in terminal while executing flask server.

### ISSUE THREAD

**Issue by barudwale20** [elastic/apm-agent-python#418]
I am using`ElasticAPM` with `flask server`.

I did import library `elastic-apm (v3.0.0)`

while I am importing `ElasticAPM` and initializing it using:

`apm=ElasticAPM(app, logging=True)`

The supervisor logs (hits to API endpoints, errors etc.) are not visible in the terminal when I am testing it using debug mode on the terminal (Ubuntu 18) while running flask server. The same issue is being faced when I am setting logging levels other than 0 (NOTSET).

While I am keeping `logging=False` , I am able to see the logs on the terminal. How can I see the logs while `logging=True`?

I have seen this in `v4.1.0` also.
Please add/modify the feature in order to get the logs on the terminal.

**Comment by beniwohli** [comment]
Hi @barudwale20 

sorry for the late answer. Do you have any other logging configuration set up? If so, can you paste it here?

**Comment by basepi** [comment]
I created some [troubleshooting docs](https://www.elastic.co/guide/en/apm/agent/python/master/troubleshooting.html) that should help with this. `logging=True` actually has nothing to do with the agent's logs. Rather, that's for shipping logs from your app to elasticsearch.
