### ISSUE TITLE
Span.start.us field is empty

### ISSUE THREAD

**Issue by ifmusic** [elastic/apm-agent-python#421]
Hi,
I'm trying to get performance data on an django app. This little app is making psql requests and SOAP requests (using Zeep). Transaction data gets recieved, with info on spans and duration times but the start offset is null.

![image](https://user-images.githubusercontent.com/919625/54171362-d140b380-4458-11e9-8f3a-cc83bb07bbce.png)

Other Python Apps are sending data correctly to the same elastic apm server.

**To Reproduce**
Default config and pip install APM Agent (4.0.3) and send data to the APM Server.

**Expected behavior**: ...
Start times set correctly.

**Environment (please complete the following information)**
- OS: Ubuntu 16.04 LTS
- Python version: 3.5.2
- Framework and version [e.g. Django 2.1]: 2.0.3
- APM Server version: 6.5.2
- Agent version: 4.0.3

**Additional context**

Other Python Apps are sending data correctly to the same elastic apm server.

- Agent config options 
```
ELASTIC_APM = {
  'SERVICE_NAME': 'XXXXXXX',
  'SERVER_URL': 'http://10.20.99.XX:8200',
  'DEBUG': True,
}
```

- `requirements.txt`:
```
> appdirs==1.4.3
> attrs==19.1.0
> cached-property==1.5.1
> certifi==2018.8.13
> chardet==3.0.4
> defusedxml==0.5.0
> Django==2.0.3
> djangorestframework==3.8.2
> elastic-apm==4.0.3
> idna==2.7
> isodate==0.6.0
> lxml==4.2.5
> psycopg2==2.7.5
> pycrypto==2.6.1
> PyPDF2==1.26.0
> pytz==2018.5
> raven==6.9.0
> requests==2.19.1
> requests-toolbelt==0.9.1
> six==1.12.0
> urllib3==1.23
> zeep==3.2.0
>  
```
>

**Comment by beniwohli** [comment]
Hi @ifmusic 

With the release of version 4.0 of the agent, `span.start` is not set anymore. Instead, the `@timestamp` field is set to the correct span start time, independent of the start time of the related transaction. This simplifies custom aggregations on spans a lot.
