### ISSUE TITLE
[META 352] AWS Lambda support

### ISSUE THREAD

**Issue by bobthemighty** [elastic/apm-agent-python#428]
I'm currently building a serverless architecture and was hoping to use elastic cloud as a one-stop repository for logs and metrics. Per elastic/apm-agent-python#320 it seems that Lambda is not a supported environment for Elastic-APM.

I'd be happy to put in some work to make this happen, but I'm not entirely clear on where the problems lie. Is there a reason why this is more complex than calling `collect` on the  metric repository and `flush` on the transport? 

If I had a MetricRegistry with a collect_interval of 0ms, and an unthreaded transport that flushed only on demand, I could flush explicitly at the end of the lambda invocation. It would be simple to extend that to a decorator that flushed on exit from the wrapped function.
Is this an enormous simplification of the requirements?

**Comment by beniwohli** [comment]
Hi @bobthemighty. Yes, that would probably work, however it might incur quite a heavy overhead as basically every lambda invocation would result in an HTTP request to your APM Server. That might be ok if you have relatively long-running lambda functions, but for very short running functions (< 100ms or thereabout), the overhead might start to dominate the actual execution time.

I'm not very familiar with how exactly the life cycle of an invoked lambda function is, but if they shut down the interpreter cleanly after the invocation, you might not even have to flush the queue, as we use [`atexit`](https://docs.python.org/3/library/atexit.html) to flush the queue on shutdown.

**Comment by beniwohli** [comment]
That goes in the general direction of what we think might be a workable solution, basically use CloudWatch or possibly SQS as a transport.

Note however that the events that the agent generates are not elasticsearch documents. They first need to be processed by the APM Server, which turns them into ES documents. 

If you want to write your own transport, note that we just merged a pretty large change to the inner workings of transports (#411). This shouldn't make it much more complicated to implement such a transport, though (we might have to move the `init_buffer` inner function to a method though, so you can avoid the GZip compression).

**Comment by bobthemighty** [comment]
> Note however that the events that the agent generates are not elasticsearch documents. They first need to be processed by the APM Server, which turns them into ES documents.

Roger. Is the format you're writing identical between apm-node/python/go, or is there additional language-specific munging? I'm thinking that if we were to write to CloudWatch, and the format is the same, then it's not too hard to provide a library for parsing those logs out and forwarding them to an APM instance.

> note that we just merged a pretty large change to the inner workings of transports (#411). 

What Transport methods other than "send" are relied on by client code? I can see that there's a queue method that's public-looking, but not sure where it's actually in use. I'm wondering how much of the transport infrastructure is actually relevant to a stdout implementation.

Thanks for the prompt reply, btw. :+1:

**Comment by beniwohli** [comment]
The API between the agent and APM Server is standardized and all agents use the same (it's defined as JSONSchema here: https://github.com/elastic/apm-server/tree/master/docs/spec).

For implementing your own transport, ideally you'd only need to override `send(data)`. `data` however is a gzip encoded blob, which is less than ideal for printing to stdout. So you'd either need to unzip it again, which is wasteful, or have a way to disable gzip compression in the first place. If it's ok with you, I'd recommend to unzip it for now, and if this turns out to be a workable solution, we can add a hook to disable gzip compression.

**Comment by basepi** [comment]
Ref https://github.com/elastic/apm/issues/352

**Comment by basepi** [comment]
We're going to try to get an MVP of this going soon -- it will not be using lambda extensions initially, but will just be sending directly to the configured APM server from the lambda function itself. We know this will not be useful in all cases as the overhead will be dramatic, especially for short-running lambda functions. But it will be a first step toward a better implementation using extensions.
