### ISSUE TITLE
AttributeError: 'ChilledQueue' object has no attribute 'not_full'

### ISSUE THREAD

**Issue by ddemid** [elastic/apm-agent-python#436]
Client v.4.2.0 fails in celery 4.0 with `AttributeError: 'ChilledQueue' object has no attribute 'not_full'`

`File "/usr/local/lib/python3.5/site-packages/elasticapm/transport/base.py", line 331, in put`

**Comment by beniwohli** [comment]
Hi @ddemid. Do you per chance use eventlet? They monkeypatch `queue.Queue` which makes our subclass explode. I'm already working on a fix in #435

**Comment by ddemid** [comment]
Hi @beniwohli. Yes! Thank you very much for explanation.

**Comment by beniwohli** [comment]
@ddemid I just released version 4.2.1 of the agent which contains a fix for this issue.

**Comment by ddemid** [comment]
@beniwohli Thank you!
