### ISSUE TITLE
apm agent v. 4.2.1 only collects metrics, not transactions, for flask >= 1.x

### ISSUE THREAD

**Issue by digressionary** [elastic/apm-agent-python#440]
**Describe the bug**: ...

The APM agent for python + flask reports only metrics, not transactions or spans or errors, for flask >= 1.x

Setup:
APM Server: v 6.6.0
python v 3.7.2
flask v 1.0.2
python apm agent v 4.2.1 (latest)

**To Reproduce**

1. follow the docs here: https://www.elastic.co/guide/en/apm/agent/python/3.x/configuration.html

2. set up app as follows:
`app.config['ELASTIC_APM'] = {
    'SERVICE_NAME' : os.getenv('ELASTIC_APM_SERVICE_NAME'),
    'SECRET_TOKEN' : os.getenv('ELASTIC_APM_TOKEN'),
    'SERVER_URL' : os.getenv('ELASTIC_APM_SERVER_URL'),
    'CAPTURE_BODY' : 'all',
    'TRANSACTION_SAMPLE_RATE' : os.getenv('ELASTIC_APM_TRANSACTION_SAMPLE_RATE')
}
apm = ElasticAPM(app)`

3. make a request to the app and look in the apm-* index for new records

**Expected behavior**: ...
Metrics, transactions, spans and errors all received and logged

**Environment (please complete the following information)**
- OS: mac osx Sierra / docker desktop with k8s v 1.13.0
- Python version: 3.7.2
- Framework and version Flask 1.0.2
- APM Server version: 6.6.x
- Agent version: 4.2.1

**Additional context**

It works fine if I downgrade my Flask to < 1.x (e.g. 0.11)
Here is an example of the type of document that IS created:
[bug_report_example_doc.txt](https://github.com/elastic/apm-agent-python/files/3014824/bug_report_example_doc.txt)

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    config as above
    ```
  </details>
- `requirements.txt`:
  <details>
    <summary>Click to expand</summary>

    ```
    Flask flask-cors nose -e git+https://github.com/vemba/m3u8.git@ad-marker-support#egg=m3u8 redis gunicorn>=19,<20 Flask-PyMongo boto3 requests elastic-apm[flask]
    ```
  </details>

**Comment by ramshaw888** [comment]
Looks like a duplicate of #439 

I've been running this with flask==1.0.2 and can see it reporting data correctly. One thing that tripped me up a while ago is that when flask debug mode is on, the agent will not report transactions. See https://github.com/elastic/apm-agent-python/blob/master/elasticapm/contrib/flask/__init__.py#L180

**Comment by digressionary** [comment]
Thank you!!! Turning off debug mode did the trick

**Comment by michaelbukachi** [comment]
Thanks @ramshaw888. Been trying to solve this issue the whole day. Turning off debug mode worked like a charm.
