### ISSUE TITLE
NO_PROXY not passed

### ISSUE THREAD

**Issue by kh2901** [elastic/apm-agent-python#458]
The environment variable NO_PROXY is not processed. An APM server in front of a proxy is therefore not found, after a while you get http connection error. Only the environment variables HTTP_PROXY and HTTPS_PROXY are processed.  I`m using flask and the environment variables HTTP & HTTPS_PROXY are needed for oauth.

**To Reproduce**

1. Define APM Server in front of a Proxy
2. Define HTTP_PROXY and HTTPS_PROXY environment variable
3. Define NO_PROXY
4. Try to initiate app
5. Seconds after initate you get an HTTP Connection error.

**Expected behavior**: 
Check if IP or URL is defined in NO_PROXY, maybe part of an URL for wildcard usage.

Change this [line](https://github.com/elastic/apm-agent-python/blob/b3b0ba42c260935b1d3c3a1db244c1ebc14d40ad/elasticapm/transport/http.py#L62) and add a second condition.

**Environment (please complete the following information)**
- OS: [e.g. Linux]
- Python version: 3.6.8
- Framework and version [e.g. Django 2.1]: Flask 1.0.2
- APM Server version: 7.0.0
- Agent version: 4.2.2

**Comment by beniwohli** [comment]
Hi @kh2901 

thanks for raising this issue! `NO_PROXY` is indeed not supported at the moment. But it should be relatively easy to add, leveraging [`proxy_bypass_environment`](https://github.com/python/cpython/blob/da0847048aa7f934573fa449cea8643def056aa5/Lib/urllib/request.py#L2486-L2492) from `urllib` here: https://github.com/elastic/apm-agent-python/blob/b3b0ba42c260935b1d3c3a1db244c1ebc14d40ad/elasticapm/transport/http.py#L61-L65

I probably won't have time for this in the next few days. If you're up for it, a pull request would be awesome. A test would probably look similar to the tests for [`HTTP(S)_PROXY`](https://github.com/elastic/apm-agent-python/blob/90f3eac222f163a12d6fd2ef172710eb361ba470/tests/transports/test_urllib3.py#L101-L116). You set values for both `HTTP_PROXY` and `NO_PROXY`, and check if 1) `isinstance(transport.http, urllib3.PoolManager)` if the given URL matches `NO_PROXY` and 2) `isinstance(transport.http, urllib3.ProxyManager)` if it doesn't.

**Comment by akhmadMizkat** [comment]
Hi, any updates on this issue?

**Comment by beniwohli** [comment]
@akhmadMizkat not yet unfortunately. We have a few more pressing things to take care of, I hope to get to these smaller issues afterwards.
