### ISSUE TITLE
`check` cmd output differs from documentation. 

### ISSUE THREAD

**Issue by simitt** [elastic/apm-agent-python#46]
Running `python manage.py elasticapm check` returns an error if no `Secret_Token` is configured. Documentation states that configuration is optional.

**Comment by beniwohli** [comment]
Good catch. I wonder if we should change this to instead issue a warning if a secret token is set, but the server URL isn't https.

**Comment by simitt** [comment]
I think a warning would be a good idea, in any case as soon as the server only uses http to indicate there is an insecure connection.
