### ISSUE TITLE
Capture Python runtime metrics 

### ISSUE THREAD

**Issue by nehaduggal-zz** [elastic/apm-agent-python#460]
Python agent to capture runtime metrics to help visualize the impact of underlying infrastructure in context of the application.

Metrics to be captured by the Python agent:
- Garbage collection
- Memory usage(existing memory usage graph on the apm-contrib dashboard)
- I/O
- Thread count (Gauge)
- Context switches (Counter)
       - Voluntary
       - Involuntary
- Open file handles (Gauge)

APM Meta issue: elastic/apm#73

A dashboard should be created in apm-contrib for these metrics

**Comment by lreuven** [comment]
@beniwohli can we close?

**Comment by lreuven** [comment]
closing

**Comment by lreuven** [comment]
zube is messing w/m
