### ISSUE TITLE
Capture Python  request.urlopen runtime metrics

### ISSUE THREAD

**Issue by EricYqd** [elastic/apm-agent-python#462]
Python agent can capture  requests.get /  requests.post runtime metrics . but  request.urlopen can not capture  runtime metrics
Thanks

**Comment by beniwohli** [comment]
Hi @EricYqd 

I assume you mean `urllib2.urlopen()` (Python 2) and `urllib.request.urlopen` (Python 3) from the standard library? We do indeed not currently instrument these calls, but it's a good idea to add them :)

**Comment by EricYqd** [comment]
Thank you for your quick feedback and look forward to python agent improvement.

在 2019-04-23 20:25:47，"Benjamin Wohlwend" <notifications@github.com> 写道：


Hi @EricYqd

I assume you mean urllib2.urlopen() (Python 2) and urllib.request.urlopen (Python 3) from the standard library? We do indeed not currently instrument these calls, but it's a good idea to add them :)
