### ISSUE TITLE
Parent DroppedSpan causing AttributeError

### ISSUE THREAD

**Issue by nchudleigh** [elastic/apm-agent-python#468]
**Describe the bug**: ...

A parent span being a DroppedSpan is causing an AttributeError to be called within end_span.  I cannot find the reason why.  Randomly started happening at 4am on a Sunday (in other words not connected to rollout).  Happened across many different task contexts.  Believe it was connected to some connection issues with the instrumented code.  In anycase the code should protect against this type of problem

Here is the trace from Sentry:
![image](https://user-images.githubusercontent.com/5580824/56857022-c2915b80-6935-11e9-8153-4451793619b9.png)

**To Reproduce**

I have not been able to reproduce, but changing the check to a `hasattr(parent, "id")` should be sufficient.

**Expected behavior**: ...

Don't throw errors when ending span.

**Environment (please complete the following information)**
- OS: [e.g. Linux] Ubuntu
- Python version: 2.7
- Framework and version [e.g. Django 2.1]: Flask 0.12
- APM Server version: 6.6.1
- Agent version: 4.1.0

**Additional context**

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```python
    TRANSACTIONS_IGNORE_PATTERNS = ["^OPTIONS "]
    SERVER_URL = "http://apm:8200"
    ```
  </details>
- `requirements.txt`:
  <details>
    <summary>Click to expand</summary>

    ```
    elastic-apm==4.1.0
    Flask==0.12
    ```
  </details>

**Comment by nchudleigh** [comment]
Heres an example of the fix that I mentioned in the description.  Obviously this is a result of something off further up the chain that someone more experienced should diagnose.  But this is a good quick fix for that gnarly one-liner.
```python
    def to_dict(self):
        if self.parent_span_id:
            parent_id = self.parent_span_id
        elif self.parent and hasattr(self.parent, "id"):
            parent_id = self.parent.id
        else:
            parent_id = self.transaction_id

        result = {
            "id": self.id,
            "transaction_id": self.transaction.id,
            "trace_id": self.transaction.trace_parent.trace_id,
            # use either the explicitly set parent_span_id, or the id of the parent, or finally the transaction id
            "parent_id": parent_id,
            "name": encoding.keyword_field(self.name),
            "type": encoding.keyword_field(self.type),
            "timestamp": int(self.timestamp * 1000000),  # microseconds
            "duration": self.duration * 1000,  # milliseconds
        }
```

**Comment by beniwohli** [comment]
Hi @nchudleigh 

thanks for opening the issue and the PR! I have some difficulties understanding how this could happen. A `Span` should never have a `DroppedSpan` as a parent. We create `DroppedSpan`s in only two places:

https://github.com/elastic/apm-agent-python/blob/eac6ff86e7b28050d24f0bb2a4505ab9907fd70e/elasticapm/traces.py#L82-L87

First, if the parent span is a leaf span (meaning all child spans are ignored), a `DroppedSpan` is created that itself has `leaf` set to true, so any child spans of the dropped span should themselves be a `DroppedSpan`.

Second, if we reach the maximum amount of spans per transaction. Once this count is reached, we only create `DroppedSpan`s for the remainder of the transaction.

I've tried to think through scenarios that could end up in this buggy state, but couldn't come up with one yet. Do you per chance know if you have any transactions that can reach the max spans limit (500 by default)?

As for your proposed solution: while it would fix the exception, the resulting span object would be faulty. A better solution would probably be to add another `if` clause to the above code snippet, checking if the parent span is a `DroppedSpan` and, if yes, always create a `DroppedSpan` instead of a span. But before implementing this, I'd like to have a clearer understanding of how we can end up in this situation in the first place :)

**Comment by nchudleigh** [comment]
Thanks for the quick and detailed response!  I agree that would be a better fix.

> Do you per chance know if you have any transactions that can reach the max spans limit (500 by default)?

Yes this could happen in some cases.  Is there something I should consider for that?  Figured those cases would be safely handled.

**Comment by beniwohli** [comment]
@nchudleigh I just asked because if you didn't have transactions that could reach the the max spans limit, I could have focused my investigation on leaf spans. Alas, that's not the case ¯\\\_(ツ)\_/¯

**Comment by nchudleigh** [comment]
@beniwohli Right right, makes sense.  

Is there anything I can help with?  I could try and get more diagnostics or context from the cases where it was raised from.

As a fix for the time being, I am planning on just running a fork that implements your proposed solution.  Is there anything I could implement in the fork that would help with your investigation?

**Comment by nchudleigh** [comment]
@beniwohli Is there anything I can do to help on this?  Any luck finding issues?

**Comment by nchudleigh** [comment]
>@nchudleigh unfortunately I still wasn't able to replicate this issue. Was this a one-time occurrence for you or does it happen regularly?

Had an incident where it happened about a month ago, had a few hundred occurrences of it.  It only occurred in celery tasks, so for the time being I have turned the sampling for celery instances way down and am monitoring for the issue to occur again.

Can definitely try and replicate using that branch.  It's possible it is related to some of our celery changes though those are fairly standard.

Give me a couple days to pull something together, thank you for the branch.

**Comment by neilswinton** [comment]
I'm seeing this, too.  I don't start seeing it until I start several browsers.  I'm running gunicorn with gevents, two workers with four threads each.  I'm happy to run some experiments to see if it's threading related or to try a diagnostic branch.

This is my environment:

    OS: Alpine 3.9 (python:3.7.3-alpine3.9 docker container)
    Python version: 3.7.3
    Framework and version: Flask 1.1.1
    APM Server version: 6.5.4
    Agent version: 5.1.0

**Comment by KyeRussell** [comment]
I too am having this occur semi-regularly. I only added the Elastic agent a couple of days ago, and I already have 26 occurrences, which all appear to be within Celery jobs.

Happy to help in any way I can, time permitting. I am certainly unfamiliar with the internals of the Elastic APM Python agent so unsure of how much help I can be, however I have Celery events recorded for each occurrence with what I'm sure is a trove of valuable information.

**Comment by basepi** [comment]
I'm pretty certain this was fixed in https://github.com/elastic/apm-agent-python/pull/602, as now `DroppedSpan` objects have an `id`.

I'm closing this, but if anyone is still seeing this error please comment, and we'll get it re-opened!
