### ISSUE TITLE
Transaction.Response.StatusCode is expected to be Number not String

### ISSUE THREAD

**Issue by simitt** [elastic/apm-agent-python#47]
I experienced an `error` being sent to the `transactions` endpoint. It clearly happened in a development scenario, when I applied a change in a running Django app. Feel free to disregard this 'bug' report if it cannot happen in a 'real-world-scenario'.

Django console logging:
```
HTTP 400:
Failed to submit message: '<no message value>'
Traceback (most recent call last):
  File "/Users/simitt/.pyenv/versions/django-test-3.6.2/lib/python3.6/site-packages/elasticapm/transport/http_urllib3.py", line 75, in send_sync
    url = Urllib3Transport.send(self, data, headers)
  File "/Users/simitt/.pyenv/versions/django-test-3.6.2/lib/python3.6/site-packages/elasticapm/transport/http_urllib3.py", line 61, in send
    raise TransportException(message, data, print_trace=print_trace)
elasticapm.transport.base.TransportException: HTTP 400:
```

APM Server logging:
```
  I[#/transactions/0/context/response/status_code] S[#/properties/transactions/items/properties/context/properties/response/properties/status_code/type] expected number or null, but got string, code=400
```

**Comment by beniwohli** [comment]
Hmm, we actually turn the status code into a string, is that wrong?

https://github.com/elastic/apm-agent-python/blob/master/elasticapm/contrib/django/client.py#L159

**Comment by simitt** [comment]
In the current version it is expected to be a [number](https://github.com/elastic/apm-server/blob/master/docs/spec/context.json#L35).

But we could also implement it to allow `number,string,null` as we do for [error.exception.code](https://github.com/elastic/apm-server/blob/master/docs/spec/errors/error.json#L18).

**Comment by simitt** [comment]
But in either case, shouldn't the exception above be rather sent to the `errors` endpoint than to the `transactions` endpoint?

**Comment by beniwohli** [comment]
I don't think this was an exception, but a transaction, and during sending of the transaction, an error happened.

**Comment by simitt** [comment]
I updated the title. After trying to monitor performance requests I figured out that this is a general issue sending transactions. This seems to be urgent, since no performance data including a `response.status_code` can be processed right now on the APM server.

**Comment by beniwohli** [comment]
Opened a PR. Ideally, we should have tests that run this stuff against the JSON Schema. I'll look into doing that.
