### ISSUE TITLE
metrics.base_metrics.Counter.val accesses value without holding the lock

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-python#489]
https://github.com/elastic/apm-agent-python/blob/8705f2c746b429595cc8421ed990a1f0d155c199/elasticapm/metrics/base_metrics.py#L207-L209

`metrics.base_metrics.Counter.val` doesn't hold the lock, whereas all the other methods do. Seems like they all should?

**Comment by beniwohli** [comment]
@axw this is a read-only operation, so I don't think a lock is necessary. Or am I missing something?

**Comment by axw** [comment]
@beniwohli as in, it's atomic because of the GIL? Then should `Counter.reset` also not hold the lock? That's just a store - one operation, so atomic in CPython right?

Maybe I'm overcautious. I would use locks even for reads to (a) document that it's something that may be concurrently modified, and (b) so in a future world where the Gilectomy is completed, or Jython or IronPython are resurrected, then the agent wouldn't start having data races.

**Comment by beniwohli** [comment]
I don't think the GIL plays into it. I'm just not sure why a pure read operation that returns an immutable value (an integer) would need a lock.

**Comment by axw** [comment]
> I don't think the GIL plays into it. I'm just not sure why a pure read operation that returns an immutable value (an integer) would need a lock.

I don't understand. It's not an immutable variable, it's updated by `inc`, `dec`, and `reset`. Can those occur concurrently with `val`? If they cannot, then I guess we're fine - but it would be good to document that in that case.

**Comment by basepi** [comment]
I think what @beniwohli is saying is that a read is atomic, but a read+write is not (`inc`, `dec`). The only reason we need it on `reset` (which is also atomic) is to prevent an `inc` or `dec` operation from racing the `reset`. Thus, we lock anything that writes, but a straight read doesn't need it.

I'm going to close this issue, unless there's any other thoughts.
