### ISSUE TITLE
Implement remote configuration 

### ISSUE THREAD

**Issue by beniwohli** [elastic/apm-agent-python#498]
- [x] Implement API
- [x] Implement regular update call
- [x] Implement hot-reloading of configuration

see https://github.com/elastic/apm/issues/76

**Comment by bmorelli25** [comment]
I'll be on vacation when you implement this feature. Here's some boilerplate documentation you can hopefully adapt to match your config style: https://github.com/elastic/apm/issues/86. Also, don't forget to update the [precedence list](https://www.elastic.co/guide/en/apm/agent/python/current/configuration.html). Would be great if it included a link to the new configuration variable.

**Comment by beniwohli** [comment]
This has been implemented in #511, precedence list has been adapted in #548
