### ISSUE TITLE
System metrics not available on linux host with kernel < 3.14

### ISSUE THREAD

**Issue by NielkS** [elastic/apm-agent-python#500]
**Bug description**
I see the following exception twice whenever I start a (django) application and execute a transaction for the first time.

> Exception in thread eapm metrics collect timer:
> Traceback (most recent call last):
>   File "/opt/pack/PYT/envs/pyt-3.6.6.1/lib/python3.6/threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "/data/nielks/virtualenv/lib/python3.6/site-packages/elasticapm/utils/threading.py", line 64, in run
>     self._function(*self._args, **self._kwargs)
>   File "/data/nielks/virtualenv/lib/python3.6/site-packages/elasticapm/metrics/base_metrics.py", line 86, in collect
>     data = metricset.collect()
>   File "/data/nielks/virtualenv/lib/python3.6/site-packages/elasticapm/metrics/sets/cpu_linux.py", line 73, in collect
>     self.gauge("system.memory.actual.free").val = new["mem_available"]
> KeyError: 'mem_available'

As a result, no information related to CPU & memory usage is collected.

**Environment (please complete the following information)**
- OS: Linux, kernel 3.0.101-108.18-default 
- Python version: 3.6.6
- Framework and version  Django 2.1.4 
- APM Server version: 7.1.0
- Agent version: 4.2.2

**Additional context**
Looking at the implementation of elasticapm/metrics/sets/cpu_linux.py, I see that the "mem_available" gauge is evaluated from the "MemAvailable" line of /proc/meminfo.
That info was added in https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0a, release in 2014 in kernel 3.14.
My host machine has a kernel older than this, hence the exception.

I managed to implement a simple fix, that works fine on my machine:

```
    def collect(self):
        new = self.read_process_stats()
        new.update(self.read_system_stats())
        with self._read_data_lock:
             # ...
            mem_available = new["mem_available"] if "mem_available" in new else new["mem_free"]
            self.gauge("system.memory.actual.free").val = mem_available
            # ...

    def read_system_stats(self):
        stats = {}
        # ...
        with open(self.memory_stats_file, "r") as memfile:
            for line in memfile:
                if line.startswith("MemTotal:"):
                    stats["mem_total"] = int(whitespace_re.split(line)[1]) * 1024
                elif line.startswith("MemAvailable:"):
                    stats["mem_available"] = int(whitespace_re.split(line)[1]) * 1024
                elif line.startswith("MemFree:"):
                    stats["mem_free"] = int(whitespace_re.split(line)[1]) * 1024

        return stats

```
This will silently fallback to the value of "MemFree", if "MemAvailable" is not present.
I can create a PR for that, if the behavior is fine for you. (would you rather log a warning ? not provide the metric ?)

Best regards

**Comment by beniwohli** [comment]
Hi @NielkS 

thanks for opening the issue, great find! Your fix makes sense in my opinion. Would be great if you could open a pull request! If you're up for it, you could also add a test to this file: https://github.com/elastic/apm-agent-python/blob/7c831287a67166588395221c56994e23dddfafac/tests/metrics/cpu_linux_tests.py, but I can also do that after you submit your PR :)
