### ISSUE TITLE
use of django/flask apm

### ISSUE THREAD

**Issue by suyog1pathak** [elastic/apm-agent-python#503]
Hi,

I have one opensource python code from github which gives you TUI on terminal (it is not django or flask). Can I use Flask or Django APM in the same to get metrics?

Please help.

**Comment by beniwohli** [comment]
Hi @suyog1pathak 

You could theoretically use the [Agent API](https://www.elastic.co/guide/en/apm/agent/python/current/api.html) to create transactions/spans. But currently, the agent isn't really geared towards GUI or TUI ("terminal user interface" I assume?) apps, so you might encounter some awkwardness. This [blog post](https://www.elastic.co/blog/creating-custom-framework-integrations-with-the-elastic-apm-python-agent) could also be helpful to figure out how to use the API.

If you don't mind, could you direct future usage questions to our [forum](https://discuss.elastic.co/c/apm)? Github issues are more for tracking bugs/feature requests for the agent. Thanks! I'll go ahead and close this issue.
