### ISSUE TITLE
Change elasticsearch indices

### ISSUE THREAD

**Issue by JonasKs** [elastic/apm-agent-python#519]
I'm trying to make the APM indicies less frequent. I've tried looking for some settings, but unable to find any. I've also tried to send the APM logs through my Logstash, but I can't seem to make it work. Is there support for either of these options? If so, any documentation?

**Comment by axw** [comment]
@JonasKs please open a topic in the Discuss forum: https://discuss.elastic.co/c/apm. GitHub issues are meant for reporting bugs or previously-discussed feature requests. Thanks!

**Comment by JonasKs** [comment]
Sure, cheers!
