### ISSUE TITLE
Proposal: Enable support for Sanic

### ISSUE THREAD

**Issue by harshanarayana** [elastic/apm-agent-python#521]
**Is your feature request related to a problem? Please describe.**
This feature proposal describes the request to include support for [`sanic`](https://github.com/huge-success/sanic ) framework.

Sanic is being adopted widely by a large developer community and like `Flask` there is a need to add support for `Sanic` under the Elastic APM python client. 

**Describe the solution you'd like**
Add sanic support under contrib

**Describe alternatives you've considered**
I've a personal project going for supporting opentracing spec using Jaeger Client for Sanic but there is nothing available for sanic under the elastic-apm umbrella.

**Additional context**
NA

**Comment by beniwohli** [comment]
Hi @harshanarayana 

thanks for opening the issue and PR! Great work! Sanic is definitely a super interesting framework, I played around with it a bit a while ago.

There is however a bit of an issue with the fact that some code paths in the Python agent have blocking code. While most of them are on a background thread, some are currently still executed on the main thread (gathering source code lines for stack traces is the main culprit, I can't remember any others at the moment). This could lead to the event loop being blocked.

Implementing proper support for asyncio is on our roadmap, and that work will include moving blocking calls to background threads. I hope to get to this topic in the next couple of months, but unfortunately our backlog is pretty full at the moment.

**Comment by harshanarayana** [comment]
@beniwohli Thanks for getting back to me on this. I see your point and I will hold my PR in draft mode until the async support is brought into the python client.

That being said, I would be more than happy to lend a hand in case if there is a need for it in adding the async behavior to the apm python client.

**Comment by basepi** [comment]
For completeness, I added [an update](https://github.com/elastic/apm-agent-python/pull/522#issuecomment-582162814) to the PR at #522

**Comment by harshanarayana** [comment]
@basepi  That is wonderful news. Let me resurrect my work on this PR and get this on in.

**Comment by ajay1mg** [comment]
@harshanarayana is there any update on this? have you resurrected this PR?

**Comment by alexcc4** [comment]
Any update on this?

**Comment by frutik** [comment]
When a release can be expected?
