### ISSUE TITLE
elasticapm.transport.http spams logs with INFO level 'Sent request, url=...' message

### ISSUE THREAD

**Issue by zleroy** [elastic/apm-agent-python#527]
The following message is repeated in application logs over and over.  It pollutes the logs with what should be a TRACE or DEBUG level message at the INFO level.

2019-07-16T21:08:03.508Z INFO [logger={elasticapm.transport.http}] Sent request, url= size=1.06kb status=202

**Comment by beniwohli** [comment]
@zleroy I agree, `INFO` is too loud for this log message. I'll downgrade it to DEBUG. Thanks for the feedback!

**Comment by zleroy** [comment]
Excellent. Thank you!
