### ISSUE TITLE
Use `span.type: external` instead of `span.type: ext` 

### ISSUE THREAD

**Issue by roncohen** [elastic/apm-agent-python#528]
We should be using `span.type: external` instead of `span.type: ext` to align with the other agents in accordance with https://github.com/elastic/apm/issues/117

**Comment by beniwohli** [comment]
@roncohen this has been implemented in #377 already, but not yet merged. Basically, it's waiting for the next major release, as I consider it to be a breaking change. There are a few other breaking changes piling up, so it's probably getting time to make that jump. Lior suggested to synchronise it with the next minor stack release, and include central config management and breakdown metrics in that (agent) major.

**Comment by beniwohli** [comment]
#377 has been merged.
