### ISSUE TITLE
Limit the max amount of timer metrics

### ISSUE THREAD

**Issue by axw** [elastic/apm-agent-python#540]
We missed a bullet point from #479 in the implementation (https://github.com/elastic/apm-agent-python/pull/535):

- [ ] [Limit the max amount of timers](https://docs.google.com/document/d/1-_LuC9zhmva0VvLgtI0KcHuLzNztPHbcM0ZdlcPUl64#heading=h.tzyh7loxf2is)

**Comment by beniwohli** [comment]
@axw (or @felixbarny) can you define metricset in this context? I believe I might use it somewhat differently (I used the term `MetricSet` to describe a class that acts as a container for a set of metrics, e.g. all `gc` metrics, all `system` metrics and so forth).

**Comment by axw** [comment]
The fundamental thing we need to avoid is unbounded memory growth. In this case, a `metricset` is identified by its labels (including `transaction.name`, `transaction.type`, `span.type`, `span.subtype`); we need to cap the set of unique combinations of labels at 1000.

**Comment by felixbarny** [comment]
That's how I would define metric sets: https://github.com/elastic/apm-agent-java/blob/b6fef1d701f7edb3d9a2337d737f7207eec9df2b/apm-agent-core/src/main/java/co/elastic/apm/agent/metrics/MetricSet.java#L33-L44
