### ISSUE TITLE
Cant' disable instrumentation of code

### ISSUE THREAD

**Issue by Azd325** [elastic/apm-agent-python#546]
**Describe the bug**: 

[Docs ](https://www.elastic.co/guide/en/apm/agent/python/current/configuration.html#config-instrument)

`INSTRUMENT` Settings Variable does not work. It seems that it still looks for `DISABLE_INSTRUMENTATION`

https://github.com/elastic/apm-agent-python/blob/d495c27284ce62c5b39ecc3d0866eb9965caf098/elasticapm/conf/__init__.py#L311

**To Reproduce**

Install elasticapm in Version 5.0.0 and set up a django Project and try to disable instrumentation with `INSTRUMENT`

**Expected behavior**: 

Instrumentation ist disable with `INSTRUMENT` and not `DISABLE_INSTRUMENTATION`

**Comment by beniwohli** [comment]
@Azd325 great catch, thanks for opening the issue! I'll get this fixed ASAP!

**Comment by Azd325** [comment]
Great thanks.
