### ISSUE TITLE
Change the default port to 8200 to improve the getting started experience 

### ISSUE THREAD

**Issue by mcascallares** [elastic/apm-agent-python#57]
https://github.com/elastic/apm-agent-python/blob/e2c43748606e014a3c2f6238646ff2d37c127381/elasticapm/conf/defaults.py#L24

**Comment by beniwohli** [comment]
Thanks @mcascallares. As discussed off github, this is a relict from olden days and needs some cleaning up. The new defaults are set here: https://github.com/elastic/apm-agent-python/blob/54082d9b3e566c958032d0c056315a6cdeadc01a/elasticapm/conf/__init__.py#L134-L163
