### ISSUE TITLE
Agent can't monitor oracle sql in Python project

### ISSUE THREAD

**Issue by Jruing** [elastic/apm-agent-python#574]
I want to monitor the Pythonweb project, using the elastic-apm-5.0 version of the agent, it does not monitor oracle sql, see the relevant documentation on github(https://github.com/elastic/apm-agent-nodejs/issues/531), but it is for nodejs, in that document I saw nodejs support Custom span, I tried to use Python to customize the span, but Python has no informatio
agent version：elastic-apm-5.0
django version: 1.11.10

**Comment by beniwohli** [comment]
Hi @Jruing 

At the moment, there isn't a public API similar to what the NodeJS agent has. However, it's relatively easy to create your own SQL instrumentation, as long as the database driver supports Python's DB-API2 interface. For `cx_oracle`, you could do something like this

    from elasticapm.instrumentation.packages.dbapi2 import (
        ConnectionProxy,
        CursorProxy,
        DbApi2Instrumentation,
        extract_signature,
    )
    from elasticapm.instrumentation import register
    
    
    class OracleCursorProxy(CursorProxy):
        provider_name = "oracle"
    
        def extract_signature(self, sql):
            return extract_signature(sql)
    
    
    class OracleConnectionProxy(ConnectionProxy):
        cursor_proxy = OracleCursorProxy
    
    
    class OracleInstrumentation(DbApi2Instrumentation):
        name = "oracle"
    
        instrument_list = [("cx_Oracle", "connect")]
    
        def call(self, module, method, wrapped, instance, args, kwargs):
            return OracleConnectionProxy(wrapped(*args, **kwargs))
    
    
    register.register('ora.OracleInstrumentation')

Save this as `ora.py`, add it somewhere in your `PYTHON_PATH`, and then `import ora` as early as possible in your project (e.g. in your root `urls.py`)

Note that this is unsupported and might explode. I suggest to test it heavily in your development/staging environments before deploying it.

We hope to add official support for Oracle at some point. The main hold-up is that adding testing for Oracle would require a lot of work and computing resources.

**Comment by Jruing** [comment]
Ok, thank you very much for your help. I tried to write some code based on sqlite myself. It barely solves my problem.
