### ISSUE TITLE
Pause Elastic APM monitoring.

### ISSUE THREAD

**Issue by umarriqbal** [elastic/apm-agent-python#575]
I don't think this is already a feature or if there is a viable workaround around it.
I'm looking to dynamically pause/resume APM monitoring. 
I'm using:

`Python 3.5`
`Flask 1.0.2`
`Elastic APM 6.6.2`

Detail:
I'm trying to monitor logs or transactions only when a particular type/URL of request comes in. One way that I can achieve that is to reject/sanitise my transactions but that still includes the overhead of monitoring by Elastic APM. I want to get rid of the overhead completely since I deal in super realtime responses.

/edit:

### Spec

To align with the other agents and to provide greater flexibility, we're introducing two new config options: `enabled` and `recording`, while deprecating `active`.

Here's the expected behavior as described in https://github.com/elastic/apm/issues/92#issuecomment-519752096:

- `enabled` - Should behave identically to `active`, which in turn should be deprecated (this is essentially a rename to get a more meaningful name)
- `recording` - Should default to `true`. Setting to `false` will completely disable the recording and sending of data (transactions, spans, errors, and metrics). It must be possible to toggle `recording` dynamically, either locally or via remote config. Setting `recording` to `false` will therefore not disable remote config polling, config file watching, etc.

**Comment by beniwohli** [comment]
Hi @umarriqbal 

While such an option does not currently exist, we do have it on our roadmap: https://github.com/elastic/apm/issues/92#issuecomment-519752096. I haven't had a chance to open an implementation issue in this repo. If it's alright with you, I'll "declare" this issue the implementation issue and will add a short spec to your message.

**Comment by umarriqbal** [comment]
Hi, @beniwohli. That'll be great.

**Comment by basepi** [comment]
This was introduced in https://github.com/elastic/apm-agent-python/pull/790 -- `RECORDING` is the config that you're looking for.
