### ISSUE TITLE
DB interactions not traced when using context manager with psycopg2 connections or cursors

### ISSUE THREAD

**Issue by robbietotten** [elastic/apm-agent-python#577]
When using a context manager with psycopg2 connections or cursors, db interactions are not captured in spans.

The code below generates a span for `psycopg2.connect`, but not the query:
```
with psycopg2.connect(DSN) as conn:
    with conn.cursor() as curs:
        curs.execute("SELECT * FROM data.portfolio;")
        portfolios = curs.fetchall()
```

whereas the following captures both spans as expected:
```
conn = psycopg2.connect(DSN)
curs = conn.cursor()
curs.execute("SELECT * FROM data.portfolio;")
portfolios = curs.fetchall()
curs.close()
conn.close()
```

**Comment by beniwohli** [comment]
@robbietotten great catch! I opened #580 to fix this issue.
