### ISSUE TITLE
Python agent errors on using capture exception in decorator function

### ISSUE THREAD

**Issue by codeninja55** [elastic/apm-agent-python#599]
**Describe the bug**: ...
When trying to capture an exception in a decorator function, APM produces the following error.

```
File "/opt/conda/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/src/app/sim_api/middleware.py", line 343, in decorated_func
    apm.capture_exception()
  File "/opt/conda/lib/python3.7/site-packages/elasticapm/contrib/flask/__init__.py", line 214, in capture_exception
    return self.client.capture_exception(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/elasticapm/base.py", line 224, in capture_exception
    return self.capture("Exception", exc_info=exc_info, handled=handled, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/elasticapm/base.py", line 194, in capture
    event_type, date=date, context=context, custom=custom, stack=stack, handled=handled, **kwargs
  File "/opt/conda/lib/python3.7/site-packages/elasticapm/base.py", line 377, in _build_msg_for_logging
    result = handler.capture(self, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/elasticapm/events.py", line 119, in capture
    exc_type = exc_type.__name__
AttributeError: 'NoneType' object has no attribute '__name__'
```

**To Reproduce**

Take this function:

```
def auth_restful(f)
    @wraps(f)
    def decorated_func(*args, **kwargs):
        resp = User.decode_auth_token(auth_token=auth_token)
       
        if not user.is_admin:
            response['message'] = 'Not authorized.'
           # Error occurs HERE
            apm.capture_exception()
            return response, 403
        return f(user, *args, **kwargs)
    return decorated_func
```

The Flask-RESTful library and code to do this is as follows:

```
class UserList(Resource):
    """Return all users (admin only)"""

    method_decorators = {'get': [auth_restful]}

    def get(self, _) -> Tuple[dict, int]:
        """Get all users only available to admins."""
        user_list = User.as_dict
        response = {'status': 'success', 'data': {'users': user_list}}
        return response, 200
```

**Expected behavior**: ...

**Environment (please complete the following information)**
- OS: [e.g. Linux]: Docker base continuumio/miniconda3:4.6.14
- Python version: 3.7.3
- Framework and version [e.g. Django 2.1]:  Flask-RESTful
- APM Server version: 5.1.2
- Agent version: 5.1.2

**Additional context**

- `requirements.txt`:
  <details>
    <summary>Click to expand</summary>

    ```
    Flask==1.0.2
    elastic-apm[flask]==5.1.2
    fluent-logger==0.9.3
    Flask-RESTful==0.3.7
    Flask-Testing==0.7.1
    ```
  </details>

**Comment by beniwohli** [comment]
Hi @codeninja55 

Thanks for opening the issue. While there is indeed a bug here, I think you'd want to use `capture_message` instead, something like `apm.capture_message("Unauthorized access")`. `capture_exception` requires an actual Python exception to be present.

The bug is that we should detect if `capture_exception` is used when no exception is present, and warn instead of exploding. The actual problem is here:

https://github.com/elastic/apm-agent-python/blob/d0f2a392fb52d0e09d92aa7036a0353e819ba2f1/elasticapm/events.py#L85-L90

When no exception is present, `sys.exc_info()` returns `(None, None, None)`, not `None` as the `if not exc_info` line seems to think.

**Comment by codeninja55** [comment]
Thanks for the response. I'll do as you suggest.

**Comment by basepi** [comment]
Better error handling in #600 ^

Thanks again for the report!
