### ISSUE TITLE
Flask integration doesn't send transaction for unhandled errors

### ISSUE THREAD

**Issue by beniwohli** [elastic/apm-agent-python#629]
**Describe the bug**: When an unhandled error occurs, the transaction is not ended correctly, and no transaction data is captured

**To Reproduce**

1. Access a flask endpoint that triggers an error
2. Error is captured, transaction is not

**Expected behavior**: Both error and transaction events should be captured

This is due to the fact that we listen to the `flask.signals.request_finished` signal, which is not sent when an error occurs. So far, I haven't found a better candidate

 * `request_teardown` is sent even if an error occurs, but it isn't provided the `response` object, which we need
 * similarly, `got_request_exception` also doesn't have the `response` object
 * functions decorated with `after_request` are also not called if an unhandled exception is triggered

We can move some of the work we do currently do in the `request_finished` handler to the `request_started` handler. But for setting the transaction result (based on the HTTP status code), we *need* the response object. I currently don't see a way to do this without taking out the big monkeypatching guns :(

**Comment by basepi** [comment]
Ouch. That's a bummer. Might be worth opening a dialog to upstream, though that will obviously only fix the issue for new versions.

**Comment by beniwohli** [comment]
I believe Flask's API is consciously behaving the way it does, so I don't think we have a big chance in getting it changed. I implemented an IMO acceptable workaround in #635
