### ISSUE TITLE
[Feature] gRPC support

### ISSUE THREAD

**Issue by xiaowuyz** [elastic/apm-agent-python#645]
APM support for gRPC would be excellent. We can likely implement this support via [gRPC interceptors](https://github.com/grpc/proposal/blob/master/L13-python-interceptors.md).

**Comment by beniwohli** [comment]
Hi @xiaowuyz 

The Python agent currently doesn't support grpc. We do plan to add support some time in the coming months.

**Comment by basepi** [comment]
I took the liberty of editing your issue title/text so that we can track gRPC implementation here.

**Comment by julianogv** [comment]
@basepi  Any idea on when we will have grpc support for python client?

**Comment by basepi** [comment]
No clear idea yet, but I've added it to our roadmap discussions.

**Comment by smitp33** [comment]
Hi, be really interesting to know how this is progressing on your roadmap. We are a platform that is heavily invested in elastic APM and see real value from it. Our only current gap is the platform traffic that is GRPC based so having this capability would be gold dust for us ;)

**Comment by basepi** [comment]
Hey @smitp33! I'm pretty sure @beniwohli is working on this *right now*, so hopefully we'll have some good news for you soon!

**Comment by smitp33** [comment]
That is great news @basepi. If we can help any in terms of real world testing please do let us know.

**Comment by basepi** [comment]
If anyone is still willing to test, we have an open PR! #1703
