### ISSUE TITLE
Implement API Key authentication

### ISSUE THREAD

**Issue by beniwohli** [elastic/apm-agent-python#671]
See https://github.com/elastic/apm/issues/183 for a specification.

It might make sense to use this as a test case for [pytest-bdd](https://github.com/pytest-dev/pytest-bdd)

**Comment by bartier** [comment]
@beniwohli Hi! I'm new here.

Is this already implemented? I'm not sure.
https://github.com/elastic/apm-agent-python/blob/151f2ef8e7d15e7a21829d9cb72dec8bfeb887e5/elasticapm/transport/http_base.py#L92-L98

**Comment by basepi** [comment]
This was implemented in #679

**Comment by basepi** [comment]
Thanks for your offer of help @bartier! Sorry we were slow to respond here.
