### ISSUE TITLE
Opentracing contrib: `DroppedSpan has no attribute transaction`

### ISSUE THREAD

**Issue by JeckyTian** [elastic/apm-agent-python#683]
**Describe the bug**: ...
When using Elastic APM with Opentracing, the program crashes on `AttributeError: DroppedSpan object has no attribute transaction` exception if `span.finish()` is called. 
 It turns out to be this line:
https://github.com/elastic/apm-agent-python/blob/74cd1fa56f15a3149b367bd65ea4721a6fd95615/elasticapm/contrib/opentracing/span.py#L129
It will access `transaction` attribute which does NOT exist for `DroppedSpan`.

**Expected behavior**: ...
It should be expected to behave normally even if it's `DroppedSpan`.

**Environment (please complete the following information)**
- OS: [e.g. Linux] Linux
- Python version: 2.7
- Framework and version [e.g. Django 2.1]: N/A
- APM Server version: 7.4.0
- Agent version: 5.3.2

**Comment by beniwohli** [comment]
Great find @JeckyTian! I'll open a PR with a fix.

**Comment by JeckyTian** [comment]
@beniwohli  Thanks,   is there an expectation which release has this fix?

**Comment by HarmitMinhas96** [comment]
Similarly this occurs: `"AttributeError: 'DroppedSpan' object has no attribute 'name'`

**Comment by beniwohli** [comment]
@JeckyTian we just published 5.3.3 of the agent which includes this bug fix. Thanks again for reporting!
