### ISSUE TITLE
Add support for FastAPI

### ISSUE THREAD

**Issue by kicmultimedia** [elastic/apm-agent-python#686]
Currently, it seems FastAPI is unsupported. Would be great to add the Python Framework to the list of those supported.

Am I correct in assuming we could write our own middleware for this Framework using this library?

**Comment by basepi** [comment]
Yes, you could. It would be very similar to [this blog post](https://www.elastic.co/blog/creating-custom-framework-integrations-with-the-elastic-apm-python-agent), I think. You can also look at our [aiohttp]() support for an example.

Note that FastAPI and Starlette will probably be on our roadmap, as they are definitely picking up popularity. We just don't have an ETA.

**Comment by Sparkycz** [comment]
Hey guys, we have the same need therefore I dug into it and wrote the middleware. Check it out please.

**Comment by basepi** [comment]
Awesome! I was planning to start working on that today so your timing couldn't be better! I'll review it today.
