### ISSUE TITLE
HOSTNAME value ignored and socket.gethostname() sent

### ISSUE THREAD

**Issue by esseti** [elastic/apm-agent-python#688]
I've trouble in configuring the HOSTNAME, If I set it in the django settings or in the enviorment nothing changes. the `socket.gethostname()` is always the value sent.

**To Reproduce**
- setup project with APM
- add 
```
ELASTIC_APM = {
  ..
    'HOSTNAME': 'myhostname'
...
}
```

**Expected behavior**: 
To see `myhostname` in the host list in kibana

**Environment (please complete the following information)**
- OS: Linux/Mac
- Python version: 3.7
- Framework and version Django 2.2
- APM Server version: 7.5
- Agent version: elastic-apm==5.3.2

**Additional context**

Debugging the code, in the `config` the correct value is there, however the 
socket.gethostname() value is sent

**Comment by esseti** [comment]
By looking into the code, my guess is that this line: https://github.com/elastic/apm-agent-python/blob/master/elasticapm/base.py#L320

should be
`"hostname": keyword_field(self.config.hostname),`

in the config, the hostname is set as ` hostname = _ConfigValue("HOSTNAME", default=socket.gethostname())` so that the line above is cutting the string to the max length and that's it.

**Comment by beniwohli** [comment]
@esseti great catch! I'll open a PR with your suggested fix and a test in a minute
