### ISSUE TITLE
Python Flask APM cannot disable metrics

### ISSUE THREAD

**Issue by kourosh-azizi** [elastic/apm-agent-python#696]
**Describe the bug**: ...

I have the following Python Flask APM configuration in my web app:

```
from elasticapm.contrib.flask import ElasticAPM
app = Flask(__name__)
app.config['ELASTIC_APM'] = {
  'SERVICE_NAME': 'FLASK-APP-PROJECT',
  'SECRET_TOKEN': '***',
  'SERVER_URL': '***',
  'DISABLE_METRICS': '*.cpu.*,system.memory.*,system.process.memory.*'
}
apm = ElasticAPM(app)
```

I tried to disable the CPU and Memory metrics because I'm not interested to monitor them anymore, and they are just populating my storage and making my queries slow. 

I applied the `DISABLE_METRICS` field, but it didn't stop the process, and data was still being sent.

I also tried to set `METRICS_INTERVAL` to 0 to stop sending metrics completely, but it didn't work, and I was still receiving APM CPU and Memory metrics.

**To Reproduce**

1. Run a Python Flask web app project locally on the command line. Then apply the above configuration in the code (note: I am using Elastic Cloud and not localhost for my ELK stack).

2. Click around in your web app, and go to Kibana APM page and wait for 30-40 seconds, then refresh the page to view the metrics.

**Expected behavior**: 
- CPU and Memory metrics keep sending to Elasticsearch from APM.
![image](https://user-images.githubusercontent.com/50716652/72836134-e6719b80-3c40-11ea-8189-425aae0a1a66.png)

**Environment (please complete the following information)**
- OS: [e.g. Linux]
- Python version: 3.6.8
- Kibana version: 7.3.2
- Elasticsearch version: 7.3.2
- APM Server version: APM 7.3.2
- APM Agent language and version: Python Flask 4.2.2

**Additional context**
If you need my Flask project, let me know and I can send/email it to you.

I also opened this issue on Elastic discussion, and one of Elastic developers (@basepi ) suggested to open a Github ticket issue to investigate this further. 
https://discuss.elastic.co/t/how-to-reduce-apm-transactions-and-metrics/215206/5

In the past there were multiple tickets and discussions opened regarding APM agent failing to stop sending metrics to Elasticsearch such as this one:
https://discuss.elastic.co/t/unable-to-disable-apm-via-environment-variable/180558/3

**Comment by basepi** [comment]
A workaround was recommended [on the discuss thread](https://discuss.elastic.co/t/how-to-reduce-apm-transactions-and-metrics/215206/11?u=basepi) by @beniwohli:

> As a workaround until we have a real solution, you could remove the CPU metrics from the `METRICS_SETS` setting. This setting is undocumented, as it can be a bit finicky. You can set it to:
>
> ```
> app.config['ELASTIC_APM']['METRICS_SETS'] = ["elasticapm.metrics.sets.transactions.TransactionsMetricSet",]
> ```
>
> The `TransactionsMetricSet` is required to get the overall metrics how much time your app spends in database queries, http requests etc, so I recommend to leave it in.

We still haven't found the "correct" solution but will update here when we do.

**Comment by kazizi1** [comment]
Thanks, I tried the above workaround, and it works!
