### ISSUE TITLE
Error while application is shutdown and long delay

### ISSUE THREAD

**Issue by amalpadmanabhan** [elastic/apm-agent-python#702]
Pip freeze version for elastic-apm
elastic-apm==5.3.3

Using Flask Elastic APM to monitor an application that is loaded using UWSGI.

While stopping the application I am getting the error,

Traceback (most recent call last):
  File "*lib/python3.6/site-packages/elasticapm/utils/compat.py", line 65, in uwsgi_atexit
    func()
  File "*lib/python3.6/site-packages/elasticapm/base.py", line 293, in close
    self._transport.close()
  File "*lib/python3.6/site-packages/elasticapm/transport/base.py", line 293, in close
    super(AsyncTransport, self).close()
  File "*lib/python3.6/site-packages/elasticapm/transport/base.py", line 241, in close
    raise ValueError("close timed out")
ValueError: close timed out
worker 5 buried after 11 seconds
goodbye to uWSGI.

The only code that I have added for instrumentation of my app is,

import elasticapm
from elasticapm.contrib.flask import ElasticAPM
elasticapm.instrument()
application.config['ELASTIC_APM'] = {
  'SERVICE_NAME': servicename,

  'SECRET_TOKEN': '',

  'SERVER_URL': 'url:8200',
}

Now when I shutdown it takes a while.

I also tried both lazy-app and default preforking mechanism on USWGI. 

uwsgi.ini
[uwsgi]
module = wsgi

master = true
processes = 5
threads = 4

socket = locatest.sock
chmod-socket = 660
vacuum = true
enable-threads = true
lazy-apps = true
single-interpreter = true
logto = uwsgi_log/%n.log

die-on-term = true

**Comment by beniwohli** [comment]
Hi @amalpadmanabhan 

What seems to happen here is that we're unable to flush the APM data to the apm-server in time when uwsgi is exiting. The default timeout for this is 10 seconds, which explains why uwsgi reports 11 seconds.

How busy are your apm-server(s)? When uwsgi is exiting, all running instances flush the data at the same time, which might lead to a peak in resources needed by apm-server. If it is already quite busy normally, this could push it over the edge and lead to the timeouts.

do you see this regularly or only occasionally?

**Comment by beniwohli** [comment]
@amalpadmanabhan we just released a new version of the agent that should fix this issue, can you try to install 5.4.1 and see if the problem goes away?

I'll close this issue for now, please re-open it if you still encounter the bug.
