### ISSUE TITLE
Celery workers hangs while being restarted

### ISSUE THREAD

**Issue by starenka** [elastic/apm-agent-python#704]
Hi folks, I have problem with celery (4.3.0) workers within django (1.11.20) project. I'm unable to restart them via supervisor (3.3.1-1+deb9u1). Here's one of the workers conf in supervisor for illustration....

```
[program:celery_tvr_reporting]
command = /home/project/venv/project/bin/celery worker -A project --concurrency 3 --loglevel=INFO -Q tvr -n worker.tvr
directory = /home/project/project/django/
priority = 1000
user = project
autorestart = true
stdout_logfile = /home/project/weblogs/supervisor/celery_tvr.log
redirect_stderr = true
startsecs = 10
stopwaitsecs = 600
killasgroup = true
```

I get this trace in sentry when trying to restart the workers (or killing them with `-9` - I'm not sure which one triggers it)

```
ValueError: close timed out
  File "celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "elasticapm/contrib/celery/__init__.py", line 83, in worker_shutdown
    client.close()
  File "elasticapm/base.py", line 293, in close
    self._transport.close()
  File "elasticapm/transport/base.py", line 293, in close
    super(AsyncTransport, self).close()
  File "elasticapm/transport/base.py", line 241, in close
    raise ValueError("close timed out")
```

Without `elasticapm.contrib.django` in `INSTALLED_APPS` everything works well, workers are gracefully restarted even in "high times". There's no problem with other (gunicorn) workers (they send to apm server fine, no timeouts etc). I've tried at least turn the instrumentation for celery workers off (not fine, but well, better than this) with setting up:
```
environment=
 ELASTIC_APM_INSTRUMENT=False,
 ELASTIC_APM_DISABLE_SEND=True
```

in supervisor, but it doesn't help. Anyway the celery integration seems defunct either way, cause I haven't seen any stuff in Kibana from celery workers. I will happily provide more information, but it's quite hard to experiment, because this is a production server and I need those workers to work ;)

PS. Yes, I'm aware our stack is ancient, we're working on it.... 

Any help? Thanks!

**Environment (please complete the following information)**
- OS: [e.g. Linux] Debian
- Python version: 2.7.13
- Framework and version [e.g. Django 2.1]: 1.11.20
- APM Server version: 7.5.2
- Agent version: 5.3.3
- Celery: 4.3.0

**Comment by basepi** [comment]
I think the hang on restart, while problematic, is secondary to the fact that even on a normal start, you're not seeing APM data from celery.

@beniwohli do you see any red flags? I haven't actually worked with our celery instrumentation yet, so I wanted to check before I did any deep diving.

**Comment by beniwohli** [comment]
@starenka  we just released a new version of the agent that should fix this issue, can you try to install 5.4.1 and see if the problem goes away?

I'll close this issue for now, please re-open it if you still encounter the bug.

**Comment by starenka** [comment]
Hi @beniwohli, what issue do you mean? The hangs or the kinda not working env variables? I fixed it meanwhile by making extra django settingsm, where apm app is not in `INSTALLED_APPS`...

**Comment by starenka** [comment]
PS. I'm unable to reopen the issue...

**Comment by beniwohli** [comment]
@starenka sorry about that! We released 5.4.2, which should solve the `'AsyncTransport' object has no attribute '_start_event_processor'` error.

**Comment by starenka** [comment]
No, problem. Well, the error is not there :+1: , yet the workers are still blocked...

**Comment by beniwohli** [comment]
@starenka would you mind trying if setting the [`transport_class`](https://www.elastic.co/guide/en/apm/agent/python/current/configuration.html#config-transport-class) setting to `elasticapm.transport.http.Transport` fixes the issue?

**Comment by starenka** [comment]
well, `Note however that this can have adverse effects on performance.` this says me i don't want to :)

**Comment by beniwohli** [comment]
That note is slightly out of date, and we need to fix it. Basically, all transports are now asynchronous (in the sense that putting something on the transport queue is non-blocking). The only difference between `Transport` and `AsyncTransport` is that the former uses the same background thread for processing as it does for actually sending the data over HTTP(s), while the latter has a separate thread for HTTP communication.

**Comment by runekri3** [comment]
I am getting the same issue. Seems to happen when celery containers shut down (e.g. during a deploy).

Environment (please complete the following information)

OS: [e.g. Linux] Linux
Python version: 3.8
Framework and version [e.g. Django 2.1]: Django 2.2.12
APM Server version: 7.6.1
Agent version: 5.6.0
Celery: 4.4.2

**Comment by basepi** [comment]
@starenka did changing the transport_class fix this issue for you?

**Comment by basepi** [comment]
Closing this for now. Please comment if this is still an issue and we can open it again!
