### ISSUE TITLE
Make parameters of a SQL query visible as a config option

### ISSUE THREAD

**Issue by ifmusic** [elastic/apm-agent-python#709]
I know that SQL spans params are obfuscated by design as a security measure but I think it'd be great if you could add a flag to send these params in raw format.

https://discuss.elastic.co/t/make-parameters-of-a-sql-query-visible-as-a-config-option/217025
https://discuss.elastic.co/t/how-to-print-query-parameters-also-along-with-the-query/194016

I think there should be some flag in the agent config like:
`RAW_REQUESTS_PARAMS= True / False (obfuscated, as it is right now; default) `

Thanks

**Comment by beniwohli** [comment]
Hi @ifmusic

It's an interesting idea! We'd probably want to introduce it across all our APM agents, I'll bring it up with the team.

Just a minor clarification for posterity's sake: the fact that params are currently masked is something we basically get for free. Most libraries that create queries (SQLAlchemy, Django ORM etc) use either prepared statements or parametrized queries. If you would run a "hardcoded" query, we would capture it as is, with all the variables (I'm not suggesting you should do that ;) ).

**Comment by basepi** [comment]
Hey @ifmusic we discussed this in today's agents meeting and I don't think we're going to implement this for now. The main issues are targeting/security (a single environment variable will collect raw SQL from everything in the app which could collect unintended information while debugging a single query) as well as support surface (if we had this config available, we would be obliged to support it across all database libraries which may not be feasible).

Our recommendation for now is to collect this data yourself, either by logging the raw SQL to your application logs or using [`elasticapm.set_custom_context`](https://www.elastic.co/guide/en/apm/agent/python/current/api.html#api-set-custom-context) to add it to the current transaction's context.

Sorry for the inconvenience!
