### ISSUE TITLE
No module named 'elasticapm.contrib.aiohttp'

### ISSUE THREAD

**Issue by meysam81** [elastic/apm-agent-python#710]
When I install the package using `pip install elastic-apm`, the `aiohttp` module is not found in the library. I tried installing via cloning the repository and using `pip install .` on the project's root directory and the `aiohttp` module was there. My best guess is that the [PyPi](https://pypi.org/project/elastic-apm/) of the project is not up-to-date. But then again I may be wrong and I may have to do something that I'm not aware of. By the way I read the [docs](https://www.elastic.co/guide/en/apm/agent/python/master/aiohttp-server-support.html) as well but no luck there too.

**To Reproduce**

1. install the package using `pip install elastic-apm`
2. try importing like this `from elasticapm.contrib.aiohttp import ElasticAPM`
3. you would encounter something like this: `No module named 'elasticapm.contrib.aiohttp'`
4. try cloning the repository and installing via `pip install .` in the project's root directory and then `from elasticapm.contrib.aiohttp import ElasticAPM` would work just find.

**Expected behavior**: ...
I was expecting that it would work just find using the simple installation of `pip install elastic-apm`

**Environment (please complete the following information)**
- OS: Linux
- Python version: 3.8.1
- Framework and version [e.g. Django 2.1]: Aiohttp 3.6.2
- APM Server version: 5.3.3
- Agent version: doesn't matter but 7.5.0

**Additional context**

- `setup.py`:
```
from setuptools import setup, find_packages
...
REQUIRES = [
...
    'elastic-apm==5.3.3',
...
]
...
setup(
...
    install_requires=REQUIRES,
    python_requires='>=3.8.1',
...
)

```
- elasticapm library
```
/app # tail -2 /usr/local/lib/python3.8/site-packages/elasticapm/version.py 
__version__ = (5, 3, 3)
VERSION = ".".join(map(str, __version__))
/app # ls -l /usr/local/lib/python3.8/site-packages/elasticapm/contrib/
total 52
-rw-r--r--    1 root     root          1591 Feb  1 07:54 __init__.py
drwxr-xr-x    2 root     root          4096 Feb  1 07:54 __pycache__
-rw-r--r--    1 root     root          5982 Feb  1 07:54 async_worker.py
drwxr-xr-x    3 root     root          4096 Feb  1 07:54 celery
drwxr-xr-x    6 root     root          4096 Feb  1 07:54 django
drwxr-xr-x    3 root     root          4096 Feb  1 07:54 flask
drwxr-xr-x    3 root     root          4096 Feb  1 07:54 opentracing
-rw-r--r--    1 root     root          1788 Feb  1 07:54 paste.py
drwxr-xr-x    3 root     root          4096 Feb  1 07:54 pylons
drwxr-xr-x    3 root     root          4096 Feb  1 07:54 rq
drwxr-xr-x    3 root     root          4096 Feb  1 07:54 twisted
drwxr-xr-x    3 root     root          4096 Feb  1 07:54 zerorpc
```

**Comment by beniwohli** [comment]
Hi @meysam81 

support for aiohttp hasn't been quite released yet. You can try it out by installing the agent from the master branch 

    pip install https://github.com/elastic/apm-agent-python/archive/master.zip\#egg\=elastic-apm\=\=100

I would love to hear your feedback how it works for you!

**Comment by basepi** [comment]
@meysam81 I'm going to close this issue for now. But we'd love to hear any feedback you have if you try on the master branch or on our next feature release! Have a great day!

**Comment by meysam81** [comment]
didn't workout well apparently
```
 ---> 6b94ddfb4dc7
Step 26/33 : RUN pip install https://github.com/elastic/apm-agent-python/archive/master.zip\#egg\=elastic-apm\=\=100
 ---> Running in dced905cf46c
Collecting elastic-apm==100
  Downloading https://github.com/elastic/apm-agent-python/archive/master.zip
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
  WARNING: Requested elastic-apm==100 from https://github.com/elastic/apm-agent-python/archive/master.zip#egg=elastic-apm==100, but installing version 5.3.3
```

although I did try it manually and that worked out well.

**Comment by beniwohli** [comment]
@meysam81 that `WARNING` can be ignored. Setting the desired version to `100` in the `pip install` command is a bit of a hack to ensure that it'll always replace the currently installed version. The package has been installed correctly, judging from the other output you shared.

**Comment by meysam81** [comment]
but it's not an unimportant warning, it's saying that the requested version (elastic-apm==100) is not installed and rather the 5.3.3 version is installed (look at the end of warning line)

**Comment by beniwohli** [comment]
Can you try this instead, then?

    pip uninstall elastic-apm
    pip install https://github.com/elastic/apm-agent-python/archive/master.zip\#egg\=elastic-apm

It'll still say the version is 5.3.3, as that's what current master is set to:

https://github.com/elastic/apm-agent-python/blob/f007f22b44d051d197aa7b54de8fc9e6deec3e4b/elasticapm/version.py#L31-L32

We probably should consider adding a `post1` component to the version on master to make things like this clearer.

**Comment by meysam81** [comment]
@beniwohli 
OK thanks, we're all set.

**Comment by Sumanth5** [comment]
I followed the same steps but I am getting this error. 
```
Collecting https://github.com/elastic/apm-agent-python/archive/master.zip\#egg\=elastic-apm
  ERROR: HTTP error 404 while getting https://github.com/elastic/apm-agent-python/archive/master.zip\#egg\=elastic-apm
ERROR: Could not install requirement https://github.com/elastic/apm-agent-python/archive/master.zip\#egg\=elastic-apm because of HTTP error 404 Client Error: Not Found for url: https://github.com/elastic/apm-agent-python/archive/master.zip%5C for URL https://github.com/elastic/apm-agent-python/archive/master.zip\#egg\=elastic-apm
```

**Comment by beniwohli** [comment]
@Sumanth5 support for aiohttp has been merged a while ago, you should be good with just `pip install elastic-apm`

**Comment by Sumanth5** [comment]
> @Sumanth5 support for aiohttp has been merged a while ago, you should be good with just `pip install elastic-apm`

Nope,
I have an error: 
`from elasticapm.contrib.flask import ElasticAPM
ModuleNotFoundError: No module named 'elasticapm'`

**Comment by abiral-sijaria** [comment]
I am facing the same issue for elasticapm.contrib.django. It is not working with `pip install elastic-apm`. Can you please tell the workaround here?

**Comment by abiral-sijaria** [comment]
@beniwohli I am facing the same issue for elasticapm.contrib.django. It is not working with `pip install elastic-apm`. Can you please tell the workaround here?
