### ISSUE TITLE
Django 3.0 Support

### ISSUE THREAD

**Issue by Palisand** [elastic/apm-agent-python#713]
According to [this](https://www.elastic.co/guide/en/apm/agent/python/current/supported-technologies.html#supported-django), `elastic-apm` supports up to Django 2.2.

Has anyone tested this with Django 3.0?
Is there an ETA on when Django 3.0 will be officially supported (e.g. on the next release)?

**Comment by beniwohli** [comment]
Hi @Palisand

We will release version 5.4 soon, which adds official support for Django 3.0. But as far as I remember, we didn't have to implement and Django 3.0 specific fixes. It should just work with the current version.

**Comment by Palisand** [comment]
Thanks @beniwohli. I'll leave this issue open until official support is released.

**Comment by beniwohli** [comment]
@Palisand a new version of the agent has now been released.

Note that we didn't investigate ASGI yet, so there might be issues if you run your Django app in ASGI mode.

**Comment by Palisand** [comment]
@beniwohli Currently still running in WSGI. Thank you!

**Comment by daniel-ruiz** [comment]
Hi!

I'm running a Django app in ASGI mode. I'd want to integrate it with APM and I found this issue. Are there any plans to officially support Django ASGI apps? Is there any other way to currently integrate them with APM? 

Any help would be appreciated. Thanks in advance 😊

**Comment by basepi** [comment]
@daniel-ruiz We definitely plan to officially support it. It may largely work now, we just haven't investigated yet.
