### ISSUE TITLE
'AsyncTransport' has no attribute '_start_event_processor'

### ISSUE THREAD

**Issue by jaap3** [elastic/apm-agent-python#723]
**Describe the bug**: ...

After upgrading to `elastic-apm==5.4.1` I now get an error when Celery starts:

```
<function _register_worker_signals.<locals>.worker_startup at 0x7feae4beb620> raised: AttributeError("'AsyncTransport' object has no attribute '_start_event_processor'",)
Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/venv/1.37.1/lib/python3.6/site-packages/elasticapm/contrib/celery/__init__.py", line 80, in worker_startup
    client._transport._start_event_processor()
AttributeError: 'AsyncTransport' object has no attribute '_start_event_processor' 
```

**Environment (please complete the following information)**
- OS: Linux-3.10.0-1062.9.1.el7.x86_64-x86_64-with-centos-7.7.1908-Core 2020-02-18 16:24:31
- Python version: Python 3.6.8
- Framework and version: 
  celery 4.4.0
  Django 3.0.3
- APM Server version: ?
- Agent version: 5.4.1

I see the same error mentioned in issue #704, but I don't seem to have an issue with restarting Celery workers.

**Comment by beniwohli** [comment]
@jaap3 thanks for opening the issue! We are already working on a fix, hopefully to be released later today.

Sorry for the inconvenience!

**Comment by jaap3** [comment]
OK, it's almost the end of my workday. So I'll downgrade to 5.4.0 for now just to make sure

**Comment by beniwohli** [comment]
@jaap3 5.4.2 is on PyPI and should fix this particular issue.

**Comment by jaap3** [comment]
Thanks, I'll update :)
