### ISSUE TITLE
[Feature] encode/httpx support

### ISSUE THREAD

**Issue by basepi** [elastic/apm-agent-python#739]
A friend and I were chatting recently about async libraries in python. He had nothing but good things to say about the tools in https://github.com/encode

`httpx` seems like a no-brainer, in particular: https://github.com/encode/httpx

**Comment by HenrikOssipoff** [comment]
I was in need of this yesterday in one of our projects, and made a quick implementation of this. Would you be accepting a PR for this, or is anyone working on it?

`httpx` has both a sync and async client in the same codebase. Am I correct in assuming that the correct approach here is to add two separate instrumentation packages?

**Comment by basepi** [comment]
We'd love to see a PR! And yes, it would be two different instrumentation modules due to the `async def` vs not.

**Comment by sethmlarson** [comment]
Something to note here is that HTTPX is not a stable interface. 0.12 vs what will be 0.13 will look completely different. See HTTPX/httpcore split.

**Comment by basepi** [comment]
@sethmlarson Thanks for the reminder! I remember you mentioning that previously. Perhaps we should wait for the eventual v1.0 release before we officially support this.

**Comment by HenrikOssipoff** [comment]
@sethmlarson @basepi As far as I can tell between the current work in progress v0.13 and v0.12, the interface exposed on the `Client` class is the same, it's only the underlying implementation that's been changed (there's a `send` method both the normal client and the async client that I used for my local implementation - it's the same between versions).

Your call of course, if you'd rather wait for a fully stable version though - very understandable 🙂

**Comment by basepi** [comment]
Hmm. I think we can probably add some tests that pull from their development branch so we won't be caught off guard. Go ahead and open your PR! :)

**Comment by basepi** [comment]
@HenrikOssipoff Are you still game to submit a PR for this?

**Comment by HenrikOssipoff** [comment]
Sorry it's been busy during this situation that's going on - still up for it, will get to it within the next few days. Sorry about the wait! v0.13 is out now as well with the reworked internals.

**Comment by basepi** [comment]
Excellent! Looking forward to it.
