### ISSUE TITLE
[Feature] encode/databases support

### ISSUE THREAD

**Issue by basepi** [elastic/apm-agent-python#740]
A friend and I were chatting recently about async libraries in python. He had nothing but good things to say about the tools in https://github.com/encode

`databases` seems like a good candidate for upping our async game: https://github.com/encode/databases

**Comment by beniwohli** [comment]
So far, we avoided instrumenting ORMs (and similar) and instead instrumented the database drivers.

**Comment by basepi** [comment]
My understanding is that `databases` is a driver. He has `orm`, which uses `databases` under the hood.

**Comment by beniwohli** [comment]
I didn't take a closer look at the code, but the README says

> Driver support is providing using one of asyncpg, aiomysql, or aiosqlite.

**Comment by basepi** [comment]
Well then. Those are the drivers we shall instrument! I'll open separate issues.
