### ISSUE TITLE
SSL/TLS is not working when client_authentication was not setup in APM Server

### ISSUE THREAD

**Issue by insukcho** [elastic/apm-agent-python#758]
**Describe the bug**: 
I'm trying to set up TLS/SSL between Django/Flask Agents and self-managed APM Server in the same local machine.

When I checked the `apm-server.yml` configuration, it seems `client_authentication` default value is `optional` but when I didn't set up this, I keep seeing SSL handshaking exceptions.

After comment out `client_authentication: 'optional'` in `apm-server.yml` and restart APM Server, it was working.

**To Reproduce**

1. Set APM Server with below configuration in `apm-server.yml`. (FYI, I've generated self-signed certificates with elasticsearch-certutil.)
```
apm-server.ssl.enabled: true
apm-server.ssl.key: "./certs/localhost/localhost.key"
apm-server.ssl.certificate: "./certs/localhost/localhost.crt"
apm-server.ssl.certificate_authorities: ['./certs/ca/ca.crt']
apm-server.ssl.secret_token: ${SECRET_TOKEN}
```
2. Set Django and Flask with below.

*Django(settings.py)*
```
ELASTIC_APM = {
  'DEBUG': True,
  # Set required service name. Allowed characters:
  # a-z, A-Z, 0-9, -, _, and space
  'SERVICE_NAME': 'amazing_django_service',

  # Use if APM Server requires a token
  'SECRET_TOKEN': '6AC5BF896C915',

  # Set custom APM Server URL (default: http://localhost:8200)
  'SERVER_URL': 'https://127.0.0.1:8200',

  #'SERVER_CERT': './certs/localhost/localhost.crt',
  
  'VERIFY_SERVER_CERT': False,

}
```

*Flask(hello-flask.py)*
```
app.config['ELASTIC_APM'] = {
  'DEBUG': True,
  # Set required service name. Allowed characters:
  # a-z, A-Z, 0-9, -, _, and space
  'SERVICE_NAME': 'flask-hello-service',

  # Use if APM Server requires a token
  'SECRET_TOKEN': '6AC5BF896C915',

  # Set custom APM Server URL (default: http://localhost:8200)
  'SERVER_URL': 'https://localhost:8200',

  #'SERVER_CERT': './certs/localhost/localhost.crt',
  
  'VERIFY_SERVER_CERT': False,
}
```
3. When you run Django or Flask, below error messages was printed periodically.

*Django & Flask*
```
elasticapm.transport.base.TransportException: Unable to reach APM Server: HTTPSConnectionPool(host='127.0.0.1', port=8200): Max retries exceeded with url: /intake/v2/events (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1056)'))) (url: https://127.0.0.1:8200/intake/v2/events)
```

*APM-Server*
```
2020/03/16 17:28:43 http: TLS handshake error from 127.0.0.1:53345: tls: client didn't provide a certificate
2020/03/16 17:28:43 http: TLS handshake error from 127.0.0.1:53347: tls: client didn't provide a certificate
2020/03/16 17:28:43 http: TLS handshake error from 127.0.0.1:53349: tls: client didn't provide a certificate
2020/03/16 17:28:43 http: TLS handshake error from 127.0.0.1:53351: tls: client didn't provide a certificate
```
4. After comment out `client_authentication: 'optional'`, it was working properly.

```
    # Configure which type of client authentication is supported.
    # Options are `none`, `optional`, and `required`. Default is `optional`.
    client_authentication: 'optional'
```

**Expected behavior**: `client_authentication` default setting is `optional` but it has different behavior when explicitly set it up as `optional`. The behavior should be the same as the comment's description and [reference doc's content](https://www.elastic.co/guide/en/apm/server/current/agent-server-ssl.html#_client_authentication).

**Environment (please complete the following information)**
- OS: macOS Mojave 10.14.6(18G3020)
- Python version: Python 3.7.3
- Framework and version: Django (3.0.2), Flask (1.1.1)
- APM Server version: apm-server version 7.6.1 (amd64), libbeat 7.6.1 [3b7823bb329e0e5bfe25e106a3b93e8f61d0451f built 2020-02-28 22:16:31 +0000 UTC]
- Agent version: elastic-apm 5.3.2

**Additional context**
The current setup of `APM Server` w/o issues is described step by step here: https://wiki.elastic.co/display/CC/How+to+setup+the+self-managed+APM+Server

I have long discussion with @beniwohli in [slack](https://elastic.slack.com/archives/C5M04AVJA/p1584088422200100), and he recommended to create this issue on `apm-agent-python` rather than `apm-server` repo! Thank you for your help @beniwohli

**Comment by insukcho** [comment]
it seems `apm-server.ssl.certificate_authorities: ['./certs/ca/ca.crt']` configuration automatically change certificate_authorities to `required`. I missed below comments from [reference](https://www.elastic.co/guide/en/apm/server/current/agent-server-ssl.html#_client_authentication). So that's why `'VERIFY_SERVER_CERT': False` was ignored.

>If certificate_authorities has been specified, this setting will automatically change to required.
>
>required - Requires clients to provide a valid certificate.

**Comment by insukcho** [comment]
One more scenario, if setup `client_authentication: 'required'` or comment out it in `apm-server.yml`, still have the same error message when I put the valid server certificate in Django configuration like below.

```
'SERVER_CERT': './certs/localhost/localhost.crt',
```

Only `client_authentication: 'optional'` in `apm-server.yml` is working for this case.

**Comment by beniwohli** [comment]
Closing this for now. Client certificates are currently not supported by backend agents.
