### ISSUE TITLE
[CI] Enable launch full matrix test on PRs

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-agent-python#762]
We have a job that runs a really long list of frameworks and versions, we run it on a daily basis. In some cases, we need to launch those tests on a PR.
The proposal is to trigger those builds with a GitHub comment ("jenkins run the full test matrix" )

https://apm-ci.elastic.co/job/apm-agent-python/job/apm-agent-python-nightly-mbp/job/master/

**Comment by beniwohli** [comment]
This has been addressed in #767 by @v1v
