### ISSUE TITLE
Flower hangs from version 5.4.0.

### ISSUE THREAD

**Issue by lfrodrigues** [elastic/apm-agent-python#811]
**Describe the bug**: 
Flower hangs (no answer from http connection to browser) when a version >= 5.4.0 is installed

**To Reproduce**

1. pip install elastic-apm==5.4.0
2. restart flower and try to access

**Environment (please complete the following information)**
- OS: Ubuntu 18.04
- Python version: 3.6
- Framework and version: Django 2.2
- APM Server version: NA
- Agent version: 5.4.0+

**Comment by basepi** [comment]
To clarify, you were previously on a version <5.4.0 and had it working? I want to make sure this is a regression as opposed to a long-standing bug.

**Comment by lfrodrigues** [comment]
The last version we had in production was 5.3.2 and it worked fine. From 5.4.0 it hangs.

Please let me know what extra info I can provide to help.

**Comment by basepi** [comment]
Thanks for that update. I'm going to spend some time tomorrow looking into this.

**Comment by basepi** [comment]
Aha! I have this reproduced and think I'm on the road to a fix. Basically, `flower` uses `tornado`, for which we recently added instrumentation. With the way `flower` integrates with Django and Celery, apparently it does get instrumented but not as a `tornado` app, which causes this error:

```
[E 200429 20:19:11 base_events:1296] Exception in callback _HandlerDelegate.execute.<locals>.<lambda>(<Task finishe...pm_client'",)>) at /Users/basepi/.pyenv/versions/3.6.10/envs/djangotest/lib/python3.6/site-packages/tornado/web.py:2333
    handle: <Handle _HandlerDelegate.execute.<locals>.<lambda>(<Task finishe...pm_client'",)>) at /Users/basepi/.pyenv/versions/3.6.10/envs/djangotest/lib/python3.6/site-packages/tornado/web.py:2333>
    Traceback (most recent call last):
      File "/Users/basepi/.pyenv/versions/3.6.10/lib/python3.6/asyncio/events.py", line 145, in _run
        self._callback(*self._args)
      File "/Users/basepi/.pyenv/versions/3.6.10/envs/djangotest/lib/python3.6/site-packages/tornado/web.py", line 2333, in <lambda>
        fut.add_done_callback(lambda f: f.result())
      File "/Users/basepi/.pyenv/versions/3.6.10/envs/djangotest/lib/python3.6/site-packages/elasticapm/instrumentation/packages/tornado.py", line 50, in call
        client = instance.application.elasticapm_client
    AttributeError: 'Flower' object has no attribute 'elasticapm_client'
```

Working on a fix.
