### ISSUE TITLE
[Feature] Option to change key name in set_custom_context

### ISSUE THREAD

**Issue by BuSHari** [elastic/apm-agent-python#815]
Hi,

Can you please add an option to change the key in set_custom_context?
For example:
```python
elasticapm.set_custom_context({'billing_amount': product.price * item_count}, key='extra_data')
```
and it will be under `transaction.extra_data.billing_amount`

**Comment by basepi** [comment]
The main problem with this is that transaction data has a defined (and enforced) schema. You can see the `context` schema here (I've highlighted `custom`): https://github.com/elastic/apm-server/blob/58620f9a8d0a02e4dd3b3b508734d4c712d396c5/docs/spec/context.json#L7-L14

I don't think we'll be able to make it dynamic at that top level, without risking a mapping explosion in Elasticsearch. But remember that you can put arbitrary data under `custom` context, so you could do something like this:

```
elasticapm.set_custom_context({'extra_data': {'billing_amount': product.price * item_count}})
```

That should then be available under `transaction.custom.extra_data.billing_amount`.

**Comment by BuSHari** [comment]
OK, thank you for the explanation...

**Comment by basepi** [comment]
No problem! Sorry for the lack of an ideal solution for you!
