### ISSUE TITLE
when capture_body is false, flask capture_body should not capture body at all

### ISSUE THREAD

**Issue by dvincelli** [elastic/apm-agent-python#816]
A code base I contribute to currently requires reading the `environ['wsgi.input']` stream directly before flask can get to it. When latest Elastic APM 5.5.2 is installed, this stream is empty when the app gets to it. This is because `environ['wsgi.input']` is a read once stream and does not support seek. When the Elastic APM capture_body logic runs, it first reads the stream before deciding if it will include it in the APM report. In my app, this flag is set to the default value of false.

Suggested fix: guard the body capturing logic with the capture_body flag; that is do not take the branch, set the body to '[REDACTED]' right away. 

The capture_body logic I'm referring to is here:

https://github.com/elastic/apm-agent-python/blob/master/elasticapm/contrib/flask/utils.py#L48-L66

Further, I figured out that going back to version 5.2.3 does not cause the wsgi.input stream to be consumed so this change occurred in 5.3.0.

**To Reproduce**

app.py
```
import flask
from flask import request
from elasticapm.contrib.flask import ElasticAPM
from werkzeug.wsgi import get_content_length


app = flask.Flask(__name__)
# Prevent ElasticAPM from contacting APM Server (which is not running on my dev machine)
app.config['ELASTIC_APM'] = {
    'DISABLE_SEND': True,
    'CENTRAL_CONFIG': False,
}
ElasticAPM(app)


@app.route('/', methods=["POST"])
def empty_input():
    length = get_content_length(request.environ)
    if length == 0:
        return "Request Content-Length is 0, you must provide a body", 400
    foo = request.environ['wsgi.input'].read(length)
    read_len = len(foo)
    if read_len != length and read_len == 0:
        return "Empty environ wsgi.input body\n", 500
    else:
        return "OK\n"
```

```
$ gunicorn app:app # using gunicorn because the flask server hangs on the read call for this scenario
```

```
$ curl -d key=foo 127.0.0.1:8000
Empty environ wsgi.input body
```

**Environment**

- OS: Docker image python:3.7-slim
- Python version: 3.7.6
- Framework and version: Flask 1.1.1
- APM Server version: 6.2.4
- Agent version: 5.5.2

**Additional context**

- Agent config options: All default.
- `requirements.txt`:
```
Flask==1.1.1
elastic-apm==5.5.2
blinker==1.4
gunicorn==20.0.4
```

**Comment by beniwohli** [comment]
@dvincelli thanks for the super detailed bug report. We released a fix for this in version 5.6.0 of the agent. Can you verify that it solves the problem for you?

**Comment by dvincelli** [comment]
@beniwohli I'll have a look and let you know. Thanks for the quick turn-around!

**Comment by dvincelli** [comment]
@beniwohli I'm following up to confirm that I tested it locally and this change has solved my problem.

**Comment by beniwohli** [comment]
That's great, thanks for the confirmation!
