### ISSUE TITLE
Redis: Support publish and subscribe methods

### ISSUE THREAD

**Issue by smith** [elastic/apm-agent-python#828]
While running the examples from the blog post [How to instrument a polyglot microservices application with Elastic APM](https://www.elastic.co/blog/how-to-instrument-a-polyglot-microservices-application-with-elastic-apm), I noticed Redis doesn't show up on the service map as being connected to the Python service in this example.

It looks like that's because [according to our documentation we don't have the `publish` and `subscribe` methods instrumented](https://www.elastic.co/guide/en/apm/agent/python/5.x/supported-technologies.html#automatic-instrumentation-db-redis).

If these methods were instrumented we would be able to see Redis on service maps for applications that are using it for pub/sub.

**Comment by basepi** [comment]
Thanks for the request!
