### ISSUE TITLE
APM Agent on K8s take system memory from host

### ISSUE THREAD

**Issue by hramos8** [elastic/apm-agent-python#831]
**Describe the bug**
When using APM agent on Kubernetes cluster, the memory reported in **system.process.memory.size** is incorrect.

To identify this situation whe have the suport of @tanquetav

**To Reproduce**
1. In kibana, search your service metrics:
`service.name : your-service-name and processor.event : metric`
this value is all memory of host.

**Expected behavior**
The correct value of the service.

**Comment by tanquetav** [comment]
When we run containers on k8s, it is as Linux environments. The code to get memory is available here:
https://github.com/elastic/apm-agent-python/blob/master/elasticapm/metrics/sets/cpu_linux.py#L39

It reads memory from /proc/meminfo. Unfortunately this information is not cgroups compliant, and gives the information from host environment. The cgroup  information is available on /sys/fs/cgroup/

```
[george@casa02 apm-agent-dotnet]$ docker run -it --rm -m 500m ubuntu:latest /bin/bash
root@0b787d6c9417:/# cat /proc/meminfo |grep Mem
MemTotal:       16269404 kB
MemFree:          282024 kB
MemAvailable:    4454260 kB
root@0b787d6c9417:/# cat /sys/fs/cgroup/memory/memory.limit_in_bytes
524288000
```

The -m flag tells docker to limit the container to 500Mb, but /proc/meminfo shows 16G. The correct information is available in cgroup environment.

I hope it can help to fix this issue

**Comment by basepi** [comment]
Thanks for the thorough report! We'll get this fixed.
