### ISSUE TITLE
Consider using route information instead of URL for Starlette transactions

### ISSUE THREAD

**Issue by HenrikOssipoff** [elastic/apm-agent-python#833]
We're slowly started using Starlette for some smaller applications due to its simplicity and async capabilities. We also happen to use Elastic APM for our monitoring, but we've found that the agent works quite different from other agents, such as Django or Flask.

The default for Django, is "HTTP Method + path.to.view". This can be changed for Django 2.2+  using the `django-transaction-name-from-route` setting, to instead use the route that was matched against. For example `GET /users/<int:user_id>/`.

For Flask, the default seems to be the that of method + route, e.g.: `GET /users/<int:user_id/`.

For Starlette however, information about the matched route is not actually available on the request, and for that reason (I assume), the full URL is instead used as the transaction name.
In the example above, it would mean that every time a user with a different URL was hit, it would generate two separate transaction entries. For some of our views, that would mean 1+ milllion transaction names for the same view.

However, it is somewhat possible to extract the route by mimicking what Starlette itself does. On the request, the Application itself is available, and from that route router + routes. This means it's possible to loop over them, and match their regular expression against the current request.

1) I realise this isn't pretty in any way, shape or form - but it would make instrumentation of Starlette applications a lot more useable
2) I also realise it's backwards incompatible - but perhaps this could be solved in the same way that it's done with Django?

What would your thought be on such a change?

For us at our workplace, we've actually have one major of our main applications ported to Starlette, but once we saw what was happening to the transaction names, we had to revert the deployment. We'd love to have it running, so we'd probably be interested in providing a patch for it as well.

**EDIT**
Just wanted to add this here, since it's a discussion of making this type of information available in the middleware system: https://github.com/encode/starlette/issues/685
It also links another repo for timing of ASGI that basically does what I describe here, by looping over all routes and comparing them to the current URL.

**Comment by basepi** [comment]
The Starlette support is new enough I'd be willing to entertain a change like this. I would much rather have route information than the full path, but like you mentioned, it's unavailable without manually calculating the route. My only concern with that solution is that it adds some processing overhead. But I do think it would give us more useful transaction names, and hopefully they'll add an official way to get that information in middleware.

@HenrikOssipoff is this a change for which you'd be willing to open a PR?

**Comment by HenrikOssipoff** [comment]
@basepi Definitely, I'll give it a go in the near future. Would enable us to use Starlette much more than we currently do :)

**Comment by bejoinka** [comment]
Question for the group here... tagging onto this thread because I think it may be related:

Am I correct in thinking route discovery is currently the best way to handle a pipeline of middleware for a given route or group of routes?

A little backdrop... I am thinking about the equivalent of a policies.js file in nodejs, where you may build a pipeline of checks for a given request:
`
admin_policies = [https_redirect, is_logged_in, is_admin]
`
`
user_policies = [https_redirect, is_logged_in] 
`

Then somewhere later I'll assign those functions/routes to those policies so anyone who hits that route goes through that same pipeline.

I've found this kind of structure quite nice, and while fastAPI is micro and may expect someone else to plug into it (which is fine), I'm curious if anyone has approached something similar... and if so, how?

**Comment by basepi** [comment]
@HenrikOssipoff Is this a change you're still interested in contributing?

**Comment by BrikerMan** [comment]
> @HenrikOssipoff Is this a change you're still interested in contributing?

There is a solution mentioned here https://github.com/tiangolo/fastapi/issues/486#issuecomment-526892238, but it needs to iterate through all the routes for each request.

```python
path = [route for route in request.scope['router'].routes if route.endpoint == request.scope['endpoint']][0].path
```

**Comment by basepi** [comment]
Thanks. I think that's probably worthwhile overhead, the current implementation isn't super great.

**Comment by BrikerMan** [comment]
> Thanks. I think that's probably worthwhile overhead, the current implementation isn't super great.

Can't wait for the new version. Maybe we can make it an optional choice via an env variable.

**Comment by basepi** [comment]
I'm honestly still leaning towards just making the change without backwards compatibility considerations. The starlette support is very new and the current behavior could probably be considered a bug. Thoughts?

**Comment by BrikerMan** [comment]
> I'm honestly still leaning towards just making the change without backwards compatibility considerations. The starlette support is very new and the current behavior could probably be considered a bug. Thoughts?

In my use case, I am happy to fix this one a bug. I don't need old behavior.

**Comment by HenrikOssipoff** [comment]
> @HenrikOssipoff Is this a change you're still interested in contributing?

Sorry very late to the game - I can see @beniwohli has assigned himself, which is more than fine by me. Work's not leaving me much free time unfortunately.

Looking forward to the "fix" though - sorry for being slow here.

Personally I would say you shouldn't think about backwards compatibility for this one, given most likely very few people even use this particular integration, but that's my opinion alone.

**Comment by beniwohli** [comment]
@HenrikOssipoff I opened #957 with (hopefully) a fix for this. If you have time, would you mind giving that a quick spin and see if it works?

I agree that backwards compatibility is not a major concern. I would consider the current behavior as buggy compared to our other integrations.

**Comment by HenrikOssipoff** [comment]
@beniwohli Sweet I'll take it for a spin later tonight to test things out :)
