### ISSUE TITLE
Add ENV var to disable proxy completely

### ISSUE THREAD

**Issue by thenewguy** [elastic/apm-agent-python#839]
It would be very helpful for integration testing if there was an environment variable that could be set to disable the use of a proxy.  NO_PROXY='*' doesn't seem to be working.  Currently testing using docker and linking all containers together via links - however, the agent is reaching out to access via proxy set on the local workstations and making development quite difficult

-- edit --
just for clarification - noproxy case is set like this:
    no_proxy='\*'
    NO_PROXY='\*'

**Comment by thenewguy** [comment]
So determined that no_proxy was being overwritten by the test runner.  * does work. 

I.e. this output from printenv let the agent connect:
```
no_proxy=*
NO_PROXY=*
ELASTIC_APM_SERVER_URL=http://172.17.0.1:32787
```

Any idea why this one does not?
```
no_proxy=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,localhost,127.0.0.1,elasticsearch
NO_PROXY=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,localhost,127.0.0.1,elasticsearch
ELASTIC_APM_SERVER_URL=http://172.17.0.1:32792
```

**Comment by thenewguy** [comment]
I am going to close this.  Seems like some software respects CIDR and other doesn't.  Doesn't seem to have a standard interpretation so it is probably wrong either way

**Comment by beniwohli** [comment]
@thenewguy just as a quick follow up, we're using Python's built-in functions to determine if a host matches `NO_PROXY`. The function isn't documented as far as I can tell, but the source code is here:

https://github.com/python/cpython/blob/28316422124206f63ddd4b91f2e19c54b6e9cd9d/Lib/urllib/request.py#L2513-L2545
