### ISSUE TITLE
Make SANITIZE_FIELD_NAMES constant configurable for custom headers

### ISSUE THREAD

**Issue by AumitLeon** [elastic/apm-agent-python#841]
**Is your feature request related to a problem? Please describe.**
It would be nice to have the option to extend the list of field names that are considered when sanitizing HTTP headers. This is especially useful if you have custom headers with sensitive data.

**Describe the solution you'd like**
A function that lets a user provide header(s) that extend the base `SANITIZE_FIELD_NAMES` set, such that using the `sanitize_http_headers` processor will also sanitize the headers passed by the user.

**Describe alternatives you've considered**

1. The simplest workaround could just be to write a custom processor and sanitize custom headers yourself, but this feels like a misuse of the library. If there's a function meant to sanitize headers, makes sense to use it.
2. It's also potentially possible to write a custom processor that wraps `sanitize_http_headers` and monkey patch `SANITIZE_FIELD_NAMES` to include the custom headers you want sanitized. Again, doesn't seem ideal.

**Additional context**

**Comment by basepi** [comment]
This seems reasonable, and is in line with what [other](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-sanitize-field-names) agents are doing(https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-core.html#config-sanitize-field-names).

Thanks for the request!

**Comment by basepi** [comment]
(Note to self, this should support wildcards to match with .NET and Java. .NET tests are available [here](https://github.com/elastic/apm-agent-dotnet/blob/master/test/Elastic.Apm.Tests/WildcardMatcherTests.cs#L11))
