### ISSUE TITLE
Add log level in the metadata

### ISSUE THREAD

**Issue by esseti** [elastic/apm-agent-python#858]
We are using the django integration with APM.
it would be useful to add the log level for the messages.
eg log.warning -> level:warning
eg log.error -> level:erorr
```
'handlers': {

    'elasticapm': {
            'level': 'WARNING',
            'class': 'elasticapm.contrib.django.handlers.LoggingHandler',
        },
}
...
    'loggers': {
       'mylog': {
            'handlers': ['console','elasticapm'],
            'level': 'DEBUG',
            'propagate': True
        },
}
```

right now there's no way to get if the log was a warning or an error

**Comment by beniwohli** [comment]
Hi @esseti 

You can find the log level in the `error.log.level` of the error document in Elasticsearch. However, it indeed doesn't look like this information is visible anywhere in the APM app. I'll ask our UI team and get back to you.

**Comment by beniwohli** [comment]
@esseti we have an issue for this in Kibana now, https://github.com/elastic/kibana/issues/68748

I'll close this issue as the agent is already sending all the relevant information. Make sure to subscribe to the Kibana issue if you want to follow along with the progress.
