### ISSUE TITLE
Python APM agent only sends first HTTP body, rest are [REDACTED]

### ISSUE THREAD

**Issue by alexchowle** [elastic/apm-agent-python#868]
Using `elastic-apm[flask]==5.4.2`

Have config item `CAPTURE_BODY` set to `all`

Only the first Transaction provides the HTTP Body to APM. All subsequent Transactions are marked as [REDACTED].

**Comment by basepi** [comment]
@alexchowle Thanks for the report! Are you utilizing remote configuration from kibana? I wonder if it's getting overwritten there?

**Comment by alexchowle** [comment]
You're 100% corrent. Thank you.
