### ISSUE TITLE
Traces are being scrambled between transactions

### ISSUE THREAD

**Issue by HenrikOssipoff** [elastic/apm-agent-python#872]
**Describe the bug**
I'm not entirely sure how to go about this, since I'm not able to reproduce this bug in a specific manner.

The gist is that we're seeing traces from completely non-related transactions appear together in APM.

This is maybe best shown with an image:

![apm](https://user-images.githubusercontent.com/4737224/85865167-c46adf00-b7c5-11ea-8326-ff2b91fad3bf.png)

In this case, the `TerminalViewSet` seems to be using the `refunds_refund` table. However, this code is actually from a _different_ view, and not `TerminalViewSet`.

We're seeing quite a few of these per day.

I'm assume it's because there's an overlap between transaction IDs somewhere?

**To Reproduce**

Unknown

**Environment (please complete the following information)**
- OS: Docker image `python:3.8.2-buster`
- Python version: 3.8.2
- Framework and version [e.g. Django 2.1]: Django 3.0.7
- APM Server version: 7.6.1
- Agent version: 5.7.0

**Additional context**
I'll be happy to provide any additional information - I'm just not sure what's relevant for you...

**Comment by basepi** [comment]
This is a weird one! The running transaction is propagated via contextvars, for python 3.7+. I suppose it's possible that there could be a bug there, that's the only way off the top of my head that I could see an incorrect transaction being tied to spans.

Is there a chance that `TerminalViewSet` could be calling the other view, and we're just missing those connecting spans for some reason? The only reason I could see for a shared transaction ID across views is if we're propagating that transaction via headers. But if that were the case I would expect to see a span for that call... I'm grasping at straws.

I have to admit that my first intuition is that this is user error. This isn't a judgment on you, just [Occam's Razor](https://en.wikipedia.org/wiki/Occam%27s_razor). Tying spans to transactions is so core to what we do, so I'd be surprised to find a major bug that only one user noticed. I'd love it if you could check for any possibility of interaction between that view and that table, just for my sanity.

Once you've ruled that out, I guess I'd like to see the raw transaction and spans involved, redacted for anything sensitive, so I can see if anything stands out. I'll take a look next week.

**Comment by HenrikOssipoff** [comment]
@basepi Thanks for the swift reply.

From a quick grep, I find no references to the refund model/table in this Django Rest Framework ViewSet, it's serializer or the corresponding model manager. However, I'll do a thorough look through the logic early next week when I'm back at work.
My first instinct as well would be a user error. Especielly because I've mainly seen the issues on this particular view.
The trace is an interesting one in general; if I'm looking at it, it would look like it's a mix of all sorts of other views (there's multiple--20 ish--calls to the auth token table from Django Rest Framework for instance). But I've (so far) only noticed it in this view.

For the record, we're deploying this application with gunicorn, 2 workers and default worker class.

If I don't find any correlation between the table and the view, could you elaborate a tiny bit on which indices you'd like to see data from? I'm not too much into the actual underlying way the APM data is organised in their Elasticsearch indices.

**Comment by HenrikOssipoff** [comment]
@basepi Damn I feel stupid now. I've found the issue, and it is (of course) a user error.

I likely wouldn't have found it if it wasn't for you though (thanks for being my virtual rubber duck here).

We have a Filter class defined (using django-filters), that is really hacky. It basically dynamically creates a choices tuple - in the class definition. So I'm guessing for this particular application, these traces are scattered across all of our transactions, on each initial load after our application has been restarted.

I'm very sorry to have taken your time here - but thanks once again!

**Comment by basepi** [comment]
Hey, no worries! I'm mostly just relieved, this sounded like it was going to be terrible to debug! :)

Glad we found the issue. Always happy to be a rubber duck.
