### ISSUE TITLE
Reporting and showing cgroup-based metrics

### ISSUE THREAD

**Issue by beniwohli** [elastic/apm-agent-python#876]
See https://github.com/elastic/apm/issues/291 for implementation details

**Comment by tanquetav** [comment]
I already implemented  this issue in this PR: 
https://github.com/elastic/apm-agent-python/pull/846

Issue refer: https://github.com/elastic/apm-agent-python/issues/831

I already implemented this on a java, with  @eyalkoren supervision  and recoded this to python on that PR.
