### ISSUE TITLE
dictionary changed size during iteration

### ISSUE THREAD

**Issue by mrkiril** [elastic/apm-agent-python#882]
Same problem to https://github.com/elastic/apm-agent-python/issues/717

```
  File "/elasticapm/base.py", line 180, in <lambda>
    local_var,
  File "/elasticapm/utils/__init__.py", line 64, in varmap
    ret = func(name, dict((k, varmap(func, v, context, k, **kwargs)) for k, v in compat.iteritems(var)), **kwargs)
  File "/elasticapm/utils/__init__.py", line 64, in <genexpr>
    ret = func(name, dict((k, varmap(func, v, context, k, **kwargs)) for k, v in compat.iteritems(var)), **kwargs)

RuntimeError: dictionary changed size during iteration
```

Environment (please complete the following information)

OS: Ubuntu 20.04 stable
Python version: 2.7.18
Framework and version Django 1.3
APM Server version: 7.6.0
Agent version: 5.8

**Comment by beniwohli** [comment]
Hi @mrkiril 

Good catch! The solution from #717 should also work in this case. I'll open a PR.
