### ISSUE TITLE
Move certifi to an optional dependency

### ISSUE THREAD

**Issue by gatos-cc** [elastic/apm-agent-python#922]
**Describe the bug**: ...

https://github.com/elastic/apm-agent-python lists the license as `BSD-3-Clause`.  However https://pypi.org/project/liccheck/ reports that it pulls in `certifi` which has an MPL license:
```
1 package.
    certifi (2020.6.20): ['Mozilla Public License 2.0 (MPL 2.0)', 'MPL-2.0']
      dependency:
          certifi << elastic-apm
```

My understanding of the MPL is that it is a copy-left license, which means it should have to appear in the larger work's license notification.  If that's the case, that's also problematic for us since the agent has to be built into the source code, and we can't have copy left licenses like GPL/LGPL in there.

**To Reproduce**

1. create a requirements.txt file with nothing but `elastic-apm[flask]` in it
2. create an authorized-licenses.ini file that allows MIT and BSD licenses:
```
[Licenses]
authorized_licenses:
  mit
  bsd

unauthorized_licenses:

[Authorized Packages]

```
3. create a simple Dockerfile:
```
FROM amazonlinux:2018.03

RUN yum update -y && \
    yum install -y python27 python27-devel.x86_64 && \
    yum install -y wget && \
    wget https://bootstrap.pypa.io/get-pip.py && \
    python27 get-pip.py && \
    pip install liccheck && \
    pip install elastic-apm[flask]

COPY ./ ./

RUN liccheck -s authorized-licenses.ini -r requirements.txt -l Paranoid
```
4. Run Docker build:
```
docker build .
```

Result:
```
gathering licenses...
5 packages and dependencies.
check authorized packages...
4 packages.
check unknown packages...
1 package.
    certifi (2020.6.20): ['Mozilla Public License 2.0 (MPL 2.0)', 'MPL-2.0']
      dependency:
          certifi << elastic-apm
The command '/bin/sh -c liccheck -s authorized-licenses.ini -r requirements.txt -l Paranoid' returned a non-zero code: 255
```

**Environment (please complete the following information)**
- OS: Linux
- Python version: 2.7
- Framework and version [e.g. Django 2.1]: Flask
- APM Server version:
- Agent version:

**Additional context**

- `requirements.txt`:
  <details>
    <summary>Click to expand</summary>

    ```
    elastic-apm[flask]
    ```
  </details>

**Comment by jfitz1** [comment]
+1

**Comment by basepi** [comment]
@gatos-cc Thanks for the question!

Let me preface this with the standard "I am not a lawyer" caveat. :) But here goes!

MPL 2.0 is quite a bit different than other copy-left licenses, in that it's "file-level", as opposed to "library level" (LGPL) or "software level" (GPL). This means that it's only copy-left for modifications to the MPL-licensed source code files. The only requirement for distributing the source code is that users are informed where they can get a copy of the source code for the MPL-licensed pieces.

Because we don't modify `certifi` in any way, it's completely compatible with our BSD 3-clause license, and our agent can be embedded in proprietary software without any issues with license compatibility. In fact, we don't technically even distribute `certifi`, we just use the distribution from pypi, unchanged. This means that, as far as I can tell, we are even exempt from section 3.2(a), the "inform the user" requirement mentioned above.

The FAQ for the MPL 2.0 license is incredibly helpful: https://www.mozilla.org/en-US/MPL/2.0/FAQ/

I particularly recommend Q1, Q11, Q12, and Q13.

I should note that based on that FAQ, MPL 1.1 was less compatible and probably would be problematic, but since `certifi` is MPL 2.0 I think we're in the clear.

Keep me posted if you have further questions.

**Comment by gatos-cc** [comment]
For sure - I'm no lawyer either, and the language of MPL has us twisting around quite a bit.  Basically the root level CA certs are curated by Mozilla, so that master pem file has an MPL 2.0 license on it - as near as I can tell, just about everyone from Firefox to Chrome to Linux uses it.  Certifi just takes that and bundles it up into a library so you can dump it to a known location on disk for your program to use.

If we just read that pem file in from disk as a data file, I think we'd be fine - you're just giving it as an option where someone *could* use something else.  But certifi itself has also declared itself as MPL 2.0, so the library that's getting pulling into the source code build is in the final distribution.  I.e. I don't think it's simply a data file anymore, it's part of the larger work.  See https://opensource.stackexchange.com/a/8061/20524 .  So I **_think_** anything that uses certifi in the final distribution needs to provide notice and access to the source code.  But I'd be happy to be proven wrong with a little more warm fuzzy certainty around it.

Basically we're relying on a license checker to enforce compliance to a "no copy left dependencies" requirement.  Our requirements file pulls in elastic-apm[flask], which in turn pulls in certifi - and pretty much all the license checkers complain about an MPL dependency at that point.

As an alternative, on this line:
    https://github.com/elastic/apm-agent-python/blob/d98f812d5f2c560671cee2c374f05d6c408feafb/elasticapm/transport/http.py#L53
if we just allowed a user to specify the location on disk of a pem file, they could use the CA certs included with pretty much any operating system (e.g. /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem on CentOS), any browser, or running certifi.where() on their own - that would get rid of the dependency on certifi altogether.

I also feel like that may be safer - relying on the OS level certificates should get updated relatively frequently if admins are keeping up on system/security patches, while certifi is more or less maintained by "a guy" and would require someone to rebuild/redeploy the application.

**Comment by beniwohli** [comment]
Hey @gatos-cc 

also not a lawyer here, but just to be sure I asked our lawyers to have a look if there's anything iffy about us depending on an MPL-2 licensed project.

We did get requests to have the certificate location as a configuration option in the past. Also, our dependency on certifi comes from a much darker time (at least when it comes to SSL and Python). These days, urllib3 is pretty good at finding the OS-provided certificate store, so we could potentially think about making certifi an optional dependency. 

However, I think this could be considered a breaking change, so I'd vote for doing this in the next major version (6.0, which we plan to release sometime this year, and will also drop compatibility with Python 2.7)

**Comment by gatos-cc** [comment]
Thanks @beniwohli .  Sounds reasonable.  In the meantime I may run a forked version that forces the cert location.

**Comment by beniwohli** [comment]
@gatos-cc our plan changed a bit, since we've since noticed that especially in Docker images based on Debian, the default certificate bundle is often not available.

So, instead of removing certifi altogether, we'll make the [import](https://github.com/elastic/apm-agent-python/blob/d2dc959d825c29c32d4adf2c017c897c2b199004/elasticapm/transport/http.py#L38) conditional, and set `ca_certs` to `None` ([here](https://github.com/elastic/apm-agent-python/blob/d2dc959d825c29c32d4adf2c017c897c2b199004/elasticapm/transport/http.py#L54)) if the import fails. While `pip install elastic-apm` will still download certifi, you'll be able to call `pip uninstall certifi` right after, and then the agent will fall back to the OS-bundled certificate store.

**Comment by beniwohli** [comment]
closed in #1016

**Comment by gatos-cc** [comment]
@beniwohli  I understand where you guys went with this, but just for my 2 cents it doesn't address our core issue which is compliance testing/verification.

I understand that we can delete the library after the fact, but the problem is that most compliance checkers will pick up that certifi is required, and then fail the test, end of story.  You don't get to argue with those libraries/auditors much about how you're fixing it later.

Really for us, the problem comes down to the following minimally reproducible setup:
Dockerfile:
```
FROM centos:7

RUN echo "------------------- Updating System Software -------------------" && \
    yum update -y && \
    yum install -y python3 python3-devel.x86_64 git gcc wget curl unzip

RUN echo "------------------- Installing PIP -------------------" && \
    mkdir -pv /usr/src/pip && \
    cd /usr/src/pip && \
    wget https://bootstrap.pypa.io/pip/3.6/get-pip.py && \
    python3 --version && \
    python3 get-pip.py

RUN mkdir -pv /usr/src/api
WORKDIR /usr/src/api

COPY ./requirements.txt /usr/src/api/requirements.txt
RUN echo "------------------- Installing Requirements -------------------" && \
    pip install -r requirements.txt --no-cache-dir

COPY ./authorized-licenses.ini /usr/src/api/authorized-licenses.ini
RUN echo "------------------- Checking dependency licenses -------------------" && \
    pip install liccheck && \
    liccheck -s authorized-licenses.ini \
             -r requirements.txt \
             -l Paranoid \
             -R check.out && \
    cat check.out
```

(requirements.txt)
```
elastic-apm[flask]
```

(authorized-licenses.txt)
```
[Licenses]
authorized_licenses:
    apache 2.0
    apache software
    apache license 2.0
    apache license, version 2.0
    bsd
    bsd-3-clause
    bsd-like
    bsd or apache license, version 2.0
    mit
    mit license
    psf
    python software foundation

unauthorized_licenses:
    agplv3.0
    gnugplv3
    gpl
    gpl v2
    gpl v3
    gnu lgpl
    lgpl
    lgpl with exceptions or zpl
    lgplv3
    lgplv2.1

[Authorized Packages]

```

output:
```
% docker build --progress=plain -t tmp:foo .
#2 [internal] load .dockerignore
#2 DONE 0.0s
...
#13 [9/9] RUN echo "------------------- Checking dependency licenses -------...
#13 0.248 ------------------- Checking dependency licenses -------------------
#13 0.991 Collecting liccheck
#13 1.088   Downloading liccheck-0.6.5-py2.py3-none-any.whl (12 kB)
#13 1.173 Collecting semantic-version>=2.7.0
#13 1.202   Downloading semantic_version-2.9.0-py2.py3-none-any.whl (15 kB)
#13 1.278 Collecting configparser
#13 1.303   Downloading configparser-5.2.0-py3-none-any.whl (19 kB)
#13 1.360 Collecting toml
#13 1.382   Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
#13 1.534 Installing collected packages: toml, semantic-version, configparser, liccheck
#13 1.624 Successfully installed configparser-5.2.0 liccheck-0.6.5 semantic-version-2.9.0 toml-0.10.2
#13 1.624 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#13 2.276 gathering licenses...
#13 2.276 4 packages and dependencies.
#13 2.276 check authorized packages...
#13 2.276 3 packages.
#13 2.276 check unknown packages...
#13 2.276 1 package.
#13 2.276     certifi (2021.10.8): ['Mozilla Public License 2.0 (MPL 2.0)']
#13 2.276       dependency:
#13 2.276           certifi << elastic-apm
#13 ERROR: executor failed running ... runc did not terminate sucessfully
```

If the license checker doesn't pass, I can't use the library.

**Comment by gatos-cc** [comment]
(and sorry for the long delay - I had given up on things long ago, and came back today to see if I could try again)

**Comment by gatos-cc** [comment]
@basepi yeah... that's effectively what I've been doing (I forked the repository).  It just means I'm on the hook to patch it any time there's an update, which if I'm being honest really means it'll never get updates until it fundamentally breaks somehow.

I actually meant to ask specifically about a new target like `elastic-apm[flask-no-certifi]` or something, but I haven't had time to dig into what that would mean.  Sounds like it would still run afoul of a checker.

I dunno - I guess if you can keep the idea somewhere on a backlog in case you have an epiphany, I'd appreciate it.  Otherwise I'll likely just keep going with my fork, unless I find some time to dig in another level.
