### ISSUE TITLE
ElasticAPM 5.5.2 - Regression on pymongo

### ISSUE THREAD

**Issue by ca-simone-chiorazzo** [elastic/apm-agent-python#934]
**Describe the bug**: 
Using pymongo 2.8 and elasticapm 5.5.2 we have the following error:

File /usr/local/lib/python2.7/site-packages/elasticapm/instrumentation/packages/base.py line 210 in call_if_sampling
return self.call(module, method, wrapped, instance, args, kwargs)
File /usr/local/lib/python2.7/site-packages/elasticapm/instrumentation/packages/pymongo.py line 77 in call
host, port = list(nodes)[0]
File /usr/local/lib/python2.7/site-packages/pymongo/collection.py line 1759 in next args locals
raise TypeError("'Collection' object is not iterable")

The query executed is a: db.collection.update

It seems to me that the problem has been introduced by a bugfix on the 5.5.2 about pymongo https://github.com/elastic/apm-agent-python/commit/50d4651be83ebeb08066f0fa391c956c5c7be83b#diff-71a7ec87c5a7159cf6576c0342bf5ba3

**To Reproduce**

1. ...
2. ...
3. ...
4. ...

**Environment (please complete the following information)**
- OS: Linux
- Python version: 2.7.18
- Framework and version [e.g. Django 2.1]: Django 1.11
- APM Server version: 
- Agent version:5.9.2

**Additional context**

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your agent config options
    remember to mask any sensitive fields like tokens
    ```
  </details>
- `requirements.txt`:
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your `requirements.txt`
    ```
  </details>

**Comment by beniwohli** [comment]
Hey @ca-simone-chiorazzo 

We only support [pymongo 2.9+](https://www.elastic.co/guide/en/apm/agent/python/current/supported-technologies.html#automatic-instrumentation-db-mongodb). If it used to work with earlier versions, that was coincidental. Can you try to use a newer version of pymongo?

**Comment by ca-simone-chiorazzo** [comment]
Hi @beniwohli , thanks for the quick response. We gonna try with pymongo 2.9 and we'll let you know the result

**Comment by ca-simone-chiorazzo** [comment]
@beniwohli It worked. I close the issue. Thanks a lot for the help!
