### ISSUE TITLE
Agent produces empty field names 

### ISSUE THREAD

**Issue by gingerwizard** [elastic/apm-agent-python#95]
Version 6.0 rc 1

I see fields like this being indexed

```
"cookies": {
    "Max-Age": "86400",
    "Path": "/",
    "sessionid": "mdoieddd6stjvfm3obprohg8ebam8xpc",
    "expires": "Tue, 07-Nov-2017 12:01:27 GMT",
    "": "HttpOnly",
    "csrftoken": "mvy4wo38fXRwGmPwQn7huElMvDhRn9Hk"
    }
```

I'm alittle unsure how these are successfully indexed as this object should be rejected. Attempting to index these objects containing this structure results in an error.

**Comment by roncohen** [comment]
Looks like there's a mix of properties for the cookie (`Max-age` and `Path`) and actual cookies (`sessionid`, `csrftoken`)

**Comment by beniwohli** [comment]
Probably a bug in our cookie parsing. it splits 

    sessionid=mdoieddd6stjvfm3obprohg8ebam8xpc; expires=07-Nov-2017 12:01:27 GMT HttpOnly

up when it shouldn't

**Comment by beniwohli** [comment]
Turns out the workload script sends an invalid `Cookie` header. It currently just gets the `Set-Cookie` header from the response, and re-uses it as the `Cookie` header. These two headers have different formatting, but not different enough to fail catastrophically. Django's cookie parser code returns an eerily familiar result:

    In [1]: from django.http.cookie import parse_cookie

    In [2]: parse_cookie("csrftoken=********; expires=Mon, 05-Nov-2018 12:35:24 GMT; Max-Age=31449600; Path=/; sessionid=********; expires=Tue, 07-Nov-2017 12:35:24 GMT; HttpOnly; Max-Age=86400; Path=/")
    Out[2]:
    {'': 'HttpOnly',
     'Max-Age': '86400',
     'Path': '/',
     'csrftoken': '********',
     'expires': 'Tue, 07-Nov-2017 12:35:24 GMT',
     'sessionid': '********'}

@watson as the author of workload, do you have any idea how to handle cookie management correctly? Here's the workload script: https://github.com/elastic/demos/blob/master/cyclops/docker_loadgen/src/worker.js

**Comment by gingerwizard** [comment]
So the reason the data failed to index for me was the APM mapping wasn't applied when i tried to restore the data. For  data from beats, where dynamic mappings might be k, the APM mapping is essential - there are parts of the docs which are defn likely to be invalid with respect to Elasticsearch e.g. empty field names, and for which the agent has no control (as shown by @beniwohli above). This really isn't an issue for most users, but it should be made clear mapping changes with APM data is probably something you should undertake with extreme care. I can see users enabling indexing on certain parts of the hierarchy to extract metrics - something they need to do with caution.

**Comment by watson** [comment]
The Workload module does not contain a cookie jar, so if it receives a `Set-Cookie` header from the server, it doesn't do anything about it. This can done in user-land by checking for the `Set-Cookie` header on the `visit` event and then making sure to set the appropriate `Cookie` header in for instance a filter.

**Comment by beniwohli** [comment]
@watson something similar is happening already AFAICT (the `Set-Cookie` header is reused as `Cookie` header). Guess something like https://www.npmjs.com/package/set-cookie-parser could be used to convert the `Set-Cookie` header into a `Cookie` header?

(I was hoping for a nice cookiejar hook in workload 😁 )

**Comment by jamiesmith** [comment]
It was in fact just sending back the `Set-Cookie` as the `Cookie`, which is what we thought would work. A cookie jar would be nice, but I am rotating through ~100 users to simulate traffic.  After some serious digging, it appears that the load-gen should just be sending the cookie names and values, and not the other options.  A sanity check in curl against the same server yielded:


(all redacted)
Initial Request:

```console
$ >rm -f cookies && curl -v -b cookies -c cookies -I http://localhost:8000/
*   Trying 192.168.1.60...
* TCP_NODELAY set
* Connected to localhost (192.168.1.60) port 8000 (#0)
> HEAD / HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.54.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
HTTP/1.0 200 OK
Date: Thu, 09 Nov 2017 19:53:02 GMT
Server: WSGIServer/0.2 CPython/3.5.2
X-Frame-Options: SAMEORIGIN
Vary: Accept-Language, Cookie
Content-Language: en
Content-Type: text/html; charset=utf-8
Set-Cookie:  csrftoken=zz-CSRFTOKEN-zz; expires=Thu, 08-Nov-2018 19:53:02 GMT; Max-Age=31449600; Path=/
Set-Cookie:  sessionid=zz-SID-SID-SID-zz; expires=Fri, 10-Nov-2017 19:53:02 GMT; HttpOnly; Max-Age=86400; Path=/
```

the resulting cookies file:

```console

jamie@orion[14:53:02]:~/Projects/GitRepo/demos/cyclops/docker_loadgen/src $ >cat cookies 
# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

localhost	FALSE	/	FALSE	1541706782	csrftoken	zz-CSRFTOKEN-zz
#HttpOnly_localhost	FALSE	/	FALSE	1510343582	sessionid	zz-SID-SID-SID-zz
```

second run:
```console

jamie@orion[14:53:19]:~/Projects/GitRepo/demos/cyclops/docker_loadgen/src $ >curl -v -b cookies -c cookies -I http://localhost:8000/
*   Trying 192.168.1.60...
* TCP_NODELAY set
* Connected to localhost (192.168.1.60) port 8000 (#0)
> HEAD / HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.54.0
> Accept: */*
> Cookie: csrftoken=zz-CSRFTOKEN-zz; sessionid=zz-SID-SID-SID-zz
> 
* HTTP 1.0, assume close after body
HTTP/1.0 200 OK
Date: Thu, 09 Nov 2017 19:55:00 GMT
Server: WSGIServer/0.2 CPython/3.5.2
X-Frame-Options: SAMEORIGIN
Vary: Accept-Language, Cookie
Content-Language: en
Content-Type: text/html; charset=utf-8
* Replaced cookie csrftoken="zz-CSRFTOKEN-zz" for domain localhost, path /, expire 1541706900
Set-Cookie:  csrftoken=zz-CSRFTOKEN-zz; expires=Thu, 08-Nov-2018 19:55:00 GMT; Max-Age=31449600; Path=/
* Replaced cookie sessionid="zz-SID-SID-SID-zz" for domain localhost, path /, expire 1510343700
Set-Cookie:  sessionid=zz-SID-SID-SID-zz; expires=Fri, 10-Nov-2017 19:55:00 GMT; HttpOnly; Max-Age=86400; Path=/
```

So I will make it only send the name/value

**Comment by jamiesmith** [comment]
We should note that the cookie parsing should still be verified for when the agent is used in a server capacity- httponly and secure are valid attributes for server cookies- what I learned is that their presence implies a value of true (httponly=true).

**Comment by beniwohli** [comment]
@jamiesmith the [`Cookie`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie) request header doesn't define `httponly` or any other fields except for the key/value pairs. These are only available in the [`Set-Cookie`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) response header. These two headers have a completely different syntax, and one cannot interchange them.

As such, I don't see what the agent could do when the wrong format is used in the `Cookie` header. We rely on the underlying framework (Flask/Werkzeug or Django) to decode the `Cookie` header, and even these two frameworks behave differently when presented with a `Set-Cookie` header:

    In [1]: from werkzeug.http import parse_cookie

    In [2]: parse_cookie("csrftoken=********; expires=Mon, 05-Nov-2018 12:35:24 GMT; Max-Age=31449600; Path=/; sessionid=********; expires=Tue, 07-Nov-2017 12:35:24 GMT; HttpOnly; Max-Age=86400; Path=/")
    Out[2]:
    {'HttpOnly; Max-Age': '86400',
     'csrftoken': '********',
     'sessionid': '********'}

    In [3]: from django.http.cookie import parse_cookie

    In [4]: parse_cookie("csrftoken=********; expires=Mon, 05-Nov-2018 12:35:24 GMT; Max-Age=31449600; Path=/; sessionid=********; expires=Tue, 07-Nov-2017 12:35:24 GMT; HttpOnly; Max-Age=86400; Path=/")
    Out[4]:
    {'': 'HttpOnly',
     'Max-Age': '86400',
     'Path': '/',
     'csrftoken': '********',
     'expires': 'Tue, 07-Nov-2017 12:35:24 GMT',
     'sessionid': '********'}

Closing this as I don't see any needed action on the agent side. Feel free to re-open if you don't agree :)
