### ISSUE TITLE
ELASTIC_APM_RECORDING default value

### ISSUE THREAD

**Issue by cmontanaro** [elastic/apm-agent-python#953]
**Describe the bug**: 

Documentation states that the default value of ELASTIC_APM_RECORDING is false but default is set to true in code

**To Reproduce**

% grep -r RECORDING *
docs/configuration.asciidoc:| `ELASTIC_APM_RECORDING` | `RECORDING`    | `false`
elasticapm/conf/__init__.py:    recording = _BoolConfigValue("RECORDING", default=True)

**Comment by beniwohli** [comment]
@cmontanaro great catch! I opened #955 with the fix.
