### ISSUE TITLE
Add a new function to the public api returning the current trace parent header.

### ISSUE THREAD

**Issue by diegosperes** [elastic/apm-agent-python#954]
**Is your feature request related to a problem? Please describe.**

Currently I am instrumenting a kafka consumer that receive a message containing the trace parent header to after begin a new transaction passing the `TraceParent` instance on `begin_transaction` method of `Client` class. The issue remains in the ability of easily get the current trace parent header in the service that is publishing a kafka message, for that is necessary to dig into this project, understanding how trace parent header is generated.

**Describe the solution you'd like**
Create a public function that retrieve the trace parent header of the current transaction.

**Describe alternatives you've considered**
Improve the documentation to explicitly show how to generate a trace parent header of the current transaction.

```
from elasticapm.traces import execution_context

transaction = execution_context.get_transaction().
trace_parent_header = transaction .trace_parent.to_string() if transaction and transaction.trace_parent else None
```

**Comment by basepi** [comment]
Implemented in #956
