### ISSUE TITLE
'FragmentDefinition' object has no attribute 'operation'"

### ISSUE THREAD

**Issue by JannikZed** [elastic/apm-agent-python#966]
**Describe the bug**: 
I'm using elastic APM with Django 3.1.2 and graphql.
On every GraphQL Query, I'm seeing now this error: `AttributeError: 'FragmentDefinition' object has no attribute 'operation'`

The relevant file is: `elasticapm/instrumentation/packages/graphql.py in get_graphql_tx_name at line 99`

**To Reproduce**
I'm not sure yet, why the error is occurring and I'm just getting started with the service. If you can guide me to the right direction, I can create a reproducible example.

**Environment (please complete the following information)**
- OS: Linux docker Container
- Python version:
- Framework and version : Django 3.1.2
- APM Server version: 
- Agent version: 5.9.0

**Additional context**

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your agent config options
    remember to mask any sensitive fields like tokens
    ```
  </details>
- `requirements.txt`:
  <details>
    <summary>Click to expand</summary>

    ```
    replace this line with your `requirements.txt`
    ```
  </details>

**Comment by JannikZed** [comment]
because of this error, all requests to my django app fail! .. so this is actually the worst case - the APM agent is killing a production service :(

**Comment by beniwohli** [comment]
Hi @JannikZed. Sorry about the issues you are having. Would you mind providing a complete stack trace for your error?

It's also possible that you are hit by an issue that https://github.com/elastic/apm-agent-python/pull/881 tries to solve. Would it be possible for you to try that PR in a dev environment to see if it fixes the issue?

**Comment by JannikZed** [comment]
sounds like I'm hitting exactly that issue! I could definitely test that pull request in our dev environment. Could you tell me the quickest way to do that? Do all pull requests get build as NPM packages as well? Or do I need to checkout the github project and build the client locally? :)

**Comment by beniwohli** [comment]
@JannikZed you should be able to install the patched agent like this:

    pip install "git+https://github.com/elastic/apm-agent-python.git@refs/pull/966/merge"

**Comment by JannikZed** [comment]
I can confirm, that the issue got fixed by this commit
