### ISSUE TITLE
[META 355] Add support for shipping user-defined metrics (prometheus)

### ISSUE THREAD

**Issue by henrikno** [elastic/apm-agent-python#972]
**Is your feature request related to a problem? Please describe.**
We want to ship custom metrics that we collect in our python app via APM.

**Describe the solution you'd like**
APM agent is already shipping built-in app metrics such as CPU, memory, it would be nice if we can also add user-defined metrics to this. When using a well-defined metrics library such as prometheus_client it should ideally automatically ship those, or with some config/wrapping.
Java and go agent already has some support for this.

**Describe alternatives you've considered**
We currently set up a HTTP endpoint, configure metricbeat to collect it and ship it to ES. But we also have APM, so we could shorten the cycle, reduce manual configuration and avoid exposing more ports.

**Additional context**
Context: https://github.com/elastic/apm/issues/355

**Comment by beniwohli** [comment]
Prometheus support has been added with version 6.1 of the agent.
