### ISSUE TITLE
Ensure transaction_ignore_urls is centrally configurable

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-python#988]
Meta issue https://github.com/elastic/apm/issues/144 has been implemented in https://github.com/elastic/apm-agent-python/issues/772.

Configuration option has been added in Kibana for the Python agent: https://github.com/elastic/kibana/pull/85734

**The purpose of this issue is to make sure that agent supports central configuration for this option.**

**Comment by beniwohli** [comment]
Hey @AlexanderWert 

this is already implemented and tested. We ensure that configuration updates by central config are respected by calling `config.update()` in the test and then asserting that the new configuration has the expected effect, e.g.

https://github.com/elastic/apm-agent-python/blob/d829eae7d6065d598f65fce797eed5fbe52e6ef0/tests/client/client_tests.py#L376-L392

https://github.com/elastic/apm-agent-python/blob/d829eae7d6065d598f65fce797eed5fbe52e6ef0/tests/contrib/django/django_tests.py#L1596-L1604

https://github.com/elastic/apm-agent-python/blob/d829eae7d6065d598f65fce797eed5fbe52e6ef0/tests/contrib/flask/flask_tests.py#L460-L468
