### ISSUE TITLE
APM agent crashes if the SQL query is too large

### ISSUE THREAD

**Issue by Asaf-m** [elastic/apm-agent-python#991]
**Describe the bug**: ...
Same as https://github.com/elastic/apm-agent-python/issues/827, but with `psycopg2` library instead of Django ORM.

**To Reproduce**

1. use any of `psycopg2` extra utilities, for example `execute_values`, with a query that is sufficiently long.

**Environment (please complete the following information)**
- OS: mac
- Python version: 3.7
- APM Server version: ?
- Agent version: 5.10.0

**Additional context**

The issue is that `psycopg2` is passing the sql as bytes object (bytes array). The agent sql instrumentation [code](https://github.com/elastic/apm-agent-python/blob/master/elasticapm/instrumentation/packages/dbapi2.py#L222-L231) is calling the [`shorten()`](https://github.com/elastic/apm-agent-python/blob/f8977bf5c5d9921f83eed174b94cc48922bc72b2/elasticapm/utils/encoding.py#L182-L217) function which does not support bytes object.

I'm not sure if same behavior applies to `psycopg2` core `execute()` function, or only in the "extras" the query is passed as bytes object.

**Comment by Asaf-m** [comment]
@basepi I see you fixed it last time. it's an easy fix here as well. I can send PR if want...

**Comment by beniwohli** [comment]
@Asaf-m I opened a PR with a fix, #994.
