### ISSUE TITLE
`capture_message` displayed as error in Kibana. 

### ISSUE THREAD

**Issue by Asaf-m** [elastic/apm-agent-python#992]
**Describe the bug**:

Not exactly a bug, more of a question.
`capture_message` creates an `ERROR` event that is shown as error in Kibana.
Is there a way to capture events that aren't errors?

Relevant code: [`capture_message()`](https://github.com/elastic/apm-agent-python/blob/master/elasticapm/base.py#L237-L243) that calls [`capture()`](https://github.com/elastic/apm-agent-python/blob/master/elasticapm/base.py#L219-L235) which has `event_type=ERORR` hardcoded.

**Comment by beniwohli** [comment]
Hi @Asaf-m 

This works as intended. Elastic APM currently only knows a few event types (`TRANSACTION`, `SPAN`, `ERROR`, and `METRIC`). 

We are looking into adding log shipping to the agent itself, which would probably fit your use case better. I can't give a timeline on that, though,

**Comment by gabrieligbastos** [comment]
+1 for LOG SHIPPING to the agent itself
