### ISSUE TITLE
5.10.0 "kind of" regression for elasticsearch instrumentation due to logging of whole body

### ISSUE THREAD

**Issue by HenrikOssipoff** [elastic/apm-agent-python#997]
**Describe the bug**:

The elasticsearch library makes it possible to define your own custom serializer as part of the library. However, the Python agent doesn't take this into account, which can lead to wrong request bodies being collected, and it is possible to downright crash the agent (which unfortunately was what happened to us).

The problem seems to have happened with #940.

**To Reproduce - wrong body**

https://gist.github.com/HenrikOssipoff/a231b45ce504691cd71a5de23a771132

This gist shows a simple Starlette application with a custom serializer.

Using the code, the following document is correctly indexed:

```json
{"_index":"test-index","_type":"_doc","_id":"zrmN0nYBBrB60DkP7BVZ","_score":1.0,"_source":{"numbers":2}}
```

However, the wrong body is recorded with the agent:

![Skærmbillede 2021-01-05 kl  13 39 05](https://user-images.githubusercontent.com/4737224/103647318-69c3f400-4f5b-11eb-8841-b26b60533efc.png)

**To Reproduce - crash**

The following gist shows an application that works perfectly fine with the elasticsearch client, but crashes the apm agent:

https://gist.github.com/HenrikOssipoff/2219d059d3156ab8b11879e1191cefe4

Causes exception `TypeError: keys must be str, int, float, bool or None, not NumberObj`.

I'll admit this is some weird code; this is a simplified version of what we currently use.
The version in our app uses Django's translation module as keys for certain parts of the query, which corresponds to `django.utils.functional.Promise` objects. We're basically looping over these to force-evaluate them, as they're lazy objects.

It works perfectly fine, but crashes the agent.

**Environment (please complete the following information)**
- OS: [e.g. Linux] Linux/Mac
- Python version: 3.9
- Framework and version [e.g. Django 2.1]: Starlette, Django (any version, probably)
- APM Server version: 7.8.0
- Agent version: >= 5.10.0

**Additional context**

I'm not actually sure how best to solve this. The elasticsearch library already supports a wide array of custom serialization, even without using your own custom one: https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/serializer.py

The best case (from a user perspective), would be for the agent to somehow find the correct serializer to use, when dealing with the body. I'm not sure if this is even possible.

**Comment by HenrikOssipoff** [comment]
If anyone else is seeing this, the only fix I've found is to simply downgrade the python agent to <5.10.0 for now.

**Comment by basepi** [comment]
@HenrikOssipoff I think I have managed to implement your "best case" above in #998. Can you please double check by testing for me?

**Comment by HenrikOssipoff** [comment]
@basepi Thank you for looking at it so quick - #998 works like a charm!

I realise this is likely an immense edge case; I doubt many people are using proxy objects as keys for their Elasticsearch queries - so we're very happy to see a fix in the work so fast :)

**Comment by basepi** [comment]
Eh, it's an edge case but we should play nice with custom serializers since they're a feature of our own elasticsearch client. The error was definitely unacceptable.
